### ISSUE TITLE
potential bug in "View all library hits page"

### ISSUE THREAD

**Issue by alan-jarmusch** [CCMS-UCSD/GNPS_Workflows#113]
the tabulated values appear to be formatted incorrectly in the columns

https://gnps.ucsd.edu/ProteoSAFe/result.jsp?task=21aa3e7dc4384db59b5d85d0f9489de8&view=view_all_analog_annotations_DB

**Comment by mwang87** [comment]
addressed issue in library entry, will have to change code to sanitize library search results.
