### ISSUE TITLE
[GC] Example test jobs for automated testing

### ISSUE THREAD

**Issue by mwang87** [CCMS-UCSD/GNPS_Workflows#122]
Deconvolution Workflows

Agilent qTof - High Res - mzML - Skin Map Pilot - 80 files - minutes
LECO Tof - Low Res - cdf - Beer - 42 files - seconds
LECO Tof - Low Res - cdf - Derivatized Human Blood Serum - 117 files - seconds
GC Library Search

Agilent qTof - High Res - mzML - Skin Map Pilot - 80 files
LECO Tof - Low Res - cdf - Beer - 42 files
LECO Tof - Low Res - cdf - Derivatized Human Blood Serum - 117 files

**Comment by mwang87** [comment]
these are the entires that need to be filled out.

**Comment by aaksenov1** [comment]
Agilent qTof - High Res - mzML - Skin Map Pilot - 80 files - minutes
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=b38aaed0fe044c2a87d7c8f7d1821561

LECO Tof - Low Res - cdf - Beer - 42 files - seconds
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=a2b367ac3f664d659588e66ebd5cfee5

LECO Tof - Low Res - cdf - Derivatized Human Blood Serum - 117 files - seconds
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=746fe76afffc4487849746ec86316d33

GC Library Search

Agilent qTof - High Res - mzML - Skin Map Pilot - 80 files
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=26a37b14705a4912805d7314a54498e2

LECO Tof - Low Res - cdf - Beer - 42 files
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=26a37b14705a4912805d7314a54498e2

LECO Tof - Low Res - cdf - Derivatized Human Blood Serum - 117 files
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=6432df9649674a01bdc1edf0eccfdb81

**Comment by mwang87** [comment]
| Deconvolution Job | Proteomics2 | GNPS |
| ------------- | ------------- | ------------- | 
| Agilent qTof - High Res - mzML - Skin Map Pilot - 80 files - minutes | [Success](https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=b38aaed0fe044c2a87d7c8f7d1821561)  | TBD |
| LECO Tof - Low Res - cdf - Beer - 42 files - seconds | [Success](https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=b38aaed0fe044c2a87d7c8f7d1821561) | TBD  |
| LECO Tof - Low Res - cdf - Derivatized Human Blood Serum - 117 files - seconds | [Success](https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=746fe76afffc4487849746ec86316d33) | TBD |

| Library Search Job | Proteomics2 | GNPS |
| ------------- | ------------- | ------------- | 
| Agilent qTof - High Res - mzML - Skin Map Pilot - 80 files - minutes | [Success](https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=26a37b14705a4912805d7314a54498e2)  | TBD |
| LECO Tof - Low Res - cdf - Beer - 42 files - seconds | TBD | TBD  |
| LECO Tof - Low Res - cdf - Derivatized Human Blood Serum - 117 files - seconds | [Success](https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=6432df9649674a01bdc1edf0eccfdb81) | TBD |

**Comment by mwang87** [comment]
@aaksenov1 will ask Krill and Ivan about some failures, also selected wrong files in another failure, he will fix.

**Comment by mwang87** [comment]
Added 

1. https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=303104fe0d2e4183b2f1da32737a11b3
2. https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=9cbfeb8ade73469da14971419540b975
3. https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=b5667a3690cd41b5bdf0821588baa2e0

To tests.
