### ISSUE TITLE
[GC] MSHub workflow mzml file import

### ISSUE THREAD

**Issue by aaksenov1** [CCMS-UCSD/GNPS_Workflows#134]
mzml file import is not functional
Link to an example job:

https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=c44d467f137e4090b116bf6b9650988b

and originally working here:

https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=b38aaed0fe044c2a87d7c8f7d1821561

**Comment by mwang87** [comment]
@aaksenov1 Can you provide the same data with an example of it working?

**Comment by aaksenov1** [comment]
The original job:
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=b38aaed0fe044c2a87d7c8f7d1821561

**Comment by mwang87** [comment]
Deployed, ready to test @aaksenov1

**Comment by aaksenov1** [comment]
Still fails:
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=e1f95073898647f8b8341dacf7b1c570

**Comment by mwang87** [comment]
Proposed fix went live, please test and add test cases here showing working or still broken.

**Comment by aaksenov1** [comment]
All test jobs ran successfully
