### ISSUE TITLE
[NAP_CCMS2 (version 1.2.5)] workflow is not included in CCMS-UCSD/GNPS_Workflows

### ISSUE THREAD

**Issue by amcaraballor** [CCMS-UCSD/GNPS_Workflows#149]
This [NAP_CCMS2 (version 1.2.5)] should be listed in CCMS-UCSD / GNPS_Workflows but currently is not, or is somewhere else?

**Comment by mwang87** [comment]
The workflow is maintained by Ricardo Silva. Closing.
