### ISSUE TITLE
[GC] The balance score value is missing in the library search job output

### ISSUE THREAD

**Issue by aaksenov1** [CCMS-UCSD/GNPS_Workflows#155]
The balance score value is exported from the deconvolution job output and is displayed as one of the columns. The functionality is no longer present in the transferred workflow.

**Comment by zhz125** [comment]
I am not sure I understand the problem.

**Comment by aaksenov1** [comment]
The balance score is missing, these values are transferred from the feature table
<img width="1126" alt="Annotation 2019-09-17 092153" src="https://user-images.githubusercontent.com/54182738/65060405-a0bc6380-d92c-11e9-81d4-3c9557aa8ec8.png">

**Comment by zhz125** [comment]
job id?

**Comment by aaksenov1** [comment]
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=04e8c793b70548e18f76e680f1193265
This is an example, but it is the same for all library searches after moving from proteomics2 to gnps

**Comment by aaksenov1** [comment]
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=23814591421b46849462340f3a34c977

**Comment by aaksenov1** [comment]
In this job balance score is displayed correctly:
https://gnps.ucsd.edu/ProteoSAFe/result.jsp?task=4d50d571ecff425e925dbc9ecb98c921&view=view_all_annotations_DB&show=true
So this is intermittent issue

**Comment by mwang87** [comment]
This is a test case to evaluate whether the Balance Score is being produced correctly:

https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=cadde7e9dd41452fbf0418f7116224cb

The likely culprit is in this piece of code: 

https://github.com/CCMS-UCSD/GNPS_Workflows/blob/master/molecular-librarysearch-gc/tools/molecularsearch-gc/add_mshub_data.py

**Comment by mwang87** [comment]
Fixed, to evaluate, I have rerun the two test cases to see if it works:

https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=4d50d571ecff425e925dbc9ecb98c921
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=bd10ac0fd17044baa8d72f59cbcf61fd

@aaksenov1 Can you follow this progress?

**Comment by mwang87** [comment]
@aaksenov1 Any progress on testing?

**Comment by aaksenov1** [comment]
We re-ran all of the cdf jobs and all of them have balance score displayed correctly, so looking good.

**Comment by mwang87** [comment]
Thanks, closing issue.
