### ISSUE TITLE
[GC] The error in retriving Kovats calculation results

### ISSUE THREAD

**Issue by aaksenov1** [CCMS-UCSD/GNPS_Workflows#156]
The error is generated: "There was an error retrieving the result data for block "main" of workflow type "MOLECULAR-LIBRARYSEARCH-GC"."
Example job:
https://gnps.ucsd.edu/ProteoSAFe/result.jsp?task=04e8c793b70548e18f76e680f1193265&view=view_kovats

**Comment by zhz125** [comment]
it shows the Kovats library dataset is too small for polynomial fitting.

**Comment by aaksenov1** [comment]
Which is not correct, this is for the job that had the Kovats successfully calculated when it was run on proteomics2.
Here's another example where it was successful before but not after moving to gnps. This job has some of the highest quality annotations:
https://gnps.ucsd.edu/ProteoSAFe/result.jsp?task=4d50d571ecff425e925dbc9ecb98c921&view=view_kovats

**Comment by zhz125** [comment]
can you clone the job on proteomics2 so that I can look into the job status? The same with #155

**Comment by aaksenov1** [comment]
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=9d569ee1ff3d4c7789d167bda1a9a3cb

**Comment by mwang87** [comment]
In conversations with @zhz125, it was determined that there is a missing file for the Kovats indices from the library file. This was created from NIST and needs to be present. Currently it is expected to be in the tool folder, but in the future it should not be as we cannot check it in and make it public. This will be hosted in staticlibs and referenced as an absolute path. 

@mwang87 will update.

**Comment by mwang87** [comment]
Addressed in PR:

https://github.com/CCMS-UCSD/GNPS_Workflows/pull/169

and deployed as version_11 on GNPS. 

@aaksenov1 Please test.

**Comment by mwang87** [comment]
@aaksenov1 any progress on testing?

**Comment by aaksenov1** [comment]
Works with corrected RI marker file
Example test job:
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=59c860c50b7f4d29b5eda0407634b550

**Comment by mwang87** [comment]
Confirmed. Closing.
