### ISSUE TITLE
[mmvec] Empty output

### ISSUE THREAD

**Issue by aaksenov1** [CCMS-UCSD/GNPS_Workflows#157]
The job completes but no output is generated (only empty rhapsody_results.tgz file is present). Example jobs:
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=703122ebb22c4306a7087a2e4065146a
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=ca97e18ed85d4aef9ec7c3f18b8e0f5e

**Comment by mwang87** [comment]
Incorrect input for metabolite metadata, needs to be the library identifications
