### ISSUE TITLE
[GC] Add QIIME2 export to the GC workflows output

### ISSUE THREAD

**Issue by aaksenov1** [CCMS-UCSD/GNPS_Workflows#166]

**Comment by mwang87** [comment]
Added and testing here: https://github.com/CCMS-UCSD/GNPS_Workflows/pull/277

@aaksenov1 Please confirm it works on your data.

**Comment by aaksenov1** [comment]
Works, latest job example:
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=766219ebc84f4d42a5606d26f8050fb8
