### ISSUE TITLE
[Classical Networking] Add `ili example to testing and add demo link

### ISSUE THREAD

**Issue by mwang87** [CCMS-UCSD/GNPS_Workflows#171]
- [ ] Example Classical Molecular Networking with `'ili included

**Comment by amcaraballor** [comment]
Hey @mwang87, this one works: [ili_example_classical_MN](https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=04b29a1fddee4516984ae590ee19cb7b) and the 3D model can be accessed here: [3Datta_leaf_trash_spliced_Meshlab_pp_STL](https://www.dropbox.com/s/96khrvy3b834s44/3Datta_leaf_trash_spliced_Meshlab_pp_STL.stl?dl=0)

**Comment by mwang87** [comment]
Thanks @amcaraballor going to add to tests! This is fantastic and will make following up with FBMN versions easier.
