### ISSUE TITLE
[FBMN] Missing Test Cases

### ISSUE THREAD

**Issue by mwang87** [CCMS-UCSD/GNPS_Workflows#173]
1. MZmine2
2. MetaboScape
3. Optimus

**Comment by lfnothias** [comment]
Optimus: https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=d39e3b75cc7844a1b62f58956c3e971b
MetaboScape:  LC-MS/MS https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=f5287df55cba462c87605a88e3f8c87f
MetaboScape with PASEF (one sample only):  https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=655dea30113743608ddebbc73b77d1c9
MZmine2: https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=7e9c4f6a4adb46f8b6ad785c06901e4a

**Comment by mwang87** [comment]
added to gnps/proteomics2 tests
