### ISSUE TITLE
[GC] Document the Carbon Marker Format File

### ISSUE THREAD

**Issue by mwang87** [CCMS-UCSD/GNPS_Workflows#174]

**Comment by mwang87** [comment]
Add to documentation on GNPS as well as write a validator

**Comment by mwang87** [comment]
ETA 10/4/2019

**Comment by mwang87** [comment]
Any updates on this issue?

**Comment by aaksenov1** [comment]
Yes, it is documented in the tutorial and the example file link is added as well.

**Comment by mwang87** [comment]
Please link so we can close this issue.

**Comment by aaksenov1** [comment]
All the links are in the tutorial Melissa pushed to you.

**Comment by mwang87** [comment]
Please link to this issue. Thanks!

**Comment by mwang87** [comment]
https://help.github.com/en/github/managing-your-work-on-github/creating-a-permanent-link-to-a-code-snippet

**Comment by aaksenov1** [comment]
https://github.com/aaksenov1/Human-volatilome-3D-mapping-/blob/4659139a86fab0ee4d517e367218ce73d3f676fd/GC_kovats_SKIN_corrected.csv#L1-L19

**Comment by mwang87** [comment]
https://ccms-ucsd.github.io/GNPSDocumentation/gc-ms-library-molecular-network/

**Comment by mwang87** [comment]
This is incorrectly formatted. @aaksenov1 Please address.

**Comment by robinschmid** [comment]
Please see related issue #271 

Documentation says tab-separated in the text and comma-separated in parameter table.

**Comment by mwang87** [comment]
Addressed in here: https://github.com/CCMS-UCSD/GNPS_Workflows/issues/290
