### ISSUE TITLE
[GC] Balance score values exceeds 100%

### ISSUE THREAD

**Issue by aaksenov1** [CCMS-UCSD/GNPS_Workflows#177]
example job:
https://gnps.ucsd.edu/ProteoSAFe/result.jsp?task=4d55df6b6e73478b8ce32ad4cf3da0a2&view=view_kovats#%7B%22table_sort_history%22%3A%22main.Balance_score(percentage)_dsc%22%7D

**Comment by mwang87** [comment]
Requires rerunning of all jobs with newest MSHub-GC. Old ones don't work as format has changed by ICL code update.

**Comment by mwang87** [comment]
Attempted fix, pushed out, please test.

**Comment by aaksenov1** [comment]
Fixed, we'll test few more to confirm.
https://gnps.ucsd.edu/ProteoSAFe/result.jsp?task=a14efa079df64d0ab954a848c403b5dd&view=view_all_annotations_DB&show=true#%7B%22table_sort_history%22%3A%22main.Balance_score(percentage)_dsc%22%7D
