### ISSUE TITLE
[FBMN] Metaboscape Parser Bug

### ISSUE THREAD

**Issue by mwang87** [CCMS-UCSD/GNPS_Workflows#182]
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=56d0c24a69f94875a60724319c2fb99f
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=8ac11b9bb97c408ab2af3ff4bb340ba2

**Comment by lfnothias** [comment]
The script should handle the two jobs above.

**Comment by mwang87** [comment]
Testing:

https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=c8c567a81f174d9187fc957a422fa32d
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=8d5340f36bd04dc39bbfb64359b5fd4e

**Comment by mwang87** [comment]
In testing, second succeeded, but this is still failing:

https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=c8c567a81f174d9187fc957a422fa32d

Likely a format issue with feature numbering.

**Comment by lfnothias** [comment]
Thank you. This should fix the issue: #185

**Comment by mwang87** [comment]
Deployed, restarting:

https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=c8c567a81f174d9187fc957a422fa32d

**Comment by mwang87** [comment]
looks good, closing issue and putting in change log.
