### ISSUE TITLE
[FBMN] Discussing the mzTab-M upload interface for the FBMN workflow

### ISSUE THREAD

**Issue by lfnothias** [CCMS-UCSD/GNPS_Workflows#187]
Proposal to have two options in the FBMN interface for the input file selection.
Box 1: Option A (as currently): Button 1. feature table and button 2. MGF file
Box 2: Option B (addition): Button 1. mzTab-M and button 2. mzML file(s) 
Shared: metadata table.

This would make things more intuitive for the user, and easier to describe in the documentation.

**Comment by mwang87** [comment]
We could rename the inputs to not be MGF, and say MGF/MSP(Progensis)/mzML(MzTab-m)

**Comment by lfnothias** [comment]
I think that would work. Along with for: feature table or mzTab-M

**Comment by mwang87** [comment]
Sounds good, adding to in progress and will be released in release_12

**Comment by lfnothias** [comment]
Added a quick description of mzTab-M in the GNPSDocumentation (https://github.com/CCMS-UCSD/GNPSDocumentation/pull/94), but will have to update figures etc depending upon the implemented changes.

**Comment by mwang87** [comment]
Updated on input form.
