### ISSUE TITLE
[IIN] Format Documentation for pairs file for FBMN

### ISSUE THREAD

**Issue by mwang87** [CCMS-UCSD/GNPS_Workflows#190]
Add documentation to GNPS Documentation. @xsirdanielx

**Comment by lfnothias** [comment]
I think @robinschimd has already a draft documentation for that

**Comment by mwang87** [comment]
Can @robinschmid you send a PR to the GNPS Documentation? That would be great so we can track it. Let me know if you need any help with it.

**Comment by robinschmid** [comment]
See PR https://github.com/CCMS-UCSD/GNPSDocumentation/pull/99
