### ISSUE TITLE
[IIN] Adding test job 

### ISSUE THREAD

**Issue by lfnothias** [CCMS-UCSD/GNPS_Workflows#191]
Related to #70.
@XsirdanielX and @robinschmid

**Comment by XsirdanielX** [comment]
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=d0f1cd24dc5b4fa0882582974dcb5213

**Comment by XsirdanielX** [comment]
this one seemed to work

**Comment by mwang87** [comment]
Do you have a smaller one that runs faster?

**Comment by robinschmid** [comment]
how about this one:
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=a338360bf58a46a0b7443d374b5fc418
Bile acid standards with IIN. 
No metadata sheet.

**Comment by mwang87** [comment]
Thanks this is perfect. Adding to tests run continuously. 

Ming
