### ISSUE TITLE
[FBMN] enhancement with classical MN-like statistic page

### ISSUE THREAD

**Issue by lfnothias** [CCMS-UCSD/GNPS_Workflows#193]
This is enhancement that would be nice to have quick general insight and track issues.

**Comment by mwang87** [comment]
Can you list out an example output that we would like to have?

**Comment by lfnothias** [comment]
Looking at V2, I think all that would be needed are the following:

-Number of nodes/spectra:
-Number of pairs:
-Number of connected components:
-Number of spectral annotation:
-Number of connected component with spectral annotation:
----
And for IIN related application:
-Number of annotated edges:

**Comment by robinschmid** [comment]
For the IIN paper, statistics are extracted from the graphml and mgf.

Here one example:
**General stats**
![image](https://user-images.githubusercontent.com/10366914/66203334-6bdc3a80-e6a8-11e9-9118-39cd845aaffd.png)

**Stats for nodes with a given minimum n signals** 
![image](https://user-images.githubusercontent.com/10366914/66203462-b362c680-e6a8-11e9-8e58-ba451073e995.png)

**Identification density. Number of nodes with identity in range of x**
![image](https://user-images.githubusercontent.com/10366914/66203551-ead17300-e6a8-11e9-8be8-8544eb060cbc.png)

**Ion identity distribution**
![image](https://user-images.githubusercontent.com/10366914/66203590-02106080-e6a9-11e9-85e2-b1273eb7699b.png)

**Comment by mwang87** [comment]
This is actually a really great idea, pulling it from the GraphML. Then we can re-use on both networks. Will likely go out in release 15.

**Comment by mwang87** [comment]
Assigned to @allegra-aron, she will put together prototype. 

Test input will be GraphML from this download:

https://gnps.ucsd.edu/ProteoSAFe/result.jsp?task=870af5a0b797405e814fc051bf694afb&view=download_cytoscape_data

We will aim as per @lfnothias suggestion, output this:

- [ ] Number of nodes/spectra:
- [ ] Number of pairs:
- [ ] Number of connected components:
- [ ] Number of spectral annotation:
- [ ] Number of connected component with spectral annotation:

**Comment by robinschmid** [comment]
One thing that I was always missing in the graphml is a number of signals in the input spectrum. This is a very important quality detail of the input. Especially interesting, if you look at the singletons. It makes a big difference if they have 0-1 signals or are full of signals.

Do you think you could add "SpectrumSignals" to the graphml as a node attribute?
I currently use the mgf for this - but it would be easier to have this in the GNPS results.

**Comment by mwang87** [comment]
> I currently use the mgf for this - but it would be easier to have this in the GNPS results.

This should be a separate issue that will be addressed separately.

**Comment by mwang87** [comment]
The prototype for this script will be:

./calculate_stats_graphml.py <input graphml> <output stats file>

**Comment by mwang87** [comment]
Specific Steps to Accomplish

- [ ] Download Graphml from GNPS
- [ ] Create git repository for code
- [ ] Create jupyter notebook
- [ ] Load Graphml using NetworkX
- [ ] Get list of nodes from networkx graph
- [ ] Get list of edges from networkx graph
- [ ] Print both of these numbers out
- [ ] Output both of these numbers to file
- [ ] Create python script called calcualte_stats_graphml
- [ ] Learn argparse to set commandline arguments
- [ ] Run on commandline

**Comment by allegra-aron** [comment]
Update as of 10:40 am on 10/25/19:

- [X] Download Graphml from GNPS
- [ ] Create git repository for code
- [X] Create jupyter notebook
- [X] Load Graphml using NetworkX
- [X] Get list of nodes from networkx graph
- [X] Get list of edges from networkx graph
- [X] Print both of these numbers out
- [ ]  Output both of these numbers to file
- [ ]  Create python script called calcualte_stats_graphml
- [ ]  Learn argparse to set commandline arguments
- [ ]  Run on commandline

**Comment by mwang87** [comment]
Here is an example of it running in release_15:

https://proteomics2.ucsd.edu/ProteoSAFe/result.jsp?task=885270411d0a484bb6db8cb7a19e12d1&view=network_statistics

**Comment by mwang87** [comment]
I think we're good on this issue. there are more stats that can be added, but we'll add those as separate issues. @allegra-aron Can you create a new issue with the other stats outputs that woudl be good. Please take inspiration from @robinschmid and classical networking: 

https://gnps.ucsd.edu/ProteoSAFe/result.jsp?task=1ad7bc366aef45ce81d2dfcca0a9a5e7&view=network_statistics

**Comment by allegra-aron** [comment]
- [X] Number of nodes/spectra:
- [X] Number of pairs:
- [X] Number of connected components:
- [X] Number of spectral annotation:

This issue can be closed now. We'll make another issue adding some more stats.
