### ISSUE TITLE
[Qemistree] Initial Implementation

### ISSUE THREAD

**Issue by mwang87** [CCMS-UCSD/GNPS_Workflows#195]
- [x] Example data - start with only MGF no feature table
- [x] Installation Instructions
- [x] Example command line execution
- [x] Workflow prototype

**Comment by mwang87** [comment]
initial working implementation:

https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=5c80591e7db449ff98c509381f172353

Issues with qemistree tree creation.

**Comment by mwang87** [comment]
Fixed issues with tree and network creation:

https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=252fd83712dd461babc317b3c3c25ef6

**Comment by mwang87** [comment]
Example from EMP from Louis

[FBMN Task](https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=8646e3489e724afe91dcb5ec5ac6ca78)

[Qemistree Task](https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=f7526b837e3643a9b1702d55c8ac9022)

**Comment by mwang87** [comment]
Its very slow, likely worth using cplex for ILP solver along with it.

**Comment by mwang87** [comment]
@anupriyatripathi See job:

https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=53f48becfb764a93a028345ac2fb0b38

Please download the output, and try creating the tree. Seems to not generate.

**Comment by anupriyatripathi** [comment]
The tasks look good. I was able to take fingerprints.qza from GNPS workflow and generate a hierarchy. 
An update in the first task: we _do need_ a feature table to run hierarchy generation (make_hierarchy())

**Comment by anupriyatripathi** [comment]
Description | FBMN | Qemistree |
------------|--------|-----------|
QE C18|[Job](https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=cd2cc1a410e144989df55f899839c5bb) | [Job](https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=43ebcbc849fb410497bca9a17d6ed79d)
QTOF C18|[Job](https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=ef28e0f32e2745ee8ff95545f8e8a994) |[Job](https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=f4bdd8e9b3dd4d70bbe8bb0459e58195)

**Comment by mwang87** [comment]
- [ ] Establish Qemistree runs properly in GNPS
- [ ] Commands to generate PCoA with UniFRAC
- [ ] Augment workflow to input metadata file
- [ ] Evaluate structures generated by Sirius

**Comment by anupriyatripathi** [comment]
- [Provide with instructions to compare structures using Tanimoto score] @mwang87

**Comment by mwang87** [comment]
https://gnps-structure.ucsd.edu/structuresimilarity?smiles1={}&smiles2={}

**Comment by mwang87** [comment]
Added metadata on proteomics2. Ready for @anupriyatripathi to test.

**Comment by mwang87** [comment]
Qemistree has an issue running. using the command:

qiime diversity beta-phylogenetic     --i-phylogeny output_folder/merged_data.qza     --p-metric "weighted_unifrac"      --o-distance-matrix output_folder/distance_matrix.qza

I get this error

 (1/2) Invalid value for "--i-phylogeny": Expected an artifact of at least
  type Phylogeny[Rooted]. An artifact of type FeatureData[Molecules] was
  provided.
 (2/2) Missing option "--i-table".

**Comment by mwang87** [comment]
For this command:

qiime diversity beta-phylogenetic     --i-table output_folder/merged_feature_table.qza     --i-phylogeny output_folder/qemistree.qza     --p-metric "weighted_unifrac"      --o-distance-matrix output_folder/distance_matrix.qza

Current see this bug:

Plugin error from diversity:

  'latin-1' codec can't encode character '\u03b2' in position 3405: ordinal not in range(256)

Debug info has been saved to /tmp/qiime2-q2cli-err-4ocq2823.log

**Comment by mwang87** [comment]
issues with running are addressed now. @anupriyatripathi will rerun and side project is to continue evaluation of results.

**Comment by mwang87** [comment]
Technical implementation seems to be fixed. 

Research will continue out of band
