### ISSUE TITLE
[Library Search/Molecular Networking GC] No option to upload Metadata in the current version

### ISSUE THREAD

**Issue by amcaraballor** [CCMS-UCSD/GNPS_Workflows#196]
The current version of [Library Search/Molecular Networking GC](https://gnps.ucsd.edu/ProteoSAFe/index.jsp?params=%7B%22workflow%22:%22MOLECULAR-LIBRARYSEARCH-GC%22%7D) (even the [Beta version](https://proteomics2.ucsd.edu/ProteoSAFe/index.jsp?params=%7B%22workflow%22:%22MOLECULAR-LIBRARYSEARCH-GC%22%7D)) does not allow the upload of metadata files. See Search Options>Spectrum Files>Select Input Files> [The current options to upload files are: Spectrum Files, Library Files, Carbon Marker Files and Quant Table]. The Metadata option is missing.

**Comment by mwang87** [comment]
- [ ] Add tasks for MSHub and Library Search and metadata associated with it
