### ISSUE TITLE
[Library Search/Molecular Networking GC] Networking Parameters and Written Description

### ISSUE THREAD

**Issue by amcaraballor** [CCMS-UCSD/GNPS_Workflows#197]
Is it possible to include the "Methods and Citation for Manuscripts [ Networking Parameters and Written Description ]" as part of the output (Status window) from this workflow, as it has been implemented into the Molecular Network workflows (classical and feature-based)?

**Comment by mwang87** [comment]
Sure, can you write a basic description of it that we can use as a template?

**Comment by aaksenov1** [comment]
Once it is submitted will put it on BioRxiv and put citation up.

**Comment by amcaraballor** [comment]
Sure @mwang87. Here I suggest a template based on the settings currently available in the workflow. The values need to be modified according to the specific job: 

**Network Description [Library Search/Molecular Networking GC workflow ]**

A molecular network was created with the Library Search/Molecular Networking GC workflow (https://gnps.ucsd.edu/ProteoSAFe/index.jsp?params=%7B%22workflow%22:%22MOLECULAR-LIBRARYSEARCH-GC%22%7D) on the GNPS website (http://gnps.ucsd.edu). The parameters for library search were set it follows: FORCE_EXACT_MATCH 1,  Precursor Ion Mass Tolerance: 2000 (there is no precursor ion in EI), Min Matched Peaks: 6, Fragment Ion Mass Tolerance: 0.5 Da, Score Treshold: 0.85. Top 1 Hits Per Spectrum  and No analogs search were performed. Filter StdDev Intensity, Filter SNR Intensity and Min Peak Int were set as 0 and no additional filtering was applied. A network was then created where edges were filtered to have a cosine score above 0.7. Further, edges between two nodes were kept in the network if and only if each of the nodes appeared in each other's respective top 10 most similar nodes. Finally, the maximum size of a molecular family was set to 100, and the lowest scoring edges were removed from molecular families until the molecular family size was below this threshold. For Kovats Index Calculation, the Cosine Threshold for Kovats Filter was set as 0.9. Retention Time Window Starts at 3 (min). Kovats Retention Index Filtering Window set as +/- 10 %. Retention Time Window Ends at 12 (min).  

**Citation**
[include citation here when available]

**Comment by mwang87** [comment]
Have added to Release_15. Please rerun to test.

**Comment by aaksenov1** [comment]
Works as it should.
