### ISSUE TITLE
Analog hits are not reported in graphml or cystoscape download

### ISSUE THREAD

**Issue by XsirdanielX** [CCMS-UCSD/GNPS_Workflows#20]
Analog matches are not reported in the graphml nor teh cytoscape output.
Woudl also be great to get them wit unique column header ( eg XXX_analg) to distuingish from exact library hits.
Thanks!

**Comment by mccall-lab-OU** [comment]
Agree that this is really necessary to get the full benefit of annotation propagation.

**Comment by mwang87** [comment]
Addressing here: https://github.com/CCMS-UCSD/GNPS_Workflows/pull/261

Test Case: https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=ff2d0c9e44d64d999776439f789330d7

**Comment by mwang87** [comment]
Test case seems to work. Merging.

**Comment by irinakoester** [comment]
This issue still exists. Analogs in the graphML are just the libraryIDs again.
I assume that means MolNetEnhancer is also only using LibIDs and not Analogs?
