### ISSUE TITLE
[USI] Adding an option to display m/z values of fragment ion

### ISSUE THREAD

**Issue by lfnothias** [CCMS-UCSD/GNPS_Workflows#201]
For the two views. It would be nice to have an option for that. They could be vertical.
Ideally, we would need to have a user defined threshold for the m/z display
https://metabolomics-usi.ucsd.edu/spectrum/?usi=mzspec:GNPSLIBRARY:CCMSLIB00000840338

**Comment by mwang87** [comment]
@bittremieux Is it possible to add masses to the peaks as an option in spectrum_utils?

**Comment by mwang87** [comment]
Addressed in https://github.com/mwang87/MetabolomicsSpectrumResolver/issues/3
