### ISSUE TITLE
[Networking] Advanced Qiime2 Integration

### ISSUE THREAD

**Issue by mwang87** [CCMS-UCSD/GNPS_Workflows#202]
1.  Bring data with metadata
2. Explore qiime2 capability and define analyses that can be performed on certain classes of data
3. Produce qiime2 command lines to produce at least once what we would want to provide
4. Test and validate results on your data

**Comment by mwang87** [comment]
Next Steps

- [ ] Find example data to analyze with SEED projects - @kcweldon20 
- [ ] Run through GNPS to create qza and manually create permanova @kcweldon20 
- [ ] Exploratory bi-plot analysis @kcweldon20 @alan-jarmusch 
- [ ] Prototype Parsing of Metadata file to determine columns to consider for Permanova @cmaceves 
- [ ] Determine what to give to user: qzv, qza, extracted table, naming? @fernie0341

**Comment by cmaceves** [comment]
@mwang87 in which directory should I put the metadata parser script?

**Comment by mwang87** [comment]
@cmaceves 

https://github.com/CCMS-UCSD/GNPS_Workflows/tree/master/feature-based-molecular-networking/tools/feature-based-molecular-networking/scripts

**Comment by kcweldon20** [comment]
- [ ] Chrissy writes metadata script
- [ ] Ming implements Biplot (Kelly provides code)
- [ ] Alan and Ming figure out how to put masses or annotations on the arrows 
- [ ] Kelly provides code for PERMANOVA
- [ ] Fernie naming stuff (outputs)
- [ ] Kelly provides GNPS job to work with (Sejal)

**Comment by kcweldon20** [comment]
Example Dataset: Seed Grant B0016
Disease-associated microbial species, for disease diagnosis and prevention of Type 1 diabetes in children ages 7 to 18. 
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=c29599fbe6cf4425b5ab8fc10eb6985d

**Comment by kcweldon20** [comment]
PCoA Biplot Code

1) Calculate Beta Diversity
`qiime diversity beta \
 --i-table categorical_ms2.qza \
 --p-metric canberra \
 --o-distance-matrix canberra_qiime2.qza`

2) Compute PCoA
`qiime diversity pcoa \
  --i-distance-matrix canberra_qiime2/distance_matrix.qza \
  --o-pcoa pcoa_canberra_qiime2.qza`

3) Compute Relative Frequency Table for Biplot
`qiime feature-table relative-frequency \
  --i-table categorical_ms2.qza \
  --o-relative-frequency-table relative_frequency.qza`

4)Compute PCoA Biplot
`qiime diversity pcoa-biplot \
  --i-pcoa pcoa_canberra_qiime2.qza \
  --i-features relative_frequency.qza \
  --o-biplot pcoa_biplot_canberra_qiime2.qza`

5)Visualize PCoA Biplot
`qiime emperor biplot \
  --i-biplot pcoa_biplot_canberra_qiime2.qza \
  --m-sample-metadata-file metadata.txt \
  --p-number-of-features 10 \
  --o-visualization pcoa_biplot_emperor_qiime2/visualization.qzv`

**Comment by kcweldon20** [comment]
PERMANOVA Code (Per category) Using Beta Diversity Calculation
```
  qiime diversity beta-group-significance \
  --i-distance-matrix canberra_qiime2.qza \
  --m-metadata-file metadata.txt \
  --m-metadata-column COLUMN \
  --o-visualization PERMANOVA_Group.qzv
```

**Comment by fernie0341** [comment]
I would recommend that we change the GNPS output links as follows

 ## Advanced Views - QIIME2 Views
View qiime2 PCoA Plot *(changed Emperor to PCoA)* 
Download qiime2 PCoA qzv *(changed Emperor to PCoA)*
View qiime2 PCoA Biplot 
Download qiime2 PCoA Bilplot qzv 
View qiime2 Permanova *(this option would be used if we visualize the permanova on GNPS)*
Download qiime2 Permanova qzv
Download qiime2 Permanova tsv

**Comment by mwang87** [comment]
What are the filenames? What is the navigation structure? Which Permanova? We can generate it for a variety of columns.

**Comment by kcweldon20** [comment]
We need to discuss the distance matrix to use on the PCoA and PCoA biplot outputs from GNPS. Can also discuss the idea of multiple outputs.

**Comment by cmaceves** [comment]
I was going to use a Euclidean distance matrix for the permanova implementation.

**Comment by mwang87** [comment]
We have included the output in FBMN to directly link to the biplot in view.qiime2.org

**Comment by mwang87** [comment]
Separating this issue out https://github.com/CCMS-UCSD/GNPS_Workflows/issues/258 https://github.com/CCMS-UCSD/GNPS_Workflows/issues/259
