### ISSUE TITLE
[FBMN] Problem Qiime2 display

### ISSUE THREAD

**Issue by lfnothias** [CCMS-UCSD/GNPS_Workflows#204]
Error with Qiime2 display for a large job, I am not sure what's wrong.
https://gnps.ucsd.edu/ProteoSAFe/result.jsp?task=d858cd5cfdcc494f9aa861a2805da16f&view=group_by_compound

I tried downloading the qzv and tested on view.qiime2.org but got the same error message.

**Comment by mwang87** [comment]
Can you run with latest version on proteomics2? There are a few updates should help with debugging.

Thanks!

**Comment by lfnothias** [comment]
Ok. Rerunning a fast version of the job. It is gonna take 35 min or so.
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=eea09e8f64b3460087c054a5dbdafa66

**Comment by lfnothias** [comment]
Job completed. Still the error.

**Comment by mwang87** [comment]
Got it thanks! Will look at!

**Comment by mwang87** [comment]
Metadata conflicts with qiime2 controlled keys. Closing.

**Comment by mwang87** [comment]
Fix currently will be on the user, but can address in this: 

https://github.com/CCMS-UCSD/GNPS_Workflows/issues/220
