### ISSUE TITLE
[MS2LDA] The workflow was forcibly terminated by the computational back end.

### ISSUE THREAD

**Issue by lfnothias** [CCMS-UCSD/GNPS_Workflows#206]
"The workflow was forcibly terminated by the computational back end.
The most likely reason is for exceeding this node's memory usage quota."
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=dcbc99284e4e42d495bcd559999caaf2

It is a huge MGF file [57k features] from the EMP project processed with MZmine2.

**Comment by lfnothias** [comment]
I tried without MS1 table and same results:
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=648a425d2d934701a87fa0df50854670

**Comment by justinjjvanderhooft** [comment]
I am pretty sure that the LDA run out of memory. It may work with 8,000 features or maybe 10,000. I recommend trying a few subsets (i.e., chunking it), then uploading the more occurring and relevant motifs to motifdb, and then rerunning the LDA with predefined motifs. That might work.... I hope to get funding to tackle large scale substructure finding!

**Comment by lfnothias** [comment]
@justinjjvanderhooft do you think if we increase the RAM (like 2 fold), we have a chance to compute that job ?

**Comment by justinjjvanderhooft** [comment]
My guess is not as 57K features is pushing it too much....

**Comment by justinjjvanderhooft** [comment]
The current implementation is not suitable for this amount of data I am
afraid....

**Comment by lfnothias** [comment]
Got it. Thanks a lot for the help.

**Comment by helenamrusso** [comment]
Hi @justinjjvanderhooft ! I'm having this message too in some MS2LDA jobs I'm trying to run.
One has also about 50k features... but the other two have about 24k and 17k features.
Would there be a way to run them? At least for the 17k? Thanks!

**Comment by justinjjvanderhooft** [comment]
Hi @helenamrusso, thanks for your message. As for the 17K one, you could consider to double-check the minimum MS2 noise you are using as the number of MS2 features (words) is influencing the total memory usage as well. Another strategy is to enlarge the binning: if you are currently using 0.005, you could try 0.01 - that will also reduce the total number of (MS2) features. An alternative strategy is to take a smaller [representative] subset (6K for example) and annotate Mass2Motifs in there. You can then create a MotifSet from them and use your MotifSet from MotifDB with some added "free motifs" for other chunks of the dataset. Happy to discuss more over email if you want.
