### ISSUE TITLE
[MolNetEnhancer] MetaboDistTree related error 

### ISSUE THREAD

**Issue by justinjjvanderhooft** [CCMS-UCSD/GNPS_Workflows#212]
Looks like the metabodisttree.py file has difficulties reading/decoding a json. Will clone to see if it is reproducible.

https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=4bd699c3053141ad972a507c58eff14f

/data/ccms-gnps/tools/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py:843: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
{'createtime': '2019-09-11 00:54:57.0', 'protected': 'false', 'workflow': 'METABOLOMICS-SNETS-V2', 'description': 'ValidationStudy_DrugMetabolism_100Urines_pHILIC_POS_Top10stepped_QExact_0_25_0_005_0_55_2_500_MCCS100 V2', 'user': 'jjjvanderhooft', 'files': [], 'status': 'DONE'}
Traceback (most recent call last):
  File "/data/ccms-gnps/tools/molnetenhancer/release_12/metabodisttree.py", line 50, in <module>
    response_dict = r_post.json()
  File "/data/ccms-gnps/tools/anaconda3/lib/python3.5/site-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/data/ccms-gnps/tools/anaconda3/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/data/ccms-gnps/tools/anaconda3/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/data/ccms-gnps/tools/anaconda3/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Tool execution terminates abnormally with exit code [1]

**Comment by justinjjvanderhooft** [comment]
Rerunning gave the same error. Will also try it for a V1 MN of this data set....

**Comment by justinjjvanderhooft** [comment]
Running from Proteomics2 also resulted in the same error - I think that is the same version running there....

**Comment by mwang87** [comment]
Thanks seems like a metabodistree error, will look into it.

**Comment by mwang87** [comment]
Adding to tests so we can catch this in future.

**Comment by justinjjvanderhooft** [comment]
Thanks @mwang87! FYI: The V1 Molecular Network of the same data did finish okay: https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=feb319ceb94141a19f0778bfa380ae3c
So it is something added/done by V2 MN that causes the hick-up....

**Comment by mwang87** [comment]
Gracefully handling errors for MolNetEnhancer if it fails, will address underlying issue in release_14. Non-fatal error will be addressed in release_13.

**Comment by justinjjvanderhooft** [comment]
@mwang87 whilst we are at it - could you add this one to the tests as well:
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=904d580291e14933b5f0febcd091025d
(looks like the same error is causing it)
This is the Rhamnaceae data that I am planning to use as example for a workshop in mid-December as we have recently published the results of that. 

FYI: in a slightly earlier release it did work:
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=37ceb84af0ff478aa96ae2ea8c343013
However, trying to look at the QIIME plots returns: Error: Network error, recieved 500 from server.
This is also true for the current release. Is it an idea to add the zipped QIIME file to the download?

The CytoScape viewer did work for this job - this is failing for larger jobs (but I can see why :) )

**Comment by justinjjvanderhooft** [comment]
@mwang87 - FYI: regarding https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=37ceb84af0ff478aa96ae2ea8c343013 - if we manage to get the QIIME to display the ClassyTree separation, I will include this in the workshop I will need to prepare for December. I noticed that you are also running a GNPS workshop then in San Diego and you may well want to use the same (published) example? Happy to share the slides I will make on this in due time....

**Comment by mwang87** [comment]
Addressing here:

https://github.com/CCMS-UCSD/GNPS_Workflows/pull/260

**Comment by mwang87** [comment]
@justinjjvanderhooft Worth testing. Please take the above workflow and clone it and add in your own tasks to test. Let me know if it works out for you. Make sure the version you're testing is: 

Version classytree_cluster:release_15

**Comment by justinjjvanderhooft** [comment]
Thx - running a test now. Could you see the QIIME PCoA based on ClassyTree in Emperor? In the job you shared the CytoScape view looked good but I could not see the Emperor plots (500 error like before).
Link to test: https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=cd0472238e5f4f36994a366dfd0b40a4

**Comment by justinjjvanderhooft** [comment]
The test finished - classifications look okay - the ClassyTree results still do not seem to load into the QIIME emperor plot (for me).

**Comment by mwang87** [comment]
@justinjjvanderhooft This job has no quantification output and thus metabodistree won't work.

**Comment by justinjjvanderhooft** [comment]
Ah okay - did not realize this version needs an MS1 quantification file to work.

**Comment by mwang87** [comment]
Does not need MS1 quantification, just simply needs quantification. Can be MS2 spectra counts as well.

**Comment by justinjjvanderhooft** [comment]
Ah, but don't all MN jobs have that? Apparently not so.... I have not purposely switched that off. Should I rerun the MN with different settings?

**Comment by mwang87** [comment]
Yes, Classical Mol Net can be switched off. Its the bucket table output.

**Comment by justinjjvanderhooft** [comment]
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=c2654ae3f8d345f3ae6dc4648c49da20
That's a MolNetEnhancer job with Qiime2 bucket enabled - no direct view either. Thanks for spotting that this was disabled - I will keep an eye on this in the future!

**Comment by justinjjvanderhooft** [comment]
@mwang87 this is a FBMN run of the Rhamnaceae data - https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=58e19418e0934a02ac11f12a26ff4464 Here, the direct qiime view does not work as the zip file is not recognised. I have also downloaded the file and uploaded it into qiime directly. Should this normally work for FBMN runs? I realise we go slightly off-topic here but it seems to be related (if we want to show the Rhamnaceae PCoA results without and with MolNetEnhancer)....

**Comment by mwang87** [comment]
molnetenhancer should work with both. 

Do you mean show PCoA with and without metabodisttree instead of molnetenhancer?

**Comment by justinjjvanderhooft** [comment]
I can confirm MolNetEnhancer runs okay for both situations. I was/am looking for reasons why the PCoA plots do not show up. I get the feeling that there is an issue with Rhamnaceae data set as the regular PCoA does not show up either. 
Of course, it is a good suggestion to show both plots (without/with ClassyTree) comparative next to each other, but that would be an enhancement for the future I would say :-)

**Comment by mwang87** [comment]
Can you link the molnetenhancer job so we can take a look at the error with metabodisttree. Thanks!

Now that we're releasing it more widely, definitely running into some growing pains.

**Comment by justinjjvanderhooft** [comment]
Sure - no problem! Happy to see it growing :-)

Classical MN: https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=b56c55a48ccb4fd594d04862ff932f2b

FBMN: https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=6c82526413194f86824cf2c07a0102e7

**Comment by justinjjvanderhooft** [comment]
and the FBMN network: https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=58e19418e0934a02ac11f12a26ff4464

**Comment by mwang87** [comment]
This [FBMN](https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=58e19418e0934a02ac11f12a26ff4464) input does not conform to the format for feature quantification table from MZMine2. 

Here is documentation on how to export: https://ccms-ucsd.github.io/GNPSDocumentation/featurebasedmolecularnetworking-with-mzmine2/#10-use-the-gnps-export-module

**Comment by mwang87** [comment]
This [Classical Networking](https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=29f6477902b24169b3c32121132331be) only has a single file as input. PCoA does not make sense for it and thus metabodisttree will not work.

**Comment by mwang87** [comment]
Since both of these issues can be explained as input error, closing issue.
