### ISSUE TITLE
[IIN] Adapting XCMS-CAMERA for IINxFBMN

### ISSUE THREAD

**Issue by lfnothias** [CCMS-UCSD/GNPS_Workflows#217]
Yay ! Thanks to @jorainer @mar-garcia @robinschmid, the workflow is almost ready. About to test the intput files, and will provide test job here very soon.

Referencing the GitHub issue:
https://github.com/DorresteinLaboratory/XCMS3_FeatureBasedMN/issues/10
and on going PR:
https://github.com/DorresteinLaboratory/XCMS3_FeatureBasedMN/pull/9

**Comment by lfnothias** [comment]
Thanks to @jorainer and @mar-garcia, XCMS-CAMERA can now output files for IINxFBMN.
See https://github.com/DorresteinLaboratory/XCMS3_FeatureBasedMN/issues/10

I have updated our xcms_converter in the FBMNxIIN workflow. Now, it will check the type of the feature quantification table and process accordingly.
Type A. XCMS for FBMN -> process like before into MZmine like table
Type B. XCMS for FBMNxIIN -> make IIN MZmine-like format (with correlated groups etc).

I was able to convert the type A and B table smoothly locally. And also process the resulting files with FBMNxIIN (using MZmine option) but there is an issue @mwang87 :
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=990fb6e07a1a464697f46fa8aaae7f85

It is breaking the create_network_edges_outputformatting.py. Maybe some weird characters ?

This is a type B  feature quantification table
[camera_iin_quant_table_sub.txt.zip](https://github.com/CCMS-UCSD/GNPS_Workflows/files/3770433/camera_iin_quant_table_sub.txt.zip)
and the converted table:
[camera_iin_quant_table_sub_parsed.csv.zip](https://github.com/CCMS-UCSD/GNPS_Workflows/files/3770431/camera_iin_quant_table_sub_parsed.csv.zip)

Here are some test jobs with XCMS CAMERA files that should work with the new xcms_parser.
All features: https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=b36659724ee748f2b6868f4973c726ef
Subset of the features (MS1 annotated): https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=b36659724ee748f2b6868f4973c726ef

**Comment by jorainer** [comment]
If there is something from our side that we can do (e.g. export fields with quotes, checking/replacing special characters **before** export or adding/removing certain columns) let us know.

**Comment by lfnothias** [comment]
It seems that the xcms_conveter.py failed https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=69c1dc7955104401800c68b1f7bde142

**Comment by mwang87** [comment]
Please put a value in the score column. I've updated the documentation here to reflect the format:

https://ccms-ucsd.github.io/GNPSDocumentation/featurebasedmolecularnetworking/#advanced-extras

**Comment by lfnothias** [comment]
The script was updated and it works fine ! @robinschmid @mwang87 
@jorainer, note that the XCMS-CAMERA-IIN export has to be updated. The "score" column cannot have empty values. So we should have 0 if no score available, or provide actually some CAMERA score.

**Comment by robinschmid** [comment]
0 should be fine for now.
Later it would be nice to have the score.

**Comment by jorainer** [comment]
I've updated our scripts and we're now exporting a score of `0`: the updated edge lists:

[camera_iin_edgelist.csv.zip](https://github.com/CCMS-UCSD/GNPS_Workflows/files/3778718/camera_iin_edgelist.csv.zip)
[camera_iin_edgelist_sub.csv.zip](https://github.com/CCMS-UCSD/GNPS_Workflows/files/3778722/camera_iin_edgelist_sub.csv.zip)

**Comment by lfnothias** [comment]
Nice ! Thanks @jorainer 
One last thing we were discussing with @robinschmid is that, usually for IIN we use only annotated edges (with "MS1 annotation) in the edge table as default, otherwise it gets really messy.
So, it would be possible to have an additional paramater to specify the edge types to include in the export function ? Alternatively, we could image having separate export steps in the script.

**Comment by robinschmid** [comment]
Great that it works :)

Either an optional subsetting of the edges.

or export the two subsets to different files:
MS1_annotation_edges.csv
correlation_edges.csv

**Comment by jorainer** [comment]
Sure. We will make an update to the workflow. We would then only export edges file and features file and mention that it would be possible to export all, but it is adviseable to export only those with adduct annotations. Do you need then also a MS2 spectra mgf file with only the spectra for the features with MS1 adduct annotation?

**Comment by robinschmid** [comment]
- the mgf is never filtered. It always contains a representative MS2 spectrum for each feature list row.
- the quant table either contains:
    - all rows with MS2
    - all rows with MS2 or an MS1 annotation

So only the edges file is changed here.

**Comment by jorainer** [comment]
I made a PR with the fixes (https://github.com/DorresteinLaboratory/XCMS3_FeatureBasedMN/pull/12). The edges and features files will only contain features with adduct annotations:

[camera_iin_edgelist.csv.zip](https://github.com/CCMS-UCSD/GNPS_Workflows/files/3783841/camera_iin_edgelist.csv.zip)
[camera_iin_quant_table.txt.zip](https://github.com/CCMS-UCSD/GNPS_Workflows/files/3783842/camera_iin_quant_table.txt.zip)

**Comment by lfnothias** [comment]
Hey @jorainer,

- I am confused. The edglist file above contains edges that are either "MS1 annotation" and "MS1 correlation" but all have an "Annotation". Is that normal for CAMERA ?
- For the quant_table, like @robinschmid, it is preferred to have the entire quant table (for all the features regardless of annotation/correlation/ms2). Which is essentially the one we were exporting before for FBMN. The same is true for the MGF who stays the same.

**Comment by jorainer** [comment]
> I am confused. The edglist file above contains edges that are either "MS1 annotation" and "MS1 correlation" but all have an "Annotation". Is that normal for CAMERA ?

That is indeed strange. I'll have a look into that.

> For the quant_table, ...

OK, then I'll not export the subsetted feature table - I'll check how to best do that and will update the pull request.

**Comment by lfnothias** [comment]
Sounds great @jorainer !

**Comment by robinschmid** [comment]
Thanks @jorainer 

The quant table needs to hold the info of all features that are mentioned in the mgf or additional edges file. 
So the subsetting of the feature table should combine the *rules* that are applied to mgf and edges.csv.

In MZmine we have the option to limit the export to: 
1. all features with MS/MS
1. all features with MS/MS OR annotation
1. *all features with MS/MS AND annotation*

The mgf, edges file, and quant table are filtered accordingly. 
The last option is not very important. The second option allows us to get more insight into the relative ionization pattern.

**Comment by jorainer** [comment]
> I am confused. The edglist file above contains edges that are either "MS1 annotation" and "MS1 correlation" but all have an "Annotation". Is that normal for CAMERA ?

The thing was that I forgot to change the EdgeType to "MS1 annotation" when the edge describes two isotopes. I fixed that. Now you get "MS1 Annotation" for both, edges combining features being adducts of the same compound **OR** isotopes. 

Thanks @robinschmid for the explanation of the output formatsof MZmine. I will change the workflow accordingly and will show an example how to export the files for case 2. describing also the other possibilities (again, in the end it is simple subsetting in R that users can do on their own). Is that OK for you?

**Comment by jorainer** [comment]
I've updated the script and the workflow. What I'm doing in the workflow now is the following:

- export the edge files **containing only** features with adduct or isotope annotation:
[camera_iin_edgelist.csv.zip](https://github.com/CCMS-UCSD/GNPS_Workflows/files/3793187/camera_iin_edgelist.csv.zip)

- add the adduct information and all other information from camera to the *main* quant table. This one contains now **all** features:
[xcms_all.txt.zip](https://github.com/CCMS-UCSD/GNPS_Workflows/files/3793437/xcms_all.txt.zip)


- the mgf file with the MS2 spectra - same as before.
[ms2spectra_maxTic.mgf.zip](https://github.com/CCMS-UCSD/GNPS_Workflows/files/3793441/ms2spectra_maxTic.mgf.zip)


This is based on the comment from @lfnothias above saying that the feature and mgf file does not have to be subsetted - let me know it I should subset any of the files, it would not be a problem. I just wanted to keep it as simple as possible for the user...

**Comment by robinschmid** [comment]
Sounds good. We can just give out examples of how to subset to achieve specific results and users can easily adapt. 
Thanks, @jorainer

**Comment by lfnothias** [comment]
Hey @jorainer the link to the last edge file is empty.

**Comment by jorainer** [comment]
Uh, sorry. Had some network issues. Here it is:

[camera_iin_edgelist.csv.zip](https://github.com/CCMS-UCSD/GNPS_Workflows/files/3802848/camera_iin_edgelist.csv.zip)

**Comment by lfnothias** [comment]
Thanks. Running a test job here:
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=1602e1709167425cac1c5441d9919a57

**Comment by robinschmid** [comment]
Great :)

**Comment by jorainer** [comment]
I've updated the workflow in PR https://github.com/DorresteinLaboratory/XCMS3_FeatureBasedMN/pull/12 accordingly.

**Comment by lfnothias** [comment]
@mwang87 the implementation is completed.

**Comment by lfnothias** [comment]
Closing the issue. This is a test job for XCMS-CAMERA and IIN: https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=1602e1709167425cac1c5441d9919a57
