### ISSUE TITLE
[IIN] Adapting MS-DIAL for IINxFBMN

### ISSUE THREAD

**Issue by lfnothias** [CCMS-UCSD/GNPS_Workflows#218]
Working with @hiroshitsugawa (hiroshi.tsugawa@riken.jp) for the integration of MS-DIAL for IINxFBMN. I will provide test job and maybe update on the ms-dial_converter.py within couple of weeks.

**Comment by robinschmid** [comment]
Do you know his time schedule for this integration?
If it is done before we finally submit, he can be a co-author for the IIN paper.

**Comment by lfnothias** [comment]
ETA by the end of the month.

**Comment by lfnothias** [comment]
Hey @robinschmid,
Hiroshi provided the following edge table. 
[GnpsTable_0_20191132250.txt.zip](https://github.com/CCMS-UCSD/GNPS_Workflows/files/3806155/GnpsTable_0_20191132250.txt.zip)

it is currently a tab-separated, so I am gonna see if he can update that. 
There are multiple EdgeTypes which I believed are fine. 
For the "Annotation" column, shall we ask for similar format with adduct. Like instead of 
'[M-C6H8O6-H]-_[M-C6H10O5-H]-_dm/z14.01669'  the following
'[M-C6H8O6-H]- [M-C6H10O5-H]- dm/z14.01669'

**Comment by robinschmid** [comment]
The most important part to harmonize, would be to change the EdgeType(s) to:
- MS1 annotation    (for IIN edges)
- MS1 correlation    (for correlated features)

The question is - what is the correlation column?
Chromatogram-based annotation?
or Alignment-based annotation?

The annotation column is actually not very important, as all the information is also provided in the quant table. It is just a nice way to visualize later in cytoscape.

Maybe you could ask him if he can export one file per edge type. This would make it easier for the user to filter.

![image](https://user-images.githubusercontent.com/10366914/68188831-5198c380-ffaa-11e9-8551-90ca1f199be1.png)

**Comment by lfnothias** [comment]
It seems that the edge annotation (Adduct annotation) is separated from the chromatogram or MS2-based annotation. Unlike IIN where edges are uniques.

1139 | 1151 | Adduct annotation | 1 | [M-H]-_[M+FA-H]-_dm/z46.01355
-- | -- | -- | -- | --
1139 | 1151 | MS2-based annotation | 1 | The precursor ion in higher m/z's MS/MS; _dm/z46.01355

1139 | 1151 | Chromatogram-based annotation | 1 | Similar chromatogram
-- | -- | -- | -- | --

Can IIN currently have two different edges for one pair of nodes ? Or the information is merged one in one edge ?

**Comment by robinschmid** [comment]
In the current mzmine version we only export the annotation edges - there is an option to also export all correlation edges. Then you would have two edges. This is supported by the additional edges parameter in GNPS.

### Regarding the MS-DIAL export
You will have some with mutiple additional edges and this is ok.
The easiest way would be to separate them into different files to let the user choose.

![image](https://user-images.githubusercontent.com/10366914/68236557-acabd400-0005-11ea-8956-957052521398.png)

**Comment by lfnothias** [comment]
Yeah but unlike for the CAMERA case, the number of edges seems manageable. 
MS2-based = 113
Chromatogram annotation = 255
Alignement annotation = 11
Adduct annotation = 28

Plus, the user can filter the table him/herself, so maybe it it fine.

I actually think the easiest is to keep MS-DIAL terminology, so it is consistent with how they generate these. So I propose we keep the edge file and just update to tab-separated format and cleaning the adduct annotation.

**Comment by robinschmid** [comment]
The number of edges is dependent on the settings and dataset. This one was a negative mode - I guess that for positive mode we will have more edges.

I think this would be very inconvenient for most of the users. 
With all these edges the cytoscape layout will be destroyed and I do not think that users will delete the edges and redo the layout. They will be scared off by the edge overload.
Don't you think so?

**Comment by lfnothias** [comment]
I understand your point. But shall we have 4 different edge files exported ?

**Comment by robinschmid** [comment]
Yeah. Why not?
I mean optionally, it would be nice to have the choice to select the edges to export in MS-DIAL.
If not, the best option is 4 different files. This way the user can choose the edges. 

IIN edges (MS1 annotation) are very limited whereas correlation or MS2 annotation could create a high number of wrong edges. (Still helpful in many cases - but also wrong in the same high number of cases)

**Comment by lfnothias** [comment]
Ok. I am reaching out and see if that's possible.

**Comment by robinschmid** [comment]
thanks Louis :)

**Comment by lfnothias** [comment]
Hiroshi provided the set of files, but there is an error. 
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=5417700b95e845f7be5b320228ceaf8c
Without the edge file, it is fine https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=65f36817aca341ac9ad363cf6edb9844

@robinschmid do you know if the GNPS workflow accepts edge between a feature with MS2 and one without MS2 ?  ?Or between two features without MS2 ?
[MS_DIAL_IIN.zip](https://github.com/CCMS-UCSD/GNPS_Workflows/files/3817971/MS_DIAL_IIN.zip)

**Comment by robinschmid** [comment]
Yes it does... We do it in MZmines IIN integration.
Maybe the feature-list is incomplete?
This could cause problems If he only exports all features with MS2 and then refers to some in the additional edge files that are not in the quant table.

In my integration, the quant table and additional edges are filtered in accordance to a user param:
- ONLY WITH MS2
- ONLY WITH MS2 OR ANNOTATION 
(annotation means IIN annotation in this case)

**Comment by robinschmid** [comment]
Maybe the additional edges file has a wrong format.
- tab separation should be changed to comma separation
- .txt should be changed to .csv

Lets see if this job completes. (same files but edges.txt -> edges.csv and tab -> comma)
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=53072e5b536340eebefb2acbfbbf92ed

**Comment by robinschmid** [comment]
Job above worked.
That means it is only a formatting issue. As the additional edges format is the same for all workflows - MS-DIAL should also stick to .csv and comma-separation. 
THis would be ideal.

**Comment by lfnothias** [comment]
YAY ! Excellent news ! Thank you !

**Comment by lfnothias** [comment]
@mwang87 
Hiroshi sent the new output files following @robinschmid recommendations.
MS-DIAL outputs now different edge files depending on the annotations-type (in source, correlation, peak shape, adduct).

I ran several jobs successfully (3/4). They include a metadata file, and the Cytoscape file looks fine. They can be used as test files. 
In-source:
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=946679b104704cd6b61fc9f8dd12d49c
Correlation:
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=8341fd3701ec43019536df9881c4792e
Peak shape:
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=0953f88cf3e94a4ebcf20319d967c46a

However, the following jobs failed:
Adduct edge file (I cannot see any weird character in the edge file, so I am not sure).
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=03f024ef69304905b75863a0624de59c
Combined peak shape / in source / correlation edge annotations (I believed multi-edge file was supported ? but it looks not supported yet).
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=ae661056ca1d4b119c0be48d83ec8150

[FBMNxIIN_MS-DIAL.zip](https://github.com/CCMS-UCSD/GNPS_Workflows/files/3935729/FBMNxIIN_MS-DIAL.zip)

Including here the test files. I am sure where you want to have them for test jobs.

**Comment by robinschmid** [comment]
The adducts_edges file defines an edge between node 0-39 (line 16 in the file). The node 0 is not defined in the quant table - it starts with node 1.

I have tried to delete this line from the file. Let's see if it works:
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=6df7f4d2ca48457aaf95b473fc223ec0

**Comment by robinschmid** [comment]
Now it also works if we add all additional edges files:
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=fb1eb310b69f492f83684dbebdf1cca6

**Comment by lfnothias** [comment]
I am closing the issue. IIN now supports MS-DIAL files. @mwang87 You can use the links few post above for test jobs.

**Comment by robinschmid** [comment]
supported since MS-DIAL 4.1
