### ISSUE TITLE
[NAP] error

### ISSUE THREAD

**Issue by justinjjvanderhooft** [CCMS-UCSD/GNPS_Workflows#221]
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=884282e778794fada0d94c6f011620cc

Results in error (  cannot open compressed file 'split_data/tabgnps.rda', probable reason 'No such file or directory')

**Comment by mwang87** [comment]
Please contact Ricardo Silva. Closing.

**Comment by MuyaoXi9271** [comment]
> https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=884282e778794fada0d94c6f011620cc
> 
> Results in error ( cannot open compressed file 'split_data/tabgnps.rda', probable reason 'No such file or directory')

Hi Justin,

I met the same issue when I run NAP by using GNPS id from FBMN workflow. May I ask how have you solved it? I preprocessed the MS2 data by using XCMS, and I am not sure whether it is the reason for the error.

Best,
Muyao
