### ISSUE TITLE
[FBMN] Adding the citation(s) in the workflow results page.

### ISSUE THREAD

**Issue by lfnothias** [CCMS-UCSD/GNPS_Workflows#223]
I think we should have the citation(s) showing up on the result page itself for all the GNPS workflows. @mwang87 If you show me how to do this, I can help.

**Comment by mwang87** [comment]
https://github.com/CCMS-UCSD/GNPS_Workflows/blob/master/feature-based-molecular-networking/tools/feature-based-molecular-networking/scripts/write_description.py

**Comment by lfnothias** [comment]
Here you go. It should pretty comprehensive. I hope my syntax is correct.
https://github.com/CCMS-UCSD/GNPS_Workflows/pull/233

@mwang87 Could you please fix the job url generation: search for it with that string 'JOBID'

**Comment by mwang87** [comment]
Can you add a test input xcms3 output so we can make sure it converts properly?

**Comment by mwang87** [comment]
Looks good, deployed and testing.
