### ISSUE TITLE
[Library Batch Validation] Seems to fail

### ISSUE THREAD

**Issue by robinschmid** [CCMS-UCSD/GNPS_Workflows#226]
Hey everyone,

I am generating some library batch submission files and they fail during validation due to multiple errors. However, they should be correct with all the default values.

- PUBMED and CAS do not support default value: N/A
- INCHI and SMILES do not support values different from N/A

[test_library_batch.zip](https://github.com/CCMS-UCSD/GNPS_Workflows/files/3763192/test_library_batch.zip)

### smalltest_failing.tsv
![image](https://user-images.githubusercontent.com/10366914/67405582-4494d100-f5b5-11e9-8696-cbc501c6f5ed.png)

The file works if you change the PUBMED and CAS to something different from the default N/A.

### library_batch_full_test.tsv
![image](https://user-images.githubusercontent.com/10366914/67407278-8e7eb680-f5b7-11e9-9136-1b9b02e892d6.png)
![image](https://user-images.githubusercontent.com/10366914/67407354-a81ffe00-f5b7-11e9-8fea-18678391c8ca.png)

The problems are the ones mentioned above:
- PUBMED and CAS
- INCHI and SMILES

Are my files actually working? The mgf and library_batch_full_test.tsv belong together.

Cheers
Robin

**Comment by robinschmid** [comment]
Updated the initial issue

**Comment by alan-jarmusch** [comment]
@mwang87 conferred with @mpanitch @kcweldon20 @emgentry @robinschmid - all errors are identical. 

SMILES and Inchi --- "is not an empty string"

**Comment by robinschmid** [comment]
I just saw your issue and realized that this might be posted in the wrong git.
