### ISSUE TITLE
[MetaMiner] Adding the workflow to GNPS

### ISSUE THREAD

**Issue by lfnothias** [CCMS-UCSD/GNPS_Workflows#228]
Congrats on the MetaMiner paper @alexeigurevich and @hoseinmohimani ! https://www.cell.com/cell-systems/pdfExtended/S2405-4712(19)30312-6
The workflow is not updated yet (https://gnps.ucsd.edu/ProteoSAFe/index.jsp?params=%7B%22workflow%22:%22RIPPQUEST%22%7D) and we don't have a documentation.

**Comment by mwang87** [comment]
Closing as this is referenced in big meta issue by @alexeigurevich
