### ISSUE TITLE
[GC] Some parameters are not suited for GC or need an update

### ISSUE THREAD

**Issue by lfnothias** [CCMS-UCSD/GNPS_Workflows#235]
Unless I am wrong, the analogue search is not used for GC, so it could be removed. Or is it using the base peak ?! Depending on that the Maximum analogue search parameter could be removed.
This is also true for the "Filter Precursor Window" parameter.

Is the "Maximum shift between precursors" used in the network ?! Should we rename it ?

@aaksenov1 @mwang87

**Comment by mwang87** [comment]
Yeah I agree, we should remove those.

**Comment by lfnothias** [comment]
Are you talking care of that ? Or can I ?

**Comment by mwang87** [comment]
These are needed by the tools, but can probably be set as a fixed value.

**Comment by mwang87** [comment]
Can you provide a full list of parameters that are likely inappropriate? @lfnothias

**Comment by lfnothias** [comment]
Not needed:
- Precursor Ion Mass Tolerance: 
- Search Analogs:  Don't SearchDo Search
- Maximum Analog Search Mass Difference:
- Maximum shift between precursors:

Need explanation:
FORCE_EXACT_MATCH:

**Comment by mwang87** [comment]
Lets move to deprecated section and deal with the software later.

**Comment by mwang87** [comment]
Deprecated these other options, will create another issue to address it in a more sustainable way.
