### ISSUE TITLE
[GC] Metadata input for LibrarySearch/Networking Workflow

### ISSUE THREAD

**Issue by mwang87** [CCMS-UCSD/GNPS_Workflows#238]
Accepts input for metadata file now. 

Needs input from @aaksenov1 with library search/networking with job with acceptable metadata file. 

- [ ] Provide new task that is actually run with the metadata, quantification table, and mgf file selected on proteomic2
- [ ] List out expected molecules (feature number, RT and molecule name and structure) that is known to vary between conditions (e.g. which conditions, what is the expected fold change)

**Comment by aaksenov1** [comment]
Dataset #1: Mix of standards in serum
Deconvolution:
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=13388c762451487692a9e3730aa49733
Lib search:
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=33928ee691d949ce96a0e7c7a023babe

Known molecules that differ (spiked standards): 

n-alkane mix >> all other groups
n-Octane
n-Dodecane
n-Tetradecane
n-Hexadecane
n-Octadecane
n-Eicosane
n-Docosane
n-Hexacosane
n-Octacosane
n-Triacontane
n-Dotriacontane
n-Hexatriacontane

FAME, FAME Serum >> all other groups
Myristic acid, methyl ester
Tetracosanoic acid, methyl ester


Dataset #2: Beer aging
Deconvolution:
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=fce3d8214823485eb7fe57c1b328c2a9
Lib search:
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=933817b180f44fc9be6afaf6e61d3629

Known molecules that differ (as determined by LECO):

0 days > 20 days
Octanoic acid, ethyl ester
Humulol 
TRANS CARYOPHYLLENE

**Comment by aaksenov1** [comment]
Dataset 2:
LECO
![image](https://user-images.githubusercontent.com/54182738/68047813-733d3680-fc9c-11e9-8a99-3ea79adc2472.png)
GNPS:
![image](https://user-images.githubusercontent.com/54182738/68047845-82bc7f80-fc9c-11e9-80c6-5a67b24d58cd.png)

LECO:
![image](https://user-images.githubusercontent.com/54182738/68047926-b39cb480-fc9c-11e9-8c77-fdfda8424f02.png)
GNPS:
![image](https://user-images.githubusercontent.com/54182738/68047943-beefe000-fc9c-11e9-8f81-b2ea4060acb6.png)

LECO:
![image](https://user-images.githubusercontent.com/54182738/68048036-ed6dbb00-fc9c-11e9-8341-f59e37843259.png)
GNPS:
![image](https://user-images.githubusercontent.com/54182738/68048057-f8c0e680-fc9c-11e9-99e0-e28d85c80e3b.png)

LECO:
![image](https://user-images.githubusercontent.com/54182738/68048091-11310100-fc9d-11e9-8702-adb8b64b7430.png)
![image](https://user-images.githubusercontent.com/54182738/68048113-1e4df000-fc9d-11e9-91fa-177e9137e8a0.png)

**Comment by aaksenov1** [comment]
Dataset 1:
Expected ratios: 1 : 1.5 : 2 : 2.5 : 3

Tetracosanoic acid, methyl ester:
![image](https://user-images.githubusercontent.com/54182738/68049869-2e67ce80-fca1-11e9-8b42-fac42edb4250.png)

Decanoic acid, methyl ester:
![image](https://user-images.githubusercontent.com/54182738/68049934-57885f00-fca1-11e9-82f7-b9ed13662f48.png)

Hexadecanoic acid, methyl ester:
![image](https://user-images.githubusercontent.com/54182738/68050012-8b638480-fca1-11e9-90b0-fb43e688425e.png)
