### ISSUE TITLE
[FBMN] Test with XCMS3 IIN Columns

### ISSUE THREAD

**Issue by mwang87** [CCMS-UCSD/GNPS_Workflows#244]
Please provide workflow on proteomics2.

**Comment by lfnothias** [comment]
I am actually fixing the script now. Testing everything and doing the PR in a bit.

**Comment by mwang87** [comment]
OK Thanks, once its done, please post the test job here so we can add it to the tests.

**Comment by lfnothias** [comment]
I did the input file conversion locally and ran it with the MZmine option. The python issue is resolved but now there is an issue with edges creation. 
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=e63ed0091313410083b1d686e849e6e8

**Comment by mwang87** [comment]
Can you make sure the pairs are the format specified here:

https://ccms-ucsd.github.io/GNPSDocumentation/featurebasedmolecularnetworking/#advanced-extras

**Comment by lfnothias** [comment]
Arf excel used ; instead of , ...
Now it works fine with the file converted locally ! https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=bd955e3728504a4282c46240b85357cd
Here is the PR:  https://github.com/CCMS-UCSD/GNPS_Workflows/pull/245

**Comment by lfnothias** [comment]
This is the test job after the xcms_formatter PR https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=6db8d52ed12044ee84e747494b430513

**Comment by mwang87** [comment]
Testing on newest release:

https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=6761086545ca497b85862899ad30102f
