### ISSUE TITLE
[FBMN] Bug in XCMS Parser

### ISSUE THREAD

**Issue by mwang87** [CCMS-UCSD/GNPS_Workflows#251]
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=17c0df18d39641ecb8d679937b21697a

**Comment by lfnothias** [comment]
Here are the input files for XCMS-FBMN (no CAMERA used)
[XCMS_FBMN.zip](https://github.com/CCMS-UCSD/GNPS_Workflows/files/3780965/XCMS_FBMN.zip)

**Comment by mwang87** [comment]
Test already existed but didn't seem to catch it. Figuring it out and deployed latest code and testing:

https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=a63187e041ba4954b7eec3d831ef5b96
