### ISSUE TITLE
[FBMN] Additional edges, try to calculate mass delta is precursor mz is available

### ISSUE THREAD

**Issue by mwang87** [CCMS-UCSD/GNPS_Workflows#266]

**Comment by robinschmid** [comment]
For a second I forgot that the delta m/z is calculated on the basis of PEPMASS in the mgf file.  Can you check and replace all N/A (all missing m/z for features without MS/MS) with the m/z which is provided in the quant table?

**Comment by mwang87** [comment]
Tests being added here:

https://github.com/CCMS-UCSD/GNPS_Workflows/pull/297

**Comment by cmaceves** [comment]
@ntbeileh

**Comment by mwang87** [comment]
How is this task going?

**Comment by cmaceves** [comment]
Honestly having trouble learning how best to manage/help my undergrad, so
pretty slowly. If it's urgent I can do it myself and she can have a new
GitHub issue!

- Chrissy

**Comment by cmaceves** [comment]
> How is this task going?

In progress!

**Comment by mwang87** [comment]
Merged and passing tests. Closing
