### ISSUE TITLE
[GC] libraries

### ISSUE THREAD

**Issue by robinschmid** [CCMS-UCSD/GNPS_Workflows#269]
I do not know if there is an issue for this:

For the GC workflow (Library Search/Networking), the standard GNPS library is auto selected and creates some issues when trying to start the job:
https://ccms-ucsd.github.io/GNPSDocumentation/gc-ms-library-molecular-network/

![image](https://user-images.githubusercontent.com/10366914/68240230-cac90280-000c-11ea-990c-6546e9c53f36.png)

**Comment by mwang87** [comment]
Waiting on finishing this first:

https://github.com/CCMS-UCSD/GNPS_Workflows/issues/89

Will then update defaults.

**Comment by mwang87** [comment]
Addressed. Defaults updated in release_15.
