### ISSUE TITLE
[GC] Harmonize Kovats index file and balance score file

### ISSUE THREAD

**Issue by robinschmid** [CCMS-UCSD/GNPS_Workflows#271]
Harmonize input format and documentation.
@mwang87 @lfnothias @aaksenov1

#### Kovats index file
Documentation says comma-separated (as also indicated by the csv format, therefore in my view preferred).
Currently, the format needs semi-colon separation. 

**Is it possible to change the parser on GNPS side?**

#### Balance score file
So far I do not know the content, format or reason for this file.
Is generated automatically by MS hub in workflow?
Why is there an optional input in the user parameter section?

related to #270 and #232

**Comment by lfnothias** [comment]
You are right. There is an inconsistency.
The format is actually tab separated.  "The metadata and carbon marker files must be formatted as a tab-separated .txt file. To create your metadata table properly, see the documentation here."
https://ccms-ucsd.github.io/GNPSDocumentation/gc-ms-library-molecular-network/

**Comment by robinschmid** [comment]
tab-separated txt is also good. 
Then we will need to change the table as well.
Is the workflow accepting tab separated?
![Screenshot_20191107-211630](https://user-images.githubusercontent.com/10366914/68425890-4494f380-01a7-11ea-8cec-28e9b97986a8.png)

**Comment by mwang87** [comment]
We will not address issue of balance score. Perhaps we should add into the quantification file with an additional header and lose the requirement for a separate file. I think thats the proper way to do it, I'll make a separate issue.

**Comment by robinschmid** [comment]
The problem is - I do not understand what the balance score is, how it is formatted, and how to start a job without it.
Can someone explain?

**Comment by mwang87** [comment]
We will remove the dependency on balance score and it will be removed in the future. The formatting is pretty non-standard so we won't attempt to describe it.

**Comment by MelissaESPOSITO** [comment]
I removed the balance score from the documentation and indicated .csv format for the Kovats table.

**Comment by aaksenov1** [comment]
Made few edits.

**Comment by mwang87** [comment]
Closing, see https://github.com/CCMS-UCSD/GNPS_Workflows/issues/290
