### ISSUE TITLE
[Molnetenhancer] Needs update pushed

### ISSUE THREAD

**Issue by jgauglitz** [CCMS-UCSD/GNPS_Workflows#273]
This job failed: http://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=89249a50d55e4c5094606c194f0f1667

A 'N/A' string sneaked into the SMILES file and caused the error.

Madeleine fixed this in version 0.1.1. of MolNetEnhancer:
MolNetEnhancer version 0.1.1. needs to be updated on GNPS, then the issue should be fixed in the GNPS workflow also.

**Comment by mwang87** [comment]
Can you confirm this also doesn't work on the development server?

**Comment by amcaraballor** [comment]
The MolNetEnhancer Release_14 does not work. I tested re-running previous jobs that were succesfully accomplished, but cloning them to the recent version [release 14] all failed. I can provide  links to the ones that worked and failed.
Cloned and failed: https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=cb491f2d010643ddb363b7662239a5b7
Original [run with MolNetEnhancer v1.2.5]: https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=420115527f604b3d8733cb248a52d132
I tested with other datasets with the same results, MolNetEnhancer release 14 does not provide CF output to any feature. Thoughts?

**Comment by mwang87** [comment]
The dereplicator results are empty.

**Comment by amcaraballor** [comment]
Hey @mwang87, even the jobs only with NAP should (in theory) run fine with the MoNetEnhancer and get the CF output. The previous version worked. Check this out using only Dereplicator and VarQuest results with a small dataset also fails running MolNetEnhancer release 14: https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=6a69517976944abba449dea51faf8923

**Comment by mwang87** [comment]
But the dereplicator results are not empty in this new example. The old job you provided, the dereplicator results are empty

**Comment by amcaraballor** [comment]
Hey @mwang87, the examples I provided above contained NAP and Dereplicator [I also tested with only NAP, only Dereplicator and/or VarQuest, even with MS2LDA and also failed with MolNetEnhancer release 14]. These contain Dereplicator, are not empty:
Cloned and failed: https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=cb491f2d010643ddb363b7662239a5b7
Original [run with MolNetEnhancer v1.2.5 and worked fine]: https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=420115527f604b3d8733cb248a52d132 
Check this out using only Dereplicator and VarQuest results with a small dataset also fails running MolNetEnhancer release 14: https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=6a69517976944abba449dea51faf8923

**Comment by justinjjvanderhooft** [comment]
Hi @amcaraballor, release 15 running at proteomics2 should finish okay. Looks like the servers are down on your end now so I can't test, but that's the most up-to-date version. That also displays the ClassyFire scores properly.

**Comment by mwang87** [comment]
@amcaraballor 

In the [failure case](https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=cb491f2d010643ddb363b7662239a5b7) you list, the dereplicator results are empty and so the software fails. Please don't include tasks where the result set is 0. We don't handle that case.

**Comment by amcaraballor** [comment]
Two examples of failed MolNetEnhancer release 14: 
[Only FBMN, none in silico]: https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=c06b7922e1c944b7afcc7d2befbd56cd 
[FBMN and NAP only]: https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=36e3fdb016814ce8be96446b1f7ac9b5
Original [MolNetEnhancer version 1.2.5 worked fine]: https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=420115527f604b3d8733cb248a52d132

**Comment by mwang87** [comment]
I think this job is too old for us to process. We need it to be at least release_8. I would recommend running again.

**Comment by mwang87** [comment]
Rerunning on Proteomics2 with fix:

https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=3efc8b1dda3b46d098b190731d46c9ab
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=f38d1cd5eff84bc8b36f9262c3d5b30a
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=a58c0dedc3cd418a999dca466c83110f

**Comment by mwang87** [comment]
Closing as should be addressed by release_15
