### ISSUE TITLE
[Qiime2/FBMN] Integrate PERMANOVA with the selected categories into Workflow

### ISSUE THREAD

**Issue by mwang87** [CCMS-UCSD/GNPS_Workflows#274]
- [x] Test GNPS Job with metadata @cmaceves - this is to include a test GNPS job that has the appropriate metadata included for us to test with
- [x] Integrate into workflow @mwang87 
- [x] Create Output Visualization @mwang87 
- [x] Testing @kcweldon20

**Comment by mwang87** [comment]
Waiting on test job from @cmaceves. 

Moving off milestone.

**Comment by cmaceves** [comment]
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=4a646c2a61ef4087bd281c9a55452e04
test job link
@mwang87

**Comment by mwang87** [comment]
For @kcweldon20 

One test case: https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=bca041271e0548f1a96a21f64d5b69e4

Please run more and let us know if its doing what we expect.
