### ISSUE TITLE
[GNPS] Spectral library Release - MSMS-Chooser

### ISSUE THREAD

**Issue by mwang87** [CCMS-UCSD/GNPS_Workflows#275]
## Title
GNPS-MSMLS - Sigma's Mass Spectrometry Metabolite Library

## Description: 
"Chemical standards run and analyzed using the MSMS-Chooser workflow found on GNPS."

## Long Description:
"This dataset contains samples from Sigma's Mass Spectrometry Metabolite Library. MSMLS is a collection of high quality small biochemical molecules that span a broad range of primary metabolism. These standards consisted of lipid-like molecules and water-soluble sugar compounds. The chemical standards were run on a Q-Exactive in positive and negative mode.

## Tasks

GNPS00001 https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=dc82cdb517ba4d339c1918290f3371c2

GNPS00002 https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=aeaf2355f1674120b17cc3ab3b7fc888

GNPS00003 https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=fb4a0a736099409aa7f1699865e3022f

GNPS00004 https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=b7485bd3c12b4e6caa0ce95fe506bd2f

GNPS00005 https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=48fb7e36593b44199c11e5b7f5962ec7

GNPS00006 https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=9b9739b04bf84e7bb7b17420377b2450

GNPS00007 https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=d7fb508e95694ec6b978af26f3c6b3dc

**Comment by mwang87** [comment]
Library released, @mpanitch calculating library statistics.

**Comment by mpanitch** [comment]
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=98030c764b734d00a74edb98727432d5

Library search for MSMLS (MSMS chooser library) created by Kelly and Alan
