### ISSUE TITLE
[GC] Deprecate Fields In Workflow

### ISSUE THREAD

**Issue by mwang87** [CCMS-UCSD/GNPS_Workflows#276]
@lfnothias correctly listed the ones we need to gracefully deprecate here https://github.com/CCMS-UCSD/GNPS_Workflows/issues/235

**Comment by aaksenov1** [comment]
Updated workflow with depreciated fields is functional, latest example job:
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=766219ebc84f4d42a5606d26f8050fb8

**Comment by mwang87** [comment]
Closing, we'll properly deprecate some fields later.
