### ISSUE TITLE
[FBMN] Standardizing and outputting CCS columns in MS-DIAL and MetaboScape

### ISSUE THREAD

**Issue by lfnothias** [CCMS-UCSD/GNPS_Workflows#283]
Outputting them in the converted table for MS-DIAL and MetaboScape
Column headers used for Progenesis QI:
- Molecular Formula
- Neutral mass
- CCS
- dCCS 
See #282 
assigned to @lfnothias

**Comment by lfnothias** [comment]
The test are good except for that error. But I haven't changed the code, so I am not sure.
`
Traceback (most recent call last):
  File "/Github/GNPS_Workflows/feature-based-molecular-networking/test/test_converters.py", line 30, in test_progenesis
    "./progenesis_MSE_output.csv")
  File "../tools/feature-based-molecular-networking/scripts/progenesis_formatter.py", line 32, in convert_to_feature_csv
    compound_name = record["Compound"]
KeyError: 'Compound'
`

**Comment by lfnothias** [comment]
Adding the test job for it here:
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=4f847b47792548a79faa1585669951fe
and the files:
[Progenesisdata_IMS.zip](https://github.com/CCMS-UCSD/GNPS_Workflows/files/3860649/Progenesisdata_IMS.zip)

If we could output the metadata column in the converted table, it would nice for users to import in Cytoscape. Otherwise, it is difficult to map it back.

I was renaming the CCS columns into some standardized headers that we could also have in MS-DIAL and MetaboScape. https://github.com/lfnothias/GNPS_Workflows/blob/83b55e692461d59ad4080abcf365750fface0572/feature-based-molecular-networking/tools/feature-based-molecular-networking/scripts/progenesis_formatter.py#L62

**Comment by lfnothias** [comment]
This is the correct link https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=124147c84f3a43b78bd347c2d62a9028

**Comment by lfnothias** [comment]
It worked @mwang87 https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=7d29705d282544c8924c18a38661035d 👍 
Now adding the metadata columns in the converted table. See the renaming for standardization, and dropping of the column 'Accepted Description' :
https://github.com/lfnothias/GNPS_Workflows/blob/83b55e692461d59ad4080abcf365750fface0572/feature-based-molecular-networking/tools/feature-based-molecular-networking/scripts/progenesis_formatter.py#L62

**Comment by mwang87** [comment]
Added into master.
