### ISSUE TITLE
[GC] The graphml output annotation for nodes needs to be the top cosine score

### ISSUE THREAD

**Issue by aaksenov1** [CCMS-UCSD/GNPS_Workflows#288]
test case #1:
The node 320 should be Decanoic acid, not 12-Bromolauric acid:
https://proteomics2.ucsd.edu/ProteoSAFe/result.jsp?task=766219ebc84f4d42a5606d26f8050fb8&view=view_all_annotations_DB&show=true#%7B%22main.%23Scan%23_lowerinput%22%3A%22320%22%2C%22main.%23Scan%23_upperinput%22%3A%22320%22%7D
![image](https://user-images.githubusercontent.com/54182738/68790708-a23c9c00-05fc-11ea-8a4f-a81db415dd53.png)

test case #2:
The node 444 should be 9-Octadecenoic acid (Z)-, not Eicosanoic acid:
https://proteomics2.ucsd.edu/ProteoSAFe/result.jsp?task=2b993563cb1140629f9e7f40fb8344a6&view=view_all_annotations_DB&show=true#%7B%22main.%23Scan%23_lowerinput%22%3A%22444%22%2C%22main.%23Scan%23_upperinput%22%3A%22444%22%7D
![image](https://user-images.githubusercontent.com/54182738/68807911-91e8e900-061d-11ea-8b57-301e8532f0d5.png)

**Comment by mwang87** [comment]
Why is the top cosine score correct in these cases? Do you have justification that is the right selection criteria? If so, then what is the point of selecting a top k results?

**Comment by aaksenov1** [comment]
It is not, but that is not the point. What is the selection criterion for the name given to the node? In the given example the 12-Bromolauric acid is not top match by any measure - cosine, balance score, name, so I am wondering why it was selected as the annotation in graphml. In most of the other nodes the top cosine is the name, but there are few scattered cases where it is not, e.g. another one in another job, the top cosine match is 9-Octadecenoic acid (Z)- but the node is labelled by the third match Eicosanoic acid:
https://proteomics2.ucsd.edu/ProteoSAFe/result.jsp?task=2b993563cb1140629f9e7f40fb8344a6&view=view_all_annotations_DB&show=true#%7B%22main.%23Scan%23_lowerinput%22%3A%22444%22%2C%22main.%23Scan%23_upperinput%22%3A%22444%22%7D
![image](https://user-images.githubusercontent.com/54182738/68807911-91e8e900-061d-11ea-8b57-301e8532f0d5.png)

**Comment by mwang87** [comment]
Should be fixed, @aaksenov1 please confirm in this test:

https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=6b1d808dd7d740309248aefb5aa284c1

**Comment by mwang87** [comment]
@aaksenov1 please rerun this job:

https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=6b1d808dd7d740309248aefb5aa284c1

You will need to reformat your carbon marker file.

**Comment by aaksenov1** [comment]
Still node names occur that are not top cosine match
The job:
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=182bd264944f4b818c02a6b10fc9ed6c

Examples:
Scan 205
Top cosine match: Benzeneethanol
Network name: 2-PHENYLETHANOL
![image](https://user-images.githubusercontent.com/54182738/70365395-09d5b800-1846-11ea-9624-7ae579ff594d.png)

Scan 562
Top cosine match: ISOPENTYL DECANOATE
Network name: BUTYRIC ACID ISOPENTYL ESTER
![image](https://user-images.githubusercontent.com/54182738/70365536-b6179e80-1846-11ea-8b1a-316867f9f530.png)

**Comment by mwang87** [comment]
Resolved issue with @aaksenov1. Seems correct with the logic. Logic is that a single compound can only be identified once. Once its been identified once (highest scoring cosine across whole dataset), it is not possible to be used as identification again.
