### ISSUE TITLE
[GC] MSHub masses are shifted by 0.2 in updated workflows

### ISSUE THREAD

**Issue by aaksenov1** [CCMS-UCSD/GNPS_Workflows#289]
The example job:
Deconvolution:
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=c89e1a63e8844fc38da68c7d76e0ee94
Library search:
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=766219ebc84f4d42a5606d26f8050fb8

**Comment by mwang87** [comment]
Testing updated PR https://github.com/CCMS-UCSD/GNPS_Workflows/pull/294 code here:

https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=ca6f89dd58294a26a2c4ea1506fc3b58

@aaksenov1 Please confirm when finished.
