### ISSUE TITLE
[GC] Setting the format for the Kovats hydrocarbon markers file - Ming to define the format

### ISSUE THREAD

**Issue by aaksenov1** [CCMS-UCSD/GNPS_Workflows#290]
Robin's module outputs as follows:

Compound_Name,RT_Query
Heptane (C7),199.62
Octane (C8),253.92
Nonane (C9),315.54
Decane (C10),380.46

**Comment by mwang87** [comment]
The new format will be a csv file, with comma separators. No other separators will be allowed. The following columns with the following semantics

## Columns

1. Compound_Name - name of the compound (string)
1. Carbon_Number - number of carbons (integer)
1. RT - retention time in seconds (float)

Adding support in PR and will list below when ready to test. Please reformat carbon marker files accordingly.

**Comment by mwang87** [comment]
Updated GNPS documentation to reflect the change in format.

**Comment by mwang87** [comment]
Revising code in this PR: https://github.com/CCMS-UCSD/GNPS_Workflows/pull/293

**Comment by mwang87** [comment]
Requires a test file. Please reformat your files and test. @aaksenov1

**Comment by aaksenov1** [comment]
Gives an error:
https://proteomics2.ucsd.edu/ProteoSAFe/result.jsp?task=2ebf0b496f7b4676b893fe0ce1e776ec&view=view_kovats

**Comment by robinschmid** [comment]
I have started a new test:
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=6b853231bdf14bb3bc0c880e69a89945

Files:
[20191120_kovats_format_test.zip](https://github.com/CCMS-UCSD/GNPS_Workflows/files/3871108/20191120_kovats_format_test.zip)

**Comment by robinschmid** [comment]
It works with the new Kovats file format and the MZmine export.
This can be closed.

**Comment by robinschmid** [comment]
However, I think it did not use the Kovats index as a filter. There are multiple hits to Eicosan with different RT. How can I check this?
@aaksenov1

**Comment by aaksenov1** [comment]
Robin -
was that the right link that you sent? I am seeing the error:
[image: image.png]

**Comment by robinschmid** [comment]
I have changed the link in an edit - maybe you have tried the old link?
This one works for me:
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=632f1d04a51143af8be6e83ba65a60e5

Only the **View Kovats calculations results** menu is failing

> There was an error retrieving the result data for block "main" of workflow type "MOLECULAR-LIBRARYSEARCH-GC".

**Comment by aaksenov1** [comment]
So this means it did not see the file in the correct format. I am getting
the same error. Either Ming needs to give us an example file that works or
this is a bug on his side.

**Comment by robinschmid** [comment]
The format is:
![image](https://user-images.githubusercontent.com/10366914/69287260-9d12ba80-0bc3-11ea-8218-4a2931b3aa89.png)
Comparable to the documentation:
![image](https://user-images.githubusercontent.com/10366914/69287338-dd723880-0bc3-11ea-88ca-b7f6794e926d.png)

Does it really fail to read the file or does it fail to construct the Kovats model?

**Comment by aaksenov1** [comment]
The job that uses old format file and generates Kovats RIs successfully:
https://gnps.ucsd.edu/ProteoSAFe/result.jsp?task=6c1a4ba480134298a5364d61469e1058&view=view_kovats

The job that uses the new redefined format input file gives the "There was an error retrieving the result data for block "main" of workflow type "MOLECULAR-LIBRARYSEARCH-GC"." error:
https://proteomics2.ucsd.edu/ProteoSAFe/result.jsp?task=2ebf0b496f7b4676b893fe0ce1e776ec&view=view_kovats

**Comment by mwang87** [comment]
[Balance Score Showing](https://proteomics3.ucsd.edu/ProteoSAFe/result.jsp?task=55f2dda8a26d4142b926ee9cdf119b6c&view=view_all_annotations_DB&show=true)

[Kovats Calculation Showing](https://proteomics2.ucsd.edu/ProteoSAFe/result.jsp?task=db100d45b5104982bc636c43471465a1&view=view_all_annotations_DB)

Please verify @aaksenov1

**Comment by aaksenov1** [comment]
All good.
