### ISSUE TITLE
mzmine Export for GNPS doesn't work anymore (I'm not submitting, just exporting)

### ISSUE THREAD

**Issue by Althalis** [CCMS-UCSD/GNPS_Workflows#305]
Hi there, 
I used the module in the past but it doesn't work anymore.
I updated mzmine, and it still doesn't work.

![billede](https://user-images.githubusercontent.com/5079495/69151606-36b26d00-0adb-11ea-9575-82e64e9f0dbb.png)

When I try to export .csv and .mgf individually, the IDs of the features don't match.
I'm stuck. 
Thanks for your help
Best
Julie

**Comment by robinschmid** [comment]
Hey Julie,

as this is an MZmine issue, you should repost this on the MZmine issue page. 
https://github.com/mzmine/mzmine2/issues

Please do this and provide:
- your MZmine version
- your export parameters
- the console log with the corresponding exception message 

Cheers
Robin

**Comment by Althalis** [comment]
Thanks Robin, I just did. :)
