### ISSUE TITLE
[GC] Specify minimum number of samples 

### ISSUE THREAD

**Issue by mwang87** [CCMS-UCSD/GNPS_Workflows#306]
Should be something like 10. Else, recommend running MZMine2.

**Comment by mwang87** [comment]
@aaksenov1 Please indicate what is minimum number of samples and where we shoudl display this?

**Comment by aaksenov1** [comment]
5 minimum for MSHub to work, 10 minimum recommended. It needs to be explicitly stated in the tutorial (will do).

**Comment by mwang87** [comment]
Updated workflow description for release 17. Closing.
