### ISSUE TITLE
msms-chooser

### ISSUE THREAD

**Issue by Adafede** [CCMS-UCSD/GNPS_Workflows#308]
Hi guys,

Great work and preprint on the msms-chooser.

Some steps could still be clarified and I think it would be nice if mwang would completely open the project used as example so that we can reproduce it completely, and better understand the input files.
((https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=8454490b1ecc49ab85e1cece2f2f944c#))

Many thanks in advance!

**Comment by mwang87** [comment]
Thanks for the question. 

We actually included all the data in the public dataset for each of these portions of the library. The first portion for what you listed is here:

https://massive.ucsd.edu/ProteoSAFe/dataset.jsp?task=a27631fcc7fc447591dec756fc056ef2
