### ISSUE TITLE
Error Showing Spectrum

### ISSUE THREAD

**Issue by MelissaESPOSITO** [CCMS-UCSD/GNPS_Workflows#311]
Error Showing Spectrum by clicking on "view spectrum" when following the link (https://gnps.ucsd.edu//ProteoSAFe/result.jsp?task=ccb8c3204c654af9bf2a99025a4e23f1&view=cluster_details&protein=947&show=true)

**Comment by mwang87** [comment]
This seems to be an issue with multiple groups. In the front end task directory, it puts group G2 into spectwo instead of where G1 appears spec. Will have to ask @jjcarver on how to address this.

**Comment by mwang87** [comment]
We will use the absolute path to the original file to plot and also show consensus.

**Comment by mwang87** [comment]
Addressing here: https://github.com/CCMS-UCSD/GNPS_Workflows/pull/324

**Comment by mwang87** [comment]
Fixed, merging in. 

https://proteomics2.ucsd.edu/ProteoSAFe/result.jsp?view=cluster_details&protein=2&show=true&task=c5ed93eeec0c486a96d3a10a8a985d3a#%7B%7D
