### ISSUE TITLE
[GC] GC-library search is not reading the metadata abundances of the quant table

### ISSUE THREAD

**Issue by mabelgon88** [CCMS-UCSD/GNPS_Workflows#317]
as I send you in the email the GNPS-GC workflow it is reading the metadata but it is not taking the abundances values of the quant table so in the network all the metadata values appeared as 0.

**Comment by mwang87** [comment]
This should be addressed in proteomics2. Can @mabelgon88 confirm? 

Also, can you provide task as evidence it doesnt work?

**Comment by mabelgon88** [comment]
This is one link of one the jobs:https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=bc8099588930489f922ef1aed1b5739e

Here you can see that the metadata has been readed as a group but, the values of intensities are not been taken for each metadata

**Comment by mwang87** [comment]
Seems like it works now, please confirm @mabelgon88 

https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=55f2dda8a26d4142b926ee9cdf119b6c

**Comment by mabelgon88** [comment]
Thanks a lot Ming! It seems that it´s working now!
