### ISSUE TITLE
[GC] Remove some of the columns in the default results view

### ISSUE THREAD

**Issue by aaksenov1** [CCMS-UCSD/GNPS_Workflows#318]
Remove: 
MZErrorPPM
MassDiff
IonMode

**Comment by mwang87** [comment]
What is the default results view?

**Comment by mwang87** [comment]
Addressed here:

https://github.com/CCMS-UCSD/GNPS_Workflows/pull/293

Testing here:

https://proteomics2.ucsd.edu/ProteoSAFe/result.jsp?task=db100d45b5104982bc636c43471465a1&view=view_all_annotations_DB

@aaksenov1 verify

**Comment by aaksenov1** [comment]
Good
