### ISSUE TITLE
[GC] Revise Display

### ISSUE THREAD

**Issue by mwang87** [CCMS-UCSD/GNPS_Workflows#326]
1. TopK Matches
1. Top 1 Match
1. Show kovats columns

**Comment by mwang87** [comment]
Addressing here: 

https://github.com/CCMS-UCSD/GNPS_Workflows/pull/293

**Comment by mwang87** [comment]
Checking results here:

https://proteomics3.ucsd.edu/ProteoSAFe/status.jsp?task=55f2dda8a26d4142b926ee9cdf119b6c

@aaksenov1

**Comment by aaksenov1** [comment]
All good!
