### ISSUE TITLE
[GC] Videos for the GC-MS GNPS manuscript

### ISSUE THREAD

**Issue by aaksenov1** [CCMS-UCSD/GNPS_Workflows#329]
1) Tutorial for the deconvolution and library search (presenter - Katherine Maloney)
2) EI network use case: dart frogs (presenter - Mabel Gonzalez)
3) EI network use case: OGC breathomics (presenter - Ilaria Belluomo)
4) EI network use case: cheese volatilome (presenter - Brooke Anderson)
5) EI network use case: B subtilis volatilome (presenter - Andrea Albrracin)
6) EI network use case: petroleomics (presenter - Roman Borisov)

**Comment by aaksenov1** [comment]
Video 6) 
https://youtu.be/UC0BFRm-7B4​

**Comment by robinschmid** [comment]
link is broken

**Comment by aaksenov1** [comment]
Updated link:
https://youtu.be/fj3vC6ixfZw

**Comment by aaksenov1** [comment]
Video 1)
https://youtu.be/_18_7y75NZ4​

**Comment by aaksenov1** [comment]
Video 1)
https://youtu.be/yrru-5nrsdk

**Comment by aaksenov1** [comment]
Video 4)
https://youtu.be/_PehOiBqzzY

**Comment by mwang87** [comment]
We need the original video content and project files so we can edit to a consistent theme. Please provide that.

**Comment by aaksenov1** [comment]
Will assemble the source videos.

**Comment by aaksenov1** [comment]
Current links:
Supplemental video V1:
Tutorial for the use of GNPS for analysis of GC-MS data.
https://www.youtube.com/watch?v=yrru-5nrsdk&feature=youtu.be

Supplemental video V2:
GNPS for GC-MS in breathomics: using molecular networking to combine different datasets.
https://www.youtube.com/watch?v=iX03r_mGi2Q&feature=youtu.be

Supplemental video V3:
GNPS for GC-MS in petroleomics: using molecular networks to find incorrect annotations.
https://www.youtube.com/watch?v=mv-fw2zSgss&feature=youtu.be

Supplemental video V4:
GNPS for GC-MS in biology: using molecular networks for compound discovery in dart frogs.
https://www.youtube.com/watch?v=nUhCZ9LwoM4&feature=youtu.be

Supplemental video V6:
GNPS for GC-MS in microbiology: using networks to explore chemistry of cheese.
https://www.youtube.com/watch?v=_PehOiBqzzY&feature=youtu.be

Supplemental video V6:
GNPS for GC-MS in biochemistry: use of networking to discover antifungals produced by B. Subtilis.
https://www.youtube.com/watch?v=MblruOSglgI&feature=youtu.be

Need to be update in the manuscript when videos are edited and put on Dorrestein youtube channel.

**Comment by mwang87** [comment]
@aaksenov1 What is the status of these video sources?

**Comment by aaksenov1** [comment]
Have all of the original compiled videos that were uploaded, is that sufficient?

**Comment by mwang87** [comment]
It’s good for now. Please send to me.

**Comment by aaksenov1** [comment]
Put on temp drive at:
Y:\videos for Ming

**Comment by mwang87** [comment]
Got it, will edit to make consistent with other videos and upload to Youtube on lab account.

**Comment by aaksenov1** [comment]
Updated links needed to update in the revised manuscript
