### ISSUE TITLE
[GC] Include public GC-MS libraries to GNPS

### ISSUE THREAD

**Issue by aaksenov1** [CCMS-UCSD/GNPS_Workflows#330]
Public library (user-assembled)
Fiehn VocBinBase

**Comment by aaksenov1** [comment]
The library is uploaded, needs to go live:
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=ee54161c9e794cd093d200e5fefd4bfc
Name: GNPS GC-MS public library 
Description: The library contains the 70 eV EI reference spectra collected and contributed by individual laboratories as well as downloaded from open sources.

**Comment by aaksenov1** [comment]
Updated description:
GC-MS EI reference data of 19,808 spectra for 19,708 standards obtained from open sources and provided by individual laboratories. The library has been assembled by Dr. Roman Borisov at the A.V.Topchiev Institute of Petrochemical Synthesis. The sources include: Atlas mass spectrov organicheskih sodineniy pod red.A.V.Koptyuga, SDBSWeb : https://sdbs.db.aist.go.jp (National Institute of Advanced Industrial Science and Technology, 2019), EI mass spectra collection of RUDN University (mass spectra registration supported by US government (NIST)

**Comment by mwang87** [comment]
Name: GC-BORISOV-COMPILATION

Will move to CCMS_SpectralLibraries

**Comment by mwang87** [comment]
Completed.
