### ISSUE TITLE
[Enhancement] Adjustable Intensity scale for USI Links

### ISSUE THREAD

**Issue by RaphaelR87** [CCMS-UCSD/GNPS_Workflows#339]
I love the USI links for high-quality mirror plots.
It would be great if users could adjust the intensity scale to optimize this parameter
for their spectra additional to m/z range

**Comment by mwang87** [comment]
What do you mean adjust intensity scale? Currenlty it scales out of base peak, so you want to scale down relative to basepeak?

**Comment by RaphaelR87** [comment]
Hi Ming,

I was referring to the relative intensities of the fragments. It would be great if users could adjust them (zoom in). 
To give an example what I mean:
Specifically data from the MaXis q-ToF seem to have problems with M+Na adducts sometimes.
The precursor ion intensity is still orders of magnitude highers compared to the fragment ions, even though we ramped up collision energies. This was the case for many different samples of mine from different compound classes.
The spectra are still useful if you can zoom in on the fragment ions.

**Comment by mwang87** [comment]
Currently you can zoom in on mass axis (x axis). Is the desired feature a zoom on the intensity (Y axis)?

**Comment by mwang87** [comment]
Maximum intensity is currently supported. Closing.
