### ISSUE TITLE
Download latest GNPS library

### ISSUE THREAD

**Issue by robinschmid** [CCMS-UCSD/GNPS_Workflows#345]
Hey all,

is there a way to download the complete spectral library? 
This download is outdated (the same file as the one I downloaded last year):
https://gnps.ucsd.edu/ProteoSAFe/gnpslibrary.jsp?library=all

cheers
Robin

**Comment by mwang87** [comment]
We are going to deprecate all, I recommend downloading them individually.

**Comment by mwang87** [comment]
https://gnps-external.ucsd.edu/gnpslibrary
