### ISSUE TITLE
super-quick start FBMN

### ISSUE THREAD

**Issue by jgauglitz** [CCMS-UCSD/GNPS_Workflows#347]
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=035a73864a5a4b39bc056d5f6abba0e9

When I try the super quick start by dragging in my FBMN files, either in one group or one file in each group, I get a very odd emperor plot. 
![image](https://user-images.githubusercontent.com/45803026/70933911-a4c25500-1ff1-11ea-92f2-d57c8632376a.png)

**Comment by mwang87** [comment]
The linked job is not FBMN. It is classical networking. Closing issue.
