### ISSUE TITLE
[FBMN] EdgeAnnotation of negative DeltaMZ 

### ISSUE THREAD

**Issue by Adafede** [CCMS-UCSD/GNPS_Workflows#349]
Hi,

Small suggestion I dream to do since a long time...
Once everything ran, your "edge annotation" is amazing and is to me one of the most helpful elements to explore a network in Cytoscape. As an improvement, would it be possible to also annotate the corresponding "negative" DeltaMZ? I am currently doing it manually and I think it would be helpful to add this option. Maybe displaying an absolute delta instead of the directed one could be a solution.

Maybe an example showing what I mean will explain it better:

<img width="1201" alt="Capture d’écran 2019-12-29 à 02 47 07" src="https://user-images.githubusercontent.com/44283913/71551333-a4f52400-29e5-11ea-96eb-454828decb31.png">

Many thanks in advance!

**Comment by mwang87** [comment]
Thanks! Thats a good point, this seems like a bug that we should handle the negative cases as well. We will address this issue in the next release!

**Comment by mwang87** [comment]
@Adafede, I just fixed the issue here:

https://github.com/CCMS-UCSD/GNPS_Workflows/pull/350

I'm interested in a test case. If you have one so we can make sure it works on your data, please post the task id here. Thanks so much for pointing out the issue!

**Comment by Adafede** [comment]
Wow, that was quick! :)

Thank you for your reactivity! 
Has the job to be public? If not, here is the ID of linked job: 3abd99a7ed4d4658871fdc7dbd0ecf46

Thank you again!

**Comment by mwang87** [comment]
This is perfect. Am deploying this latest release to beta server and will run test there. Will follow up with finished job and will let you be the judge if its doing the right thing. Thanks so much!

**Comment by mwang87** [comment]
Full test running here:

https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=69cc9231b0e84db199b89ab7ef385641

Testing version is: negative_edge_annotation:release_17

**Comment by Adafede** [comment]
Perfect, looks exactly as expected!

Thanks again, already excited to see coming releases

**Comment by mwang87** [comment]
Awesome! If you want to play around more, you can clone this beta version. However, it might get updates in an unexpected schedule. I think we'll push release 17 very soon in the new year, likely Jan 6th.

**Comment by Adafede** [comment]
Thank you very much, already played with some of the merging / ion fusion betas (I think it's the 16 between the actual 15 and the 17 you opened :P ) but not sure if properly understood everything! 
Thank you anyway for sharing all this beautiful work!
