### ISSUE TITLE
Qemistree updates

### ISSUE THREAD

**Issue by anupriyatripathi** [CCMS-UCSD/GNPS_Workflows#365]
The following features need to be pushed into the new GNPS release:
1. Adding the option to select the instrument the data was run on for FP prediction accuracy
2. Adding the option to use `euclidean` or `jaccard` distances to cluster fingerprints
3. Running Classyfire on smiles from ms/ms matches or csi fingerID predictions
4. Figuring out how to render the tree in a user-friendly manner

**Comment by mwang87** [comment]
Can you provide the exact commandlines we would be using to run this?

**Comment by anupriyatripathi** [comment]
I've sent you an email with the commands for this.

**Comment by anupriyatripathi** [comment]
Test tasks:

Description | FBMN | Qemistree |
------------|--------|-----------|
QE QERT C18|[Job](https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=efda476c72724b29a91693a108fa5a9d) | [Job](https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=170e525412b04f13bbbead326136c8f8)

**Comment by anupriyatripathi** [comment]
The current workflow renders a file that appears to be an output of one of the first steps in the qemistree workflow i.e. one of the tables from SIRIUS. It needs to be updated to the feature data QZA file produced from the last step of the processing i.e. the output of `get-classyfire-taxonomy`.
It's a QZA file that can be exported to a tsv as follows:

`qiime tools export --input-path classyfire_results.qza --output-path classyfire-results`

`classyfire-results` is a folder that would contain a tsv file called `feature_data.tsv`. We should to render `feature_data.tsv`

**Comment by mwang87** [comment]
I agree they may not be correct, but please check the output files. Are they correct for all the tests you have run? Lets take this one step at a time.

**Comment by anupriyatripathi** [comment]
@mwang87 The output files look correct; just highlighting the TBDs here. 
Upon further investigation, it looks a file called `formula.qza` is being rendered currently. I don't think this is an output from qemistree.

**Comment by mwang87** [comment]
Sounds good. I'll pull out that file. What are the contents of that feature_data.tsv file? Which columns are meaningful to display?

**Comment by anupriyatripathi** [comment]
The classified feature data has the following columns. I don't think there's an issue with displaying everything. `table_number` is not relevant though as we would not be supporting meta-analyses for the time being. 

id | #featureID | csi_smiles | ms2_smiles | ms2_compound | ms2_adduct | table_number | smiles | annotation_type | kingdom | superclass | class | subclass | direct_parent
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by mwang87** [comment]
Closing as the latest changes seem to be good. Will go out in release 18
