### ISSUE TITLE
Classyfire API can not parse smiles with charges

### ISSUE THREAD

**Issue by anupriyatripathi** [CCMS-UCSD/GNPS_Workflows#366]
For example: CCCCCCCCCCCCCCCC(=O)OCC(COP(=O)([O-])OCC[N+](C)(C)C)O 

This structure is classified when querying the Classyfire API, but isn't parsed by the GNPS-Classyfire API

**Comment by mwang87** [comment]
Can you provide a url link for how you called it? I don't think we accept structures into GNPS-Classyfire, only InChI Keys

**Comment by anupriyatripathi** [comment]
The GNPS API documentation says that we could query using smiles as follows: 
https://gnps-structure.ucsd.edu/classyfire?smiles=<smiles string> 

Here's my query through GNPS: https://gnps-structure.ucsd.edu/classyfire?smiles=CCCCCCCCCCCCCCCC(=O)OCC(COP(=O)([O-])OCC[N+](C)(C)C)O

And here are the Classyfire results: http://classyfire.wishartlab.com/entities/ASWBNKHCZGQVJV-UHFFFAOYSA-N.

On a related note, I do not think any of the GNPS APIs (conversion to Inchi, conversion to formula) handle SMILES with charges.

**Comment by mwang87** [comment]
So if you provide the inchi key in the same way as you did for classyfire:

https://gnps-classyfire.ucsd.edu/entities/ASWBNKHCZGQVJV-UHFFFAOYSA-N.json

It works. The question is encoding charges in the structure. Symbols like that need to be url encoded and cannot be plainly included in the urls like that.

**Comment by anupriyatripathi** [comment]
How does one go from smiles to inchi keys for such charges structures?

**Comment by anupriyatripathi** [comment]
I used python 3's urlib.parse to url encode charged SMILES as follows: 
<img width="567" alt="Screen Shot 2020-01-14 at 9 43 59 AM" src="https://user-images.githubusercontent.com/16598461/72368396-db53c400-36b2-11ea-8008-80aafed70885.png">

The API still does not parse it. 
`https://gnps-structure.ucsd.edu/classyfire?smiles=CCCCCCCCCCCCCCCC%28%3DO%29OCC%28COP%28%3DO%29%28%5BO-%5D%29OCCN%2B%28C%29C%29O`

**Comment by anupriyatripathi** [comment]
Rdkit does not parse url encoded SMILES:
<img width="567" alt="Screen Shot 2020-01-14 at 9 43 59 AM" src="https://user-images.githubusercontent.com/16598461/72369188-6b463d80-36b4-11ea-9d26-11a3a415c87b.png">

**Comment by mwang87** [comment]
Wait, just a second, you shouldn't pass url encoded smiles to rdkit. The url encoded smiles is so you can call the web api appropriately. I would recommend using normal smiles string.

**Comment by anupriyatripathi** [comment]
Got it. I verified that rdkit does not process the original SMILE string either
