### ISSUE TITLE
Edge between nodes not sharing minimum fragments set in parameters

### ISSUE THREAD

**Issue by Adafede** [CCMS-UCSD/GNPS_Workflows#375]
Hi,

I'm quite surprised to see that after careful inspection of some clusters generated by the v17 of FBMN, some of them contain nodes which do not share the minimal fragments set in the parameters.(!)
As I have no idea where it could come from, I tried merging / not merging after mzmine export (experimental setup) but it has nothing to do with it. 

Any idea?

Many thanks in advance!

P.S.: As some data are "sensitive" I would like to avoid posting the whole job but as an example, here are two related ions with minimum 6 fragments and 0.02Da tolerance :

[bug.mgf.zip](https://github.com/CCMS-UCSD/GNPS_Workflows/files/4086368/bug.mgf.zip)

**Comment by robinschmid** [comment]
Hey,
You know that GNPS does not simply match the signals. They perform spectral alignment and matching to calculate the cosine similarity. If the precursor m/z of the two spectra are different - this difference is allowed for the fragment signals.
Maybe this helps?

cheers
Robin

**Comment by Adafede** [comment]
Thank you very much for your reply. Yes, indeed I know GNPS does not "simply" match them. It would be indeed helpful to have the parent masses in my example, I'll try generating a subjob with what looks problematic to me...with precursor _m/z_ .

I thought the allowed difference was a single "shift", and not the difference itself for each fragment, so I was wrong?

As example:

parent ion 1: 100 _m/z_
10.00 1E1
20.00 1E1
30.00 1E1
40.00 1E1
50.00 1E1
60.00 1E1
70.00 1E1
80.00 1E1
90.00 1E1

parent ion 2: 105 _m/z_ (+5)
15.00 1E1 (+5)
25.00 1E1 (+5)
35.00 1E1 (+5)
45.00 1E1 (+5)
55.00 1E1 (+5)
65.00 1E1 (+5)
75.00 1E1 (+5)
85.00 1E1 (+5)
95.00 1E1 (+5)

This is the allowed difference I had in mind, but according to what I understood from your post, that one would also be ok?

parent ion 3: 105 _m/z_  (+5)
08.00 1E1  (-2, inside ±5 tol)
12.00 1E1 (+2, inside ±5 tol)
33.00 1E1 (+3, inside ±5 tol)
36.00 1E1 (-4, inside ±5 tol)
52.00 1E1 (+2, inside ±5 tol)
58.00 1E1 (-2, inside ±5 tol)
73.00 1E1 (+3, inside ±5 tol)
79.00 1E1 (-1, inside ±5 tol)
94.00 1E1 (+4, inside ±5 tol)

**Comment by robinschmid** [comment]
I think it can be either 5 or 0 - nothing in between.
@lfnothias @mwang87 
Can you comment on this?

**Comment by Adafede** [comment]
That's also what I thought, but then I really have an issue with fragments not matching minimum required number...

I am preparing the clean example and running it on GNPS ASAP to give you something to really work with.

**Comment by Adafede** [comment]
Okay...I know saw my mistake. I thought it could be " 5 **either** _(and not or)_ 0 - nothing in between. "

I have 1 fragment matching with no diff, 5 with difference between precursor ions...this giving the minimal 6. 

Thank you very much for clarifying it for me!

P.S.: Here attached the example!
[GNPS_example.xlsx](https://github.com/CCMS-UCSD/GNPS_Workflows/files/4097706/GNPS_example.xlsx)

**Comment by robinschmid** [comment]
You are welcome :)
So this issue can be closed then?

**Comment by Adafede** [comment]
Yes of course! Thanks again

Maybe a nasty question before: admitting two precursor ions with less than 0.02 Da diff, are the matched peaks between them then doubled? (Once without diff, once with the very small diff?)

You rock guys!

**Comment by robinschmid** [comment]
Each signal can only be matches with one corresponding signal in the library spectrum. Moreover, there are some filters (see user parameters in FBMN / MN) to filter signals within a certain m/z window.
