### ISSUE TITLE
MoNA Structures not showing on "View All Library Hits"

### ISSUE THREAD

**Issue by kcweldon** [CCMS-UCSD/GNPS_Workflows#381]
None of the annotations to a MoNA library spectrum show a structure in my table of library hits (or my View All Spectra with IDs tab either). When I view the actual library spectrum, the structure is there.

Job for reference:
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=c25d9f662d97497b9e27b8e50885deba

**Comment by mwang87** [comment]
This is an issue regarding MONA Only having INCHI and not smiles when we imported. To correct this, we are going to refactor and switch to new structure viewer.

**Comment by mwang87** [comment]
Testing here:

https://proteomics3.ucsd.edu/ProteoSAFe/status.jsp?task=0935f097f6e045e0a787bff9c53

**Comment by mwang87** [comment]
Workflow is fixed, need refactor of the chemical drawing service. @mwang87 will address there.
