### ISSUE TITLE
[FBMN] Analogs exported incorrectly

### ISSUE THREAD

**Issue by irinakoester** [CCMS-UCSD/GNPS_Workflows#389]
When downloading Cytoscape data from a current FBMN GNPS network, analogs are not exported correctly.
I have 1631 LibIds and 8314 analogs. But when opening the Cytoscape file Compound_Name equals Analog:Compound_Name (#1631).
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=695f78e0ab4a4786b57c85781895debe

**Comment by irinakoester** [comment]
I wanted to download the analogs so I can add it separately to the cytoscape file, but the DB file of the download "....view_all_analog_annotations_DB" has the LibIDs only and no Analogs as well.

**Comment by irinakoester** [comment]
Also, does that mean that MolNetEnhancer (only GNPS) would only use LibID and no Analogs?

**Comment by mwang87** [comment]
Fixed, will be in release 19.
