### ISSUE TITLE
[FBMN] run workflow with only subset of quant table?

### ISSUE THREAD

**Issue by irinakoester** [CCMS-UCSD/GNPS_Workflows#394]
It would be useful to run the network (and have emperor plot etc) after blank removal.
So mgf file would be the original one, but the quant table has less features and selected maybe samples.
GNPS would filter the mgf file according to what's in the quant table.

**Comment by mwang87** [comment]
This is a future feature, we'll have a flag that says, filter out MS2 without quant that can be accomplished when mzmine file will be converted.
