### ISSUE TITLE
Bug for files selection in molecular networking when they have been moved on MassIVE

### ISSUE THREAD

**Issue by lfnothias** [CCMS-UCSD/GNPS_Workflows#41]
The issue happends for a molecular network job derived from a MAAST job using the function "Analyze with Molecular Networking". When launching the job, some input files selected are causing "Could not find file for f.MSV000079015...]

MAAST: https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=6179f662018f479dbdccf07c876e6076

As a result, the job cannot be launched.

**Comment by mwang87** [comment]
tentatively addressed by ad023b553f0ebd3637a37e77243338539a644ff7
