### ISSUE TITLE
Direct Cytoscape Preview/Download module is not working

### ISSUE THREAD

**Issue by KyobinKang** [CCMS-UCSD/GNPS_Workflows#410]
Leaving a comment here is better than reporting on the Google forum, right?

As titled, the direct preview is not working now. It doesn't work for results from any version of workflows, so I guess it's not a problem of workflow; maybe the internal server for the preview is down?

Of course I can visualize my network by the old way, but I reaaaally want it back; it's one of the best features for removing small nuisances ;)

**Comment by mwang87** [comment]
Downtime due to UCSD networking. Systems back online
