### ISSUE TITLE
Error in FBMN workflow - job fails

### ISSUE THREAD

**Issue by jgauglitz** [CCMS-UCSD/GNPS_Workflows#42]
unknown error message in FBMN workflow; possibly due to IIN part of feature finding in mzMINE?

https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=a17860355635486e96116f7555e2f008

FAILED[Clone][Restart][Delete]Traceback (most recent call last):   File "/data/ccms-gnps/tools/feature-based-molecular-networking/scripts/convert_networks_to_graphml.py", line 31, in <module>     main()   File "/data/ccms-gnps/tools/feature-based-molecular-networking/scripts/convert_networks_to_graphml.py", line 26, in main     nx.write_graphml(G, sys.argv[5], infer_numeric_types=True)   File "</data/ccms-gnps/tools/anaconda3/lib/python3.5/site-packages/decorator.py:decorator-gen-620>", line 2, in write_graphml_lxml   File "/data/ccms-gnps/tools/anaconda3/lib/python3.5/site-packages/networkx/utils/decorators.py", line 240, in _open_file     result = func_to_be_decorated(*new_args, **kwargs)   File "/data/ccms-gnps/tools/anaconda3/lib/python3.5/site-packages/networkx/readwrite/graphml.py", line 150, in write_graphml_lxml     writer.dump()   File "/data/ccms-gnps/tools/anaconda3/lib/python3.5/site-packages/networkx/readwrite/graphml.py", line 702, in dump     self._xml_base.__exit__(None, None, None)   File "src/lxml/serializer.pxi", line 716, in lxml.etree.xmlfile.__exit__ (src/lxml/lxml.etree.c:137075)   File "src/lxml/serializer.pxi", line 993, in lxml.etree._IncrementalFileWriter._close (src/lxml/lxml.etree.c:141610)   File "src/lxml/serializer.pxi", line 999, in lxml.etree._IncrementalFileWriter._handle_error (src/lxml/lxml.etree.c:141711)   File "src/lxml/serializer.pxi", line 195, in lxml.etree._raiseSerialisationError (src/lxml/lxml.etree.c:131087) lxml.etree.SerialisationError: unknown error -1481614473 Tool execution terminates abnormally with exit code [1]
--

**Comment by lfnothias** [comment]
Possibly related to #70
