### ISSUE TITLE
Can't add new annotations

### ISSUE THREAD

**Issue by tderond** [CCMS-UCSD/GNPS_Workflows#429]
Hi all,

I'm trying to deposit some new annotated MS/MS spectra for a paper on some new compounds I'm writing.

Both the GNPS front page and the "Cluster Spectra->AnnotatetoGNPS" links send me to the ADD-SINGLE-ANNOTATED-BRONZE workflow.

I filled out all the text boxes except for Pubmed ID and CAS number, and when I try to submit it gives the following error:

[Task parameter validation failed due to 1 error: 'Description' is required]

but I don't see an entry "Description" on the page

**Comment by mwang87** [comment]
It is the very top called Title:

![image](https://user-images.githubusercontent.com/96528/75100950-05d64e00-558a-11ea-9d72-e71774243037.png)

**Comment by tderond** [comment]
So it is. Thanks!
