### ISSUE TITLE
[Qemistree] update output names to match documentation

### ISSUE THREAD

**Issue by jgauglitz** [CCMS-UCSD/GNPS_Workflows#430]

**Comment by mwang87** [comment]
Can you provide links in documentation and output where they do not match. @anupriyatripathi and @mwang87 can take a look once we have that information.

**Comment by jgauglitz** [comment]
@anupriyatripathi has the info; created issue together.

**Comment by mwang87** [comment]
Please post it here so we can track it down. Helps a lot! Thanks!

**Comment by mwang87** [comment]
Closing due to lack of information.
