### ISSUE TITLE
[Qemistree] Multiple failed Qemistree jobs

### ISSUE THREAD

**Issue by eelijah254** [CCMS-UCSD/GNPS_Workflows#432]
Below is a link to the Qemistree job: https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=dd19f58671864bfea10c42a5c30aafb7

Best,
Emmanuel

**Comment by mwang87** [comment]
Testing here:

https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=1fdd5f621f314a7e9a28191d5bc1ba47

Catching failure on my code, but Qemistree seems to not produce any meaningful output.

**Comment by anupriyatripathi** [comment]
@eelijah254 and I figured out offline that the SIRIUS export is ill-formatted. OK to close this issue until further developments on the export front.
