### ISSUE TITLE
[MERGE_NETWORKS_POLARITY] Settings / how to troubleshoot failing workflow

### ISSUE THREAD

**Issue by amcaraballor** [CCMS-UCSD/GNPS_Workflows#435]
Hey @mwang87, Here are two failed jobs from two versions of the MERGE_NETWORKS_POLARITY workflow with the same POS and NEG files resulting in different errors:
Release 18: https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=b5492f23506f4d0c8db8f6b6d2fc998b
Release 19: https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=5cfd199ca36640eba0f3508db7af40fd
Issues? bugs to fix? Let me know ;)

**Comment by mwang87** [comment]
Thanks @amcaraballor will look into it for release 20!

**Comment by mwang87** [comment]
These networks are not from the same set of data and don't make sense to merge polarities.
