### ISSUE TITLE
[Qemistree] update docs

### ISSUE THREAD

**Issue by anupriyatripathi** [CCMS-UCSD/GNPS_Workflows#439]
- tooltip - can be updated [here](https://github.com/CCMS-UCSD/GNPS_Workflows/blob/qemistree-tree/qemistree/qemistree/input.xml#L119)
- documentation page

**Comment by mwang87** [comment]
With updated qemistree on the cluster, this is the test case:

https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=84198fc46a794b10aeda5dd565dc2dde
