### ISSUE TITLE
[Qemistree] 'fingerprint_network.py' errors out

### ISSUE THREAD

**Issue by anupriyatripathi** [CCMS-UCSD/GNPS_Workflows#467]
Identify the cause of this error:

Traceback (most recent call last): File "/data/ccms-gnps/tools/qemistree/release_18/fingerprint_network.py",
 line 77, in <module> main() File "/data/ccms-gnps/tools/qemistree/release_18/fingerprint_network.py", line 28, in main df = pd.read_csv(input_filename, sep="\t") File "/data/ccms-gnps/tools/miniconda3_gamma/lib/python3.7/site-packages/pandas/io/parsers.py",
 line 678, in parser_f return _read(filepath_or_buffer, kwds) File "/data/ccms-gnps/tools/miniconda3_gamma/lib/python3.7/site-packages/pandas/io/parsers.py", line 440, in _read parser = TextFileReader(filepath_or_buffer, **kwds) File "/data/ccms-gnps/tools/miniconda3_gamma/lib/python3.7/site-packages/pandas/io/parsers.py",
 line 787, in __init__ self._make_engine(self.engine) File "/data/ccms-gnps/tools/miniconda3_gamma/lib/python3.7/site-packages/pandas/io/parsers.py", line 1014, in _make_engine self._engine = CParserWrapper(self.f, **self.options) File "/data/ccms-gnps/tools/miniconda3_gamma/lib/python3.7/site-packages/pandas/io/parsers.py",
 line 1708, in __init__ self._reader = parsers.TextReader(src, **kwds) File "pandas/_libs/parsers.pyx", line 542, in pandas._libs.parsers.TextReader.__cinit__ pandas.errors.EmptyDataError: No columns to parse from file Tool execution terminates abnormally with
 exit code [1]

**Comment by mwang87** [comment]
Can you link the job?

**Comment by anupriyatripathi** [comment]
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=8b288b3c3c5846bf838460ac48cb1013
