### ISSUE TITLE
GC-MS GNPS

### ISSUE THREAD

**Issue by MelissaESPOSITO** [CCMS-UCSD/GNPS_Workflows#468]
In the job window, after the library search, on "View All Spectra With Annotations", there is an "Error Showing Spectrum" and also the link does not work: "500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."
here is the link to my job: https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=d188527c677a4b2c88490e56a92e57b0
thanks

**Comment by mwang87** [comment]
Addressed fix here:

https://proteomics2.ucsd.edu/ProteoSAFe/result.jsp?task=a3e6a129c6664c838b51c99f4b69f8a5&view=view_all_clusters_withID

Will go out in release 20.
