### ISSUE TITLE
Develop agreed format with MS-DIAL with Hiroshi

### ISSUE THREAD

**Issue by mwang87** [CCMS-UCSD/GNPS_Workflows#47]

**Comment by lfnothias** [comment]
I tested the version MS-DIAL 3.96 shared by Hiroshi and the feature quantification table exported is like it used to be (only three rows at the top for sample metadata). So we dont have the change the table conversion script.
This a new job with 3.96 input files
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=1eeff06ce1724f5290a71e8086bb5a5e
