### ISSUE TITLE
[GC] Molecular network workflow does not accept MS-DIAL native output files

### ISSUE THREAD

**Issue by lfnothias** [CCMS-UCSD/GNPS_Workflows#481]
The issue is addressed with #480 by providing formatter/converter for the .TXT table and .MGF outputted by MS-DIAL.
@mwang87 @aaksenov1 @Melissaesposito

**Comment by mwang87** [comment]
Here is a test task with MSDial Inputs, this should work eventually once we enable reformatting:

https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=2b92351fc0d24812ba3b7bdffa38bcaf

**Comment by MelissaESPOSITO** [comment]
thanks, 
Do you know when, approximately, it will be reformatting?
