### ISSUE TITLE
GNPS normalized output to QIIME2 Diversity Analysis

### ISSUE THREAD

**Issue by kcweldon20** [CCMS-UCSD/GNPS_Workflows#49]
Interested in using the GNPS .qza output to run the qiime2 diversity plugin. I want to run the analysis on a rowsum normalized table but would need to make the final table in ppm in order for QIIME2 to accept it. 
Would there be an plugin or automated way to create this ppm table? Would it maybe be beneficial to also have any other normalization options?

**Comment by mwang87** [comment]
Working, deployed to Proteomics2, will push out in next release.
