### ISSUE TITLE
[QEMISTREE] "View Qemistree ITOL Tree" DOES NOT WORK but Dashboard works fine 

### ISSUE THREAD

**Issue by amcaraballor** [CCMS-UCSD/GNPS_Workflows#507]
"View Qemistree ITOL Tree" gives error but the rest of visualization links work fine and downloaded files work fine in iTOL [ View qiime2 Emperor Plots | View Qemistree Dashboard | Download Qiime2 Data]. So, the only link that is not working at all is [View Qemistree ITOL Tree]
Here is the link to the job: https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=8a1edb01a4974211b3dc3f91edc4047a 
Let me know what the issue is, if any. I am currently rerunning the same job in case the issue is due to any issue in the old version. Thanks @mwang87 @anupriyatripathi  ;)

**Comment by mwang87** [comment]
@anupriyatripathi Should be able to look at this.

**Comment by anupriyatripathi** [comment]
@amcaraballor is it possible that your metadata does not have the column `sample_name`. The Qemistree workflow has advanced options to choose the metadata column for visualization and if you don't change it, it uses `sample_ name` by default.

**Comment by amcaraballor** [comment]
@anupriyatripathi, yes, the metadata contains the sample_name column. 
I'm rerunning that one but using ATTRIBUTE_seedtreatment instead of the sample_name in the Sample Metadata Column advance option to see if the same issue occurs.  ;)

**Comment by amcaraballor** [comment]
@anupriyatripathi, the issue is solved running the metadata column of the dataset instead of the sample_name. Thanks ;)
