### ISSUE TITLE
Toggle G6 as a blank removal group in Classic Networking

### ISSUE THREAD

**Issue by mwang87** [CCMS-UCSD/GNPS_Workflows#51]

**Comment by mwang87** [comment]
Working on it here: https://github.com/CCMS-UCSD/GNPS_Workflows/tree/g6_network_filtering

**Comment by mwang87** [comment]
Seems a bit more diffiult than initially anticipated. We will need to know which clusters were in files in G6, but the clusterinfosummary that actually has this information is troublesome because it requires the networks to be run, thus cyclical dependency.

**Comment by lfnothias** [comment]
This is such a great addition ! 👍 
Could you please describe briefly how the filtering is done ?

**Comment by mwang87** [comment]
All consensus spectra that are found to have at least 1 spectrum from G6 is marked as being blank. Then these spectra are not allowed to be considered for molecular networking. They might appear as singletons but not actually paired up with anything.
