### ISSUE TITLE
[QEMISTREE] Error: Network error, recieved 500 from server

### ISSUE THREAD

**Issue by aaksenov1** [CCMS-UCSD/GNPS_Workflows#522]
Example of job:
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=d38166e28be541088c765c2744d055ca

**Comment by kcweldon** [comment]
I have also received this error:
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=35c391c1c3fc401d89836daacc59d441

**Comment by helenamrusso** [comment]
I also had this error. Job:

https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=b4f7bb7249044964b95f6560575c0f22

**Comment by anupriyatripathi** [comment]
> I have also received this error:
> https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=35c391c1c3fc401d89836daacc59d441

@kcweldon can you please check your metadata and ensure it has `sample_name` column? Qemistree seems to have run fine based on results under [View Summary]

**Comment by kcweldon** [comment]
So it definitely could be something with the metadata, but I ran this directly off of the feature based molecular networking job (Visualize with Qemistree) so it was auto-populated with the metadata, quant and lib annotations from that FBMN job. I checked and the samples present on the quant file are all on the metadata.....

**Comment by anupriyatripathi** [comment]
@kcweldon could you link the FBMN job here as well?

**Comment by anupriyatripathi** [comment]
@helenamrusso your Sirius export is malformed. It has repeated entries for the same feature ID. Could you please try exporting a new MGF using the LC_MZmine2 workflow. Example here:  https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=d605e633b2f142d0b2b6a05643bdcbc9.  Or you can refer to this example batch file that correctly exports the outputs: ftp://massive.ucsd.edu/MSV000085226/other/

**Comment by anupriyatripathi** [comment]
@aaksenov1 your MGF file just has MS2 information. There seems to be an issue with MZmine2 export. Here's an example batch file that should import things correctly, could you please check if your export steps are in line with this?

**Comment by kcweldon** [comment]
Hi Priya, thanks for all the help! Here is the link to the FBMN
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=46146ec01f82451b85c3481b29aae8b8

It will not show the emperor plots so it may be the metadata/data...

**Comment by anupriyatripathi** [comment]
Thanks, @kcweldon. You have a few repeated sample names in your metadata that seems to be causing an error with both FBMN and Qemistree. 
<img width="457" alt="Screen Shot 2020-05-12 at 3 55 20 PM" src="https://user-images.githubusercontent.com/16598461/81753769-62e6ef00-9469-11ea-963b-c90526634caf.png">

**Comment by anupriyatripathi** [comment]
@mwang OK to close
