### ISSUE TITLE
[FBMN] Progenesis QI bug

### ISSUE THREAD

**Issue by lfnothias** [CCMS-UCSD/GNPS_Workflows#536]
There is a bug for the FBMN with Progenesis QI as reported by Michelle Moffit https://groups.google.com/forum/#!category-topic/molecular_networking_bug_reports/unresolved-bugs--unknown-error-message/HcUsb8Hepsk

It is addressed in this PR
https://github.com/CCMS-UCSD/GNPS_Workflows/pull/535

**Comment by mwang87** [comment]
Should be fixed in Release 22. Merged and now testing.
