### ISSUE TITLE
Mirror Plot USI don't work

### ISSUE THREAD

**Issue by irinakoester** [CCMS-UCSD/GNPS_Workflows#538]
Hey,
I tried to look up ~15 mirror plot USI and only half of the links worked.

The ones not working give me following error:
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Here here is an example:
https://metabolomics-usi.ucsd.edu/mirror/?usi1=mzspec:GNPSTASK-96722ff3fec843969ca8b673b5e7fdaf:spectra/specs_ms.mgf:scan:7249&usi2=mzspec:GNPSLIBRARY:CCMSLIB00003460424#%7B%7D

**Comment by mwang87** [comment]
The library spectrum is a private spectrum that unable to be shared publicly. Closing as resource is working as it should. We will open issue to let users know that private spectra cannot be visualized.
