### ISSUE TITLE
SIRIUS (version release_19@sirius-4.4.4)  report error

### ISSUE THREAD

**Issue by LiZhihua1982** [CCMS-UCSD/GNPS_Workflows#555]
I found that SIRIUS (version release_19@sirius-4.4.4)  analysis using MZmine2, MS-DIAL even the result analyzed by LC_MZMINE2 in GNPS as input all will lead errors such as below:
![image](https://user-images.githubusercontent.com/38903973/84361540-c7cb6b80-ac06-11ea-905f-b1c9df3d3ca6.png)

**Comment by mwang87** [comment]
Thanks! This tool is super in beta but thanks for the interest. This'll give us the impetus to make it better.
