### ISSUE TITLE
GC-MS Data analysis workflow not working for High-res data (Orbitrap) 

### ISSUE THREAD

**Issue by montmasis** [CCMS-UCSD/GNPS_Workflows#556]
Hello Ming,

I had troubles since few days running the GC FBMN, from MS-DIAL pre-processed data.
I had been in contact with Alexander, who privately sent me some demo data so that I could troubleshoot. 

The only difference between mine and his demo files is that my spectra /z values are in high-res (i.e. floating numbers) while the demo in low-res (integers). Alexander said the workflow had been previously tested with high-res data, but still the error seems to indicate that this may be the issue. He agrees.

Let me know if I can be of any help (I will be out of office 15th-21st of June)

This the last failed job:
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=a9f0fe2e2bd8491a837fb7003c06a868
 
This the error:
**ValueError: could not convert string to float: '43.67894:9813**
 
This how my deconvoluted mgf spctra looks like:

BEGIN IONS
TITLE=Unknown
SCANS=71
RTINMINUTES=6.323204
RETENTIONINDEX=1116.423
MODELION=98.98421
MODELIONHEIGHT=1.16095E+08
MODELIONAREA=1.16095E+08
INTEGRATEDHEIGHT=1.16095E+08
INTEGRATEDAREA=1.16095E+08
43.01828          737250
45.03391          2829768
46.9685             856694
62.96325          579107
64.97888          2338554
69.06997          436342
77.03869          274727
79.0544             619661
80.97376          32752970
81.98165          27346378
82.98939          20615216
.........

Best

Stefano

**Comment by mwang87** [comment]
Was this quantification stitched together? Line 83 seems to be edited manually and automatically exported.

**Comment by montmasis** [comment]
Yes the quant table it is exported with MSDIAL and then I manually
converted to the mzMine format (changed columns) . The mgf spectra is the
original one from  MSDIAL

**Comment by mwang87** [comment]
Cool, the manual conversion seems to be incorrect. There are colons which shouldn't be there. I think maybe take a more careful look at the conversion you performed. Additionally, you can wait on new features to handle MSDial input.

**Comment by montmasis** [comment]
Thank you Ming. I will recheck the quant table then and retry. Strange.
Looking forward to the convention script! :)

**Comment by montmasis** [comment]
Wait, ..sorry you meant the mistake is in the mgf spectra... ? You meant
"colons" like these ":"
or "columns", like extra columns in the CSV quant table?  :)

**Comment by montmasis** [comment]
I see what you mean now. Somehow in the quant table there are some extra
entries (0) in some rows after line 83. I will fix that and try again.
Thanks!
