### ISSUE TITLE
MolNetEnhancer - MS2LDA - error 

### ISSUE THREAD

**Issue by MarynkaMassSpecGirl** [CCMS-UCSD/GNPS_Workflows#564]
Dear All, 
Thank you for your fantastic workshop yesterday. I started my adventure with your tools today. I performed SUCESSFULLY analysis in GNPS for two dataset. I successfully accomplished also MS2LDA analysis (so happy for this). Now I am trying to run MolNetEnhancer, however I find always an error, which I report below. Could you help me with this? I would love to perform entire analysis to use Cytoscape as Maddleine shod yesterday. 
I read other discussions ihere in the forum related to this topic, however I could not find the solution! 

Thank you so much for your help
Marynka

this is the error

GNPS request success: True
Traceback (most recent call last):
  File "/data/ccms-gnps/tools/molnetenhancer/release_22/molnetenhancer.py", line 75, in <module>
    main()
  File "/data/ccms-gnps/tools/molnetenhancer/release_22/molnetenhancer.py", line 35, in main
    ms2lda_gnps_job_id=args.gnps_ms2lda_job, nap_job_id=args.nap)
  File "/data/ccms-gnps/tools/molnetenhancer/release_22/molnetenhancer.py", line 49, in process
    SMILES_csv, out_dict = add_Chemical_Info(gnpslibfile, output_directory, nap_ID=nap_job_id, Derep_job_ID=dereplicator_job_id, Varquest_job_ID=varquest_job_id)
  File "/data/ccms-gnps/tools/molnetenhancer/release_22/chemClass2Network.py", line 84, in add_Chemical_Info
    gnpslib = pd.read_csv(gnpslibfile, sep='\t', error_bad_lines = False)
  File "/data/ccms-gnps/tools/miniconda3_gamma/envs/molnetenhancer/lib/python3.7/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/data/ccms-gnps/tools/miniconda3_gamma/envs/molnetenhancer/lib/python3.7/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/data/ccms-gnps/tools/miniconda3_gamma/envs/molnetenhancer/lib/python3.7/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/data/ccms-gnps/tools/miniconda3_gamma/envs/molnetenhancer/lib/python3.7/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/data/ccms-gnps/tools/miniconda3_gamma/envs/molnetenhancer/lib/python3.7/site-packages/pandas/io/parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 532, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
Tool execution terminates abnormally with exit code [1]

**Comment by justinjjvanderhooft** [comment]
It looks like MolNetEnhancer could not find any GNPS library hits from your GNPS Molecular Networking job. Could you share the link here and the GNPS team can look into what happened. You could also check yourself whether the job found any library hits.

**Comment by MarynkaMassSpecGirl** [comment]
Hi Justin, Thank you for this prompt answer. 
Please see link to job que with error: https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=c0b9756aec4c43ae96b004a9dc9d7273

These this GNPS: https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=0606c0cb3c7c44f6ae0f181a2bdacd67
from this I did perform MS2LDA, but not MolNetEnhancer. (zzip also attached)

If there are some points in the original GNPS data analysis that you believe are not ok, or could be better - please let me know. I would like to use GNPS and MS2LDA on the best way. I m not sure if I used libraries correctly..... 

I will be very appreciated for help!

MArynka
[ProteoSAFe-MS2LDA_MOTIFDB-8b570158-download_ms2lda_dict_Intra_POS.zip](https://github.com/CCMS-UCSD/GNPS_Workflows/files/4831150/ProteoSAFe-MS2LDA_MOTIFDB-8b570158-download_ms2lda_dict_Intra_POS.zip)

**Comment by justinjjvanderhooft** [comment]
The GNPS job does not show any library hits - (there is an error there) - I am not sure what happened but that looks like a bug. Could you file that as a separate bug? Once that is solved - I think MolNetEnhancer will run fine.

**Comment by MarynkaMassSpecGirl** [comment]
Ok, I will. 
I tried also a second dataset, in negative ionziation mode. I performed correctly GNPS, MS2LDA and also MolEnhancer..... mistery.... files attached.

Original work:
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=bc0035cd95b548e6923f831da9c3910d


[ProteoSAFe-MOLNETENHANCER-278f0874-download_data_MolEnhancer_IntraNEG.zip](https://github.com/CCMS-UCSD/GNPS_Workflows/files/4831351/ProteoSAFe-MOLNETENHANCER-278f0874-download_data_MolEnhancer_IntraNEG.zip)
[ProteoSAFe-MS2LDA_MOTIFDB-8a23435a-download_ms2lda_dict_Intra_NEG_2.zip](https://github.com/CCMS-UCSD/GNPS_Workflows/files/4831353/ProteoSAFe-MS2LDA_MOTIFDB-8a23435a-download_ms2lda_dict_Intra_NEG_2.zip)

**Comment by justinjjvanderhooft** [comment]
So this one worked, right? I see that the library hits do show ok for the MN job. If you share the MolNetEnhancer job id or link, it is easier to check. Did you manage to run NAP (Network Annotation Propagation) to add to MolNetEnhancer?

**Comment by MarynkaMassSpecGirl** [comment]
Here you have following: 
1) MolEnhancer for negative dataset: 
ID=278f0874663c464191f597e659b02a47

2) MS2LDA for negative dataset:
ID=8a23435ab9d841fea95663579bc43c79

3) GNPS run for negative dataset:
ID=bc0035cd95b548e6923f831da9c3910d

For your question: **Did you manage to run NAP (Network Annotation Propagation) to add to MolNetEnhancer?**
No, I did not. I dont know yet how to do it! I am trying each available option, little by little. Indeed tutorials are required, and video. Can you share some link with demo/video/or registration from workshop to follow step by step? Also the paert of Medlaine yesterday was so cool, but it was too fast - cannot reproduce her workflow in cytoscape..... :(


Thank you so much for your help!
MArynka

**Comment by justinjjvanderhooft** [comment]
To find out about NAP - this link is a good starting point: https://ccms-ucsd.github.io/GNPSDocumentation/nap/ - not sure if there was a tutorial about NAP yet.
The jobs finished okay - I think with NAP results included the MolNetEnhancer job will actually become "meaningful". I am off for some days now so someone else hopefully takes over. Don't forget to list a separate error on the GNPS Mol Netw. job as this error is not related to MolNetEnhancer....
