### ISSUE TITLE
MolNetEnhancer - error due to missing files

### ISSUE THREAD

**Issue by justinjjvanderhooft** [CCMS-UCSD/GNPS_Workflows#58]
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=fc9f0115439a4748a823c28c1267eafc

The above jobs fails due to a missing (VarQuest) file - but in a notebook with the provided task ids it runs fine. I wonder why....

Another job with a DEREPLICATOR task ID did run okay: https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=69ca43cd5f87463d8ea605399f73afca

**Comment by mwang87** [comment]
Other testing cases:

https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=aaff02c11f514d8db203b31b6b5058c1
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=fe0eab89ab55416c82cdf3e6bba96014
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=1626073f6f224862bc852139a5c61be7
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=1b96965e4629442dbedd39ec5e25bd4f
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=eac9a6df8cda40d588fd51451f44bc02
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=b6862e7f6f9f49169a4f496edc586f26

**Comment by laserc** [comment]
should be resolved with pull request #105
