### ISSUE TITLE
Updating the Quickstart page description 

### ISSUE THREAD

**Issue by lfnothias** [CCMS-UCSD/GNPS_Workflows#59]
Updating the description to clarify the issue with 30 days deletion (including when account in provided).
I am not sure where is the code for that.

**Comment by mwang87** [comment]
Duplicate of https://github.com/mwang87/GNPS_quickstart/issues/7

**Comment by mwang87** [comment]
@klj0019 Any updates on this?

**Comment by klj0019** [comment]
I thought I had finished this update. Was with the last pull request? Did I miss something?

**Comment by mwang87** [comment]
Can you please link the PR here and bump the PR saying its ready to be reviewed?

**Comment by mwang87** [comment]
These issues will need to be revisited as we are changing upload policy.
