### ISSUE TITLE
error in OPENMS (version release_13)

### ISSUE THREAD

**Issue by wonitawowowo** [CCMS-UCSD/GNPS_Workflows#607]
I want try the FBMN with OpenMS.And I use the .mzML file which have been successfully run in FBMN with XCMS/MZmine,but I got the error: https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=beb2f95b9f7f47a2b21bf21010daeeef.
I want to know where the error appear，so I also run it with the same .ini file in my PC use TOPPAS,  the FeatureFinderMetabo didn't rise an error but IDMapper did:

13:10:32 NOTICE: FeatureFinderMetabo of node #3 started. Processing ...
Progress of 'mass trace detection':

-- done [took 0.02 s (CPU), 0.01 s (Wall)] -- 
Progress of 'elution peak detection':

-- done [took 0.03 s (CPU), 0.03 s (Wall)] -- 
Progress of 'assembling mass traces to features':
Loading metabolite isotope model with 5% RMS error

-- done [took 0.02 s (CPU), 0.01 s (Wall)] -- 
-- FF-Metabo stats --
Input traces:    159
Output features: 145 (total trace count: 159)
FeatureFinderMetabo took 0.68 s (wall), 0.67 s (CPU), 0.08 s (system), 0.59 s (user).

==============================================================================
13:10:33 NOTICE: FeatureFinderMetabo of node #3 started. Processing ...
Progress of 'mass trace detection':

-- done [took 0.02 s (CPU), 0.01 s (Wall)] -- 
Progress of 'elution peak detection':

-- done [took 0.03 s (CPU), 0.03 s (Wall)] -- 
Progress of 'assembling mass traces to features':
Loading metabolite isotope model with 5% RMS error

-- done [took 0.00 s (CPU), 0.01 s (Wall)] -- 
-- FF-Metabo stats --
Input traces:    136
Output features: 123 (total trace count: 136)
FeatureFinderMetabo took 0.57 s (wall), 0.56 s (CPU), 0.03 s (system), 0.53 s (user).

==============================================================================
13:10:33 NOTICE: FeatureFinderMetabo finished!

==============================================================================
13:10:33 NOTICE: IDMapper of node #4 started. Processing ...
Error: The required parameter 'id' [valid: mzid, idXML] was not given or is empty!

==============================================================================
13:10:34 ERROR: IDMapper failed!
 
I saw the tutorial said: 
1.Input the mzML files.
2.Run the FeatureFinderMetabo tool on the mzML files.
3.Run the IDMapper tool on the featureXML and mzML files.
What I should do to get the .idXML/.mzid as IDMapper's input?
Could you give me some propose? Thank you a lot.

**Comment by wonitawowowo** [comment]
I found I had use the wrong version.When I switch to version release_20,the error wouldn't be rised up anymore.But I might a new error :https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=f7a66392f08449bdbf4759c839f579d5
it said :
FeatureLinkerUnlabeledQT: error while loading shared libraries: libxerces-c-3.2.so: cannot open shared object file: No such file or directory

What should i do?
and could you tell me when I run opensMS on my pc where could I get the IDMapper's input id?

**Comment by lfnothias** [comment]
Hi, @abisarvepalli had been pushing for a new release of the GNPSExport tool (that scales even more), and a new GNPS workflow as well. I will let @abisarvepalli advise on these.

**Comment by wonitawowowo** [comment]
Thanks a lot.

**Comment by wonitawowowo** [comment]
in release_13 with the .ini file from:https://proteomics3.ucsd.edu/ProteoSAFe/status.jsp?task=0b26b356f3e249b8a2848707fe4f65bb
and four .mzXML file, I could successfully run this workflow,but when i increase the number of .mzXML file ,a new error rise up :
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=a5848b6a35f44e3cae126360176e66e2

**Comment by abisarvepalli** [comment]
Hi @wonitawowowo, do you mind rerunning your tests on `release_20` of the workflow
https://proteomics3.ucsd.edu/ProteoSAFe/index.jsp?params=%7B%22workflow%22%3A%20%22OPENMS%22%2C%20%22workflow_version%22%3A%20%22openms%40release_20%22%7D

**Comment by wonitawowowo** [comment]
Thank you a lot @abisarvepalli .It looks while but when i download the outfile，there just two dir featurelinkerunlabeled and inifile in the .rar :
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=fc1624b1cbfa41538bbb983c4e1c5c04 
And logfile in  featurelinkerunlabeled said:
Warning: Parameters file version (2.4.0-HEAD-HASH-NOTFOUND-HEAD-HASH-NOTFOUND) does not match the version of this tool (2.6.0-pre-develop-2020-05-28).
Your current parameters are still valid, but there might be new valid values or even new parameters. Upgrading the INI might be useful.
Error: The required parameter 'in' was not given or is empty!
So I try to use my featurelinker.ini which stored from the openms on my PC.:
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=1a0c1cdb7e9b4640b5249c8c85a49e8f
The logfile says:
Warning: The provided INI file does not contain any parameters specific for this tool (expected in 'FeatureLinkerUnlabeledQT:1:'). Please check your .ini file. The default parameters for this tool will be applied.
Error: The required parameter 'in' was not given or is empty!
I think that might because of my  wrong .ini file ,could give me an example?

**Comment by wonitawowowo** [comment]
Hi @abisarvepalli I try the same .mzXMLfile in release_13 :https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=f0c706789a244f9f89ba77ea053f09de  And openms@release_20 And release_20 rise this error :Error: The required parameter 'in' was not given or is empty!

**Comment by abisarvepalli** [comment]
Apologize for the delayed response and not attaching the proper ini files corresponding to the updated version of openms.

[openms_2.4-default_ini_files.zip](https://github.com/CCMS-UCSD/GNPS_Workflows/files/5251735/openms_2.4-default_ini_files.zip)

I've attached the files here; will follow this closely until you are able to get a successful run :) There was an issue with the mapaligner and metaboliteadductdecharger parsing empty peaks that has since been addressed with the updated workflow.

**Comment by wonitawowowo** [comment]
> Apologize for the delayed response and not attaching the proper ini files corresponding to the updated version of openms.
> 
> [openms_2.6-default_ini_files.zip](https://github.com/CCMS-UCSD/GNPS_Workflows/files/5251768/ini-files.zip)
> 
> I've attached the files here; will follow this closely until you are able to get a successful run :) There was an issue with the mapaligner and metaboliteadductdecharger parsing empty peaks that has since been addressed with the updated workflow.

Thanks a lot. Could you tell my where the updated workflow is？I can't find it.

**Comment by abisarvepalli** [comment]
Should be able to rerun the workflow here:

https://proteomics2.ucsd.edu/ProteoSAFe/index.jsp?params=%7B%22workflow%22%3A%20%22OPENMS%22%2C%20%22workflow_version%22%3A%20%22openms%40release_20%22%7D

**Comment by wonitawowowo** [comment]
> 应该能够在这里重新运行工作流：
> 
> [Https://proteomics2.ucsd.edu/ProteoSAFe/index.jsp?params=%7B%22workflow%22%3A%20%22OPENMS%22%2C%20%22workflow_version%22%3A%20%22openms%40release_20%22%7D](https://proteomics2.ucsd.edu/ProteoSAFe/index.jsp?params=%7B%22workflow%22%3A%20%22OPENMS%22%2C%20%22workflow_version%22%3A%20%22openms%40release_20%22%7D)

It run success but still rise ：Error: The required parameter 'in' was not given or is empty! in feature link. :
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=a9baa3a60bff461aafbb3968c3d3a775

**Comment by wonitawowowo** [comment]
> 应该能够在这里重新运行工作流：
> 
> [Https://proteomics2.ucsd.edu/ProteoSAFe/index.jsp?params=%7B%22workflow%22%3A%20%22OPENMS%22%2C%20%22workflow_version%22%3A%20%22openms%40release_20%22%7D](https://proteomics2.ucsd.edu/ProteoSAFe/index.jsp?params=%7B%22workflow%22%3A%20%22OPENMS%22%2C%20%22workflow_version%22%3A%20%22openms%40release_20%22%7D)

I tried several times and it looks differently.I tried with about 500 .mzML file ,then fialed and said:
Workflow node [metabolite-adduct-decharger] was forcibly terminated by the computational back end.
The most likely reason is for exceeding this node's memory usage quota.
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=b262eadabb514d3480feadc369440772

Then I reduce it to 8 .mzML file ，still got this error：
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=382cbed4d713458488af7c304dc28b6d


Maybe i should try to run it with openms on my local PC to use more memory？By the way how can I make the .idXML as the IDMapper's id input?

**Comment by wonitawowowo** [comment]
> Should be able to rerun the workflow here:
> 
> https://proteomics2.ucsd.edu/ProteoSAFe/index.jsp?params=%7B%22workflow%22%3A%20%22OPENMS%22%2C%20%22workflow_version%22%3A%20%22openms%40release_20%22%7D

I tried several times and it looks differently.I tried with about 500 .mzML file ,then failed and said:
Workflow node [metabolite-adduct-decharger] was forcibly terminated by the computational back end.
The most likely reason is for exceeding this node's memory usage quota.
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=b262eadabb514d3480feadc369440772

Then I reduce it to 8 .mzML file ，still got this error：
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=382cbed4d713458488af7c304dc28b6d

Maybe i should try to run it with openms on my local PC to use more memory？By the way how can I make the .idXML as the IDMapper's id input?

**Comment by wonitawowowo** [comment]
> > Should be able to rerun the workflow here:
> > https://proteomics2.ucsd.edu/ProteoSAFe/index.jsp?params=%7B%22workflow%22%3A%20%22OPENMS%22%2C%20%22workflow_version%22%3A%20%22openms%40release_20%22%7D
> 
> I tried several times and it looks differently.I tried with about 500 .mzML file ,then failed and said:
> Workflow node [metabolite-adduct-decharger] was forcibly terminated by the computational back end.
> The most likely reason is for exceeding this node's memory usage quota.
> https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=b262eadabb514d3480feadc369440772
> 
> Then I reduce it to 8 .mzML file ，still got this error：
> https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=382cbed4d713458488af7c304dc28b6d
> 
> Maybe i should try to run it with openms on my local PC to use more memory？By the way how can I make the .idXML as the IDMapper's id input?

This beacuse I false use the default parameter which lead to too much peaks.
I rise noise threshold int to 1000，the error changed：https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=de9333349c6d435598230a2fcf0f8184

**Comment by abisarvepalli** [comment]
Still investigating, will provide a response by EOD

**Comment by wonitawowowo** [comment]
It run successfully in a small input(8 .mzML file),but for a large one(about 500),gnps-export failed:
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=374a5327cbe54845832b30fd9bdbd76b

**Comment by abisarvepalli** [comment]
Been able to update the workflow version! 

Currently rerunning your original workflow on said version:
https://proteomics2.ucsd.edu/ProteoSAFe/index.jsp?params=%7B%22workflow%22%3A%20%22OPENMS%22%2C%20%22workflow_version%22%3A%20%22release_20%2Bopenms%22%7D

**Comment by abisarvepalli** [comment]
Working on making this the default version once we are able to benchmark on your job :)

**Comment by wonitawowowo** [comment]
> Working on making this the default version once we are able to benchmark on your job :)

https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=cf0db6a73d344652a34b53e9009be122
It looks like rise the same error.

**Comment by wonitawowowo** [comment]
And I try to run the workflow on my pc to find where my problem is.This is the openms-workflow I run.
![BY3FQ1TVET64POUY`I~)~J3](https://user-images.githubusercontent.com/59105944/94652340-73223c80-032c-11eb-9d58-80489af76768.png)

It looks run successfully but don't get the .mgf output
![){BB36OL6@BWKKCY {L8XVG](https://user-images.githubusercontent.com/59105944/94653198-c5b02880-032d-11eb-85a5-75ed5070beb1.png)

And I find i don't get the right IDmapper out put
![{_WV9}`M)1LR%Y4W9}N{LXV](https://user-images.githubusercontent.com/59105944/94652748-1bd09c00-032d-11eb-9c39-7518b54354d0.png)
The IDmapper -id input which I use, is empty.idmxl which I get in your github link:
Bioinformatic-squad-DorresteinLab/openms-gnps-tools/empty.idXML

Can you tell me my mistake？Very grateful for your help.

**Comment by wonitawowowo** [comment]
> Working on making this the default version once we are able to benchmark on your job :)

It successfully runs，thanks a lot！
