### ISSUE TITLE
mzXML file parsing fails due to a NoneType object access

### ISSUE THREAD

**Issue by kostyanoob** [CCMS-UCSD/GNPS_Workflows#612]
**Describe the bug**
mzXML files are not parsed at all. Failing at [line 40 of mzxml.py](https://github.com/CCMS-UCSD/GNPS_Workflows/blob/ffc7d96845a60c492c317ffd2ad9d8ddebb33adc/mshub-gc/tools/mshub-gc/proc/io/mzxml.py#L40) **"TypeError: 'NoneType' object is not subscriptable"**

**To Reproduce**
Go to the web interface in [this link](https://www.google.com/url?q=https://github.com/CCMS-UCSD/GNPS_Workflows/tree/ffc7d96845a60c492c317ffd2ad9d8ddebb33adc/mshub-gc/tools/mshub-gc/proc/io&sa=D&source=hangouts&ust=1601303250672000&usg=AFQjCNHhnpGOiCwy5WI6xw48lNVq8F7crQ)
Click on "processing-deconvolution", plug in any legal mzXML file that you have (or use the file I attached), and receive the following error:

**Screenshots**
![2020-09-27](https://user-images.githubusercontent.com/42372287/94367866-d1aba880-00e9-11eb-8fe0-fe9eb0b30f10.png)

`Traceback (most recent call last): 
  File "/data/ccms-gnps/tools/mshub-gc/release_16/proc/io/importmsdata.py", line 629, in mzxml_reader mzXML_scans = mzxml.load_mzxml_file(filepath) `
`    File "/data/ccms-gnps/tools/mshub-gc/release_16/proc/io/mzxml.py", line 40, in load_mzxml_file read_scans = mzxml['mzXML']['msRun']['scan'] TypeError: 'NoneType' object is not subscriptable Traceback (most recent call last): `
`      File "/data/ccms-gnps/tools/mshub-gc/release_16/proc/io/importmsdata.py", line 629, in mzxml_reader mzXML_scans = mzxml.load_mzxml_file(filepath) `
`        File "/data/ccms-gnps/tools/mshub-gc/release_16/proc/io/mzxml.py", line 40, in load_mzxml_file read_scans = mzxml['mzXML']['msRun']['scan'] TypeError: 'NoneType' object is not subscriptable`

**Expected behavior**
Receiving a deconvolution solution

**Additional context**
The obvious reason for the bug is that at [line 39 of the same file](https://github.com/CCMS-UCSD/GNPS_Workflows/blob/ffc7d96845a60c492c317ffd2ad9d8ddebb33adc/mshub-gc/tools/mshub-gc/proc/io/mzxml.py#L39) the mzxml object is set to None, thus becoming non-subscriptable.

**Comment by mwang87** [comment]
Thanks for the report. In our documentation we note that we support mzML and CDF files.  

https://ccms-ucsd.github.io/GNPSDocumentation/gc-ms-deconvolution/#configure-the-workflow

If you need help converting to mzML, our documentation includes that as well:

https://ccms-ucsd.github.io/GNPSDocumentation/fileconversion/

Definitely let us know if these don't work for you!
