### ISSUE TITLE
MSHUB-GC  FAILED

### ISSUE THREAD

**Issue by zhangsz999** [CCMS-UCSD/GNPS_Workflows#634]
Now I have a question！i.e.The MS analyze is failed-https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=ff7e2da890b44a2482436ff6d558cc3f
The constant error is：

FAILED
[Clone] [Clone to Latest Version]
Unsupported extension
Tool execution terminates abnormally with exit code [1]

**Comment by mwang87** [comment]
GNPS does not support raw files. You'll have to convert to mzML. 

https://ccms-ucsd.github.io/GNPSDocumentation/fileconversion/
