### ISSUE TITLE
[FBMN] FBMN job (v26) fails with SIRIUS LCMS-Align workflow

### ISSUE THREAD

**Issue by Adafede** [CCMS-UCSD/GNPS_Workflows#644]
I am using the new FBMN export option of SIRIUS 4.5.0 GUI resulting in the classical quant table file and MGF file. 

- There is a small "trick" in the quant table file that is indexed by feature ID but on a char basis ( i.e. 1,10,100,1000...2...20...). Maybe it could be a problem. 
- However, there is no "SIRIUS" possibility when choosing the quant table tool used when submitting the job, so maybe letting mzmine was not the right option.
- the MGF contains duplicate feature IDs although labelled differently (eg. `SPECTYPE=CORRELATED MS`), I don't know if the issue could come from there also.

**To Reproduce**
I'll develop more if needed

**Expected behavior**
The job to run normally, maybe to have SIRIUS option

**Screenshots**
Tell me if needed

**Additional context**
Tell me if needed

**Comment by Adafede** [comment]
**EDIT**: I realized that I ticked the ms1 option, thus writing MS1 info into the MGF, labelled as said  `SPECTYPE=CORRELATED MS` and ms_level = 1... so anyway my fault but maybe would be great to add a filter MS1 or filter correlated_ms option :)

**Comment by lfnothias** [comment]
Hi Adrian,
Thanks for trying our experimental features ! 
Indeed, our aim is to have SIRIUS processing connected to FBMN. This is still in development and will release a functional workflow + documentation in the coming weeks. Stay tune !

**Comment by mwang87** [comment]
@Adafede We had a hiccup in the server side causing those errors. Try it again and hopefully we'll see what happens.

**Comment by Adafede** [comment]
Hi both, 

I launched the jobs again and it works, so no problem with the experimental features, nice! 👍🏼 

Thanks
