### ISSUE TITLE
[FBMN] The Networking Parameters and Description page seems broken in release 27

### ISSUE THREAD

**Issue by lfnothias** [CCMS-UCSD/GNPS_Workflows#670]
The page "Networking Parameters and Description" seems broken in release 27. See two different jobs where it fails. 
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=929ce9411f684cf8abd009670b293a33
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=f09b15fe1e6f45e396fdf1c03539ab94

Note that it worked in release 26.

**Comment by mwang87** [comment]
it works in neither for me

**Comment by lfnothias** [comment]
These links are both from release 27.
