### ISSUE TITLE
[CMN] The link "Annotate with Dereplicator+" takes to the UpSet plot page

### ISSUE THREAD

**Issue by lfnothias** [CCMS-UCSD/GNPS_Workflows#671]
In CMN results page, the link "Annotate with Dereplicator+" takes to the UpSet plot page.
See this link:  https://gnps.ucsd.edu/ProteoSAFe/result.jsp?task=ce4f631e7a2b4ea9b7696878e83684c4&view=dereplicatorplus

**Comment by mwang87** [comment]
addressed in release 28.

**Comment by lfnothias** [comment]
Nice!
