### ISSUE TITLE
 View qiime2 Emperor Plots and View Qemistree ITOL Tree  error

### ISSUE THREAD

**Issue by jeep3** [CCMS-UCSD/GNPS_Workflows#679]
Hi, GNPS great members,
         Recently , View qiime2 Emperor Plots and View Qemistree ITOL Tree  channels doesn't seem to open it. The following error is indicated:
![image](https://user-images.githubusercontent.com/28469054/107131471-d6be0700-68d6-11eb-8bea-91caee6c5e4a.png) 
Is this my personal problem or are you upgrading this part? BTW, Is there an alternative method to do it? Thanks a lot.
Huali

**Comment by mwang87** [comment]
There were changes to how ITOL enabled access to their service and so currently this does not work. We aim in the next release to not use ITOL anymore and use empress so stay tuned!

**Comment by jeep3** [comment]
Thanks for clarifying the information, Dr.Wang.
