### ISSUE TITLE
Add Integration test for Metaboscape with ion mobility

### ISSUE THREAD

**Issue by mwang87** [CCMS-UCSD/GNPS_Workflows#69]
TODO: find link

**Comment by lfnothias** [comment]
Wait that link is actually an issue with MZMine-based FBMN

**Comment by lfnothias** [comment]
The issue is addressed here #74

**Comment by lfnothias** [comment]
This job can serve as test job.
Note that this is only one sample and no metadata.

Also, there is no more the ".d" extension at the end of the sample name, compare to the previous version.

**Comment by lfnothias** [comment]
Fixed the path to the MetaboScape

**Comment by lfnothias** [comment]
Yay ! The code deployed on proteomics2 is functional and I checked data/output consistency:
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=6aea1f4af97c4e579e1f6358fd0c5e76
