### ISSUE TITLE
Bug in FBMN for IIN

### ISSUE THREAD

**Issue by mwang87** [CCMS-UCSD/GNPS_Workflows#70]
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=d9c4449a61d645fca21ef3761e75a058

**Comment by mwang87** [comment]
Likely a character format issue with unicode and compatiblity in XML. Would recommend checking metadata and additional pairs file to make sure ascii compliant.

**Comment by lfnothias** [comment]
Hey @robinschmid, what do you think of that issue ?

**Comment by lfnothias** [comment]
The issue is probably in the edge file (added here and it was a csv) since it runs fine without it. It was exported with the latest MZmine from Robin's release.
[1907_EMPv2_INN_GNPS_edges_msannotation.txt](https://github.com/CCMS-UCSD/GNPS_Workflows/files/3678408/1907_EMPv2_INN_GNPS_edges_msannotation.txt)

**Comment by lfnothias** [comment]
@xsirdanielx

**Comment by robinschmid** [comment]
Somehow the line breaks are incorrect. 

What is your operating system?
What did you do to the 

 ![image](https://user-images.githubusercontent.com/10366914/66053029-e59de800-e531-11e9-9b0d-8987da1ff0fd.png)

**Comment by lfnothias** [comment]
Weird. I haven't modify the file.
This was exported on Ubuntu 18.04 with your latest MZmine version (kai_merge_2).
I can try exporting again to check.

**Comment by mwang87** [comment]
I would recommend not using NotePad on Windows as it doesn't render new lines properly as windows by default only shows return carriages. If you open it in code text editor it should show fine.

**Comment by robinschmid** [comment]
ok thats weird. Its fine in atom.
So Ming do you know the problem?
![image](https://user-images.githubusercontent.com/10366914/66206472-861a1680-e6b0-11e9-874e-8591a1cb3618.png)

**Comment by lfnothias** [comment]
It turns out that the issue is the metadata file I used ... sorry guys :)
Same job without metadata
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=8646e3489e724afe91dcb5ec5ac6ca78

**Comment by lfnothias** [comment]
This issue can be closed
