### ISSUE TITLE
Error adding cdf file to MASSIVE

### ISSUE THREAD

**Issue by mabelgon88** [CCMS-UCSD/GNPS_Workflows#701]
**Describe the bug**
I haven't been able to add two files to a MASSIVE dataset after several tries. The file was converted to CDF format using the chemstation file conversion tool, so I don't understand why the error says unknown filetype.  

**To Reproduce**
Steps/Task to reproduce the behavior:
1. Go to https://massive.ucsd.edu/ProteoSAFe/status.jsp?task=c6b1e799d80b4d99b1505754d46f2b8e
2. Job Failed

**Expected behavior**
I expect to know the explanation of the error. PEAK-00000.CDF has an unknown filetype (.cdf).
Tool execution terminates abnormally with exit code [1].
If is possible correct this error.

**Screenshots**

**Additional context**
This file was run in the same instrument and batch that the other files and converted with the same tool of ChemStation.

**Comment by mwang87** [comment]
It’s not an accepted file type for peak. Put in raw and should be fine.
