### ISSUE TITLE
Classical Molecular Networking Direct Cytoscape preview/download not working

### ISSUE THREAD

**Issue by carribre** [CCMS-UCSD/GNPS_Workflows#743]
**Describe the bug**
Classical molecular networking(METABOLOMICS-SNETS-V2 (version release_28.2)) direct cytoscape preview/download not working. when selected, page loads for short time then notification pops up "gnps-cytoscape.ucsd.edu says       Error in creating Cytoscape file, please utilize graphml import manually".

**To Reproduce**
Go to jobs, click on "done" under status column for CMN job, scroll down to "Advanced Views-External Visualization" click on "Direct Cystoscape Preview/download

**Expected behavior**
cytoscape molecular network preview pops up, with download options at the bottom with different formats

**Screenshots**
![image](https://user-images.githubusercontent.com/86746128/124029266-31551e00-d9b2-11eb-8ead-f022d300bf0d.png)

**Additional context**

**Comment by mwang87** [comment]
can you link the job?

**Comment by carribre** [comment]
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=30376b00af4d4f6e883025fa44bf48ad

**Comment by mwang87** [comment]
This is too large for our server to handle. Please create the network in Cytoscpae Manually. 

Ming
