### ISSUE TITLE
[feature request] Spectra metadata completeness

### ISSUE THREAD

**Issue by Adafede** [CCMS-UCSD/GNPS_Workflows#747]
Hi , it seems like you back-calculate some metadata (chemical classes, InChIKey, InChIKey-Planar) from the user input (SMILES only?) of a given spectrum ID, which is really nice!
However, it looks like the metadata values are not always filled. They mainly look to rely on the SMILES, however many spectrumIDs have only InChI as structural identifier. Some InChIs have their InChIKeys (and planar) linked to it, others do not.

Would it be possible to do something like:
1. if(is.null(SMILES)){calculate smiles(InChI)}
2. calculate InChIKey+Clasification(SMILES)
3. add 2 additional (or 1 at least) metadata starting from SMILES: SMILES-planar,InChI-planar?

Best,

**Comment by mwang87** [comment]
Do you mean in GNPS Networking or in the GNPS Library pages?

**Comment by mwang87** [comment]
Yes, that makes sense. I think it would be pretty straightforward, do you think you'd be able to submit a quick PR for it? Then we could test it out together? 

Best,

Ming

**Comment by Adafede** [comment]
Huh, will have to dive into some funny parts of GNPS! 

I'll do my best and hopefully submit one soon!

Thank you again for the responsiveness!

**Comment by mwang87** [comment]
Definitley, its kind of a mess and a rabbit hole so apologies. The business end of the code I think you're looking for is here: 

https://github.com/CCMS-UCSD/GNPS_Workflows/blob/master/metabolomics-snets-v2/tools/metabolomicsnetsv2/scripts/getGNPS_library_annotations.py#L143
