### ISSUE TITLE
Link to External Ressources broken in GNPS library entries ?

### ISSUE THREAD

**Issue by lfnothias** [CCMS-UCSD/GNPS_Workflows#75]
The "View External Ressources" doesn't seem to work anymore.
https://gnps.ucsd.edu/ProteoSAFe/gnpslibraryspectrum.jsp?SpectrumID=CCMSLIB00005436490#%7B%7D

**Comment by mwang87** [comment]
This page works: 

http://dorresteinappshub.ucsd.edu:5010/structureproxy?smiles=CN1C%3DNC2%3DC1C(%3DO)N(C(%3DO)N2C)C&inchi=1S%2FC8H10N4O2%2Fc1-10-4-9-6-5(10)7(13)12(3)8(14)11(6)2%2Fh4H%2C1-3H3

Maybe that structure has nothing?

**Comment by lfnothias** [comment]
Ok. The issue is related to the absence of stereochemistry in the SMILES. 

If the Pubchem search is done with the canonical SMILES there is no result:
https://pubchem.ncbi.nlm.nih.gov/#query=CCCCC(C)C1CC(%3DO)NCC(%3DO)NC(C(%3DO)NC(C(%3DO)NC(C(%3DO)NC(C(%3DO)O1)CC2%3DCC%3DCC%3DC2)C)CC(C)C)C(C)C

However, with the isomeric SMILES
https://pubchem.ncbi.nlm.nih.gov/#query=CCCCC(C)%5BC%40%40H%5D1CC(%3DO)NCC(%3DO)N%5BC%40H%5D(C(%3DO)N%5BC%40%40H%5D(C(%3DO)N%5BC%40H%5D(C(%3DO)N%5BC%40H%5D(C(%3DO)O1)CC2%3DCC%3DCC%3DC2)C)CC(C)C)C(C)C

It seems that NPAtlas and MiBiG handles the canonical SMILES fine.
