### ISSUE TITLE
Locally use code for MS2 clustering and generating molecule network

### ISSUE THREAD

**Issue by chetankm1992** [CCMS-UCSD/GNPS_Workflows#761]
Hi,
I am trying to use this code locally and input one or multiple mzml files to perform MS2 clustering and also generate the molecular network on clustered data.
I went through the readme and also different code files but could not find the instructions and the appropriate code files to do  mentioned tasks.
Could you please point me in the right direction that which files of this code can be used to input one or multiple mzml file and can do MS2 clustering and also generate the network.
Note: I have already used GNPS webapp and the amount of information it generates on the uploaded mzml files is very impressive. I want to do the same kind of task but locally.
Thanks!

**Comment by mwang87** [comment]
Happy to discuss any issues you have during office hours

**Comment by chetankm1992** [comment]
Thank you so much for replying @mwang87. Could you please let me know what are your office hours and how can we chat? Thanks

**Comment by mwang87** [comment]
https://ccms-ucsd.github.io/GNPSDocumentation/contact/
