### ISSUE TITLE
[spec2vec] Download empty file

### ISSUE THREAD

**Issue by Adafede** [CCMS-UCSD/GNPS_Workflows#791]
**Describe the bug**
When downloading spec2vec generated pairs, the file output while clicking on 'Download' is empty. When clicking on 'Export Filtered Results', the file is correct.

**To Reproduce**
Steps/Task to reproduce the behavior:
1. Generate a spec2vec job
2. Click on 'View Filtered Pairs'
3. Click on 'Download' (alternatively 'Export Filtered Results')
3. Open obtained file(s)

**Expected behavior**
Download button to output correct file

**Additional context**
spec2vec release_27

**Comment by mwang87** [comment]
oof the joys of being in super early releases! We're in the process of totally revamping all molecular networking, so stay tuned for easier things haha
