### ISSUE TITLE
can not proceed at the last step for IIMN

### ISSUE THREAD

**Issue by ouclpl** [CCMS-UCSD/GNPS_Workflows#795]
**Describe the bug**
When I go to the last step for IIMN according to the "Data Processing with MZmine for FBMN and IIN", there is a problem that I can not get the exported files including the Supplementary Pairs file. the problem is shown as below. Could you please help me? Thank you very much.
![image](https://user-images.githubusercontent.com/93566745/141881169-cb5b3d92-8d78-44a7-9c98-34c6dbe079bc.png)

**To Reproduce**
Steps/Task to reproduce the behavior:

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by mwang87** [comment]
@robinschmid would be the best person!

**Comment by robinschmid** [comment]
Thanks for using IIMN. 
In order to help you, I will need more information.

Can you post the whole log from the console that runs with MZmine? 

1. What are your parameters for the export to GNPS? 
2. Have you checked that the feature list is not empty?
3. What is your operating system?
4. What is the path to which you try to export your files? In case its a folder on a server or remote machine - maybe try to choose a simple local path where you have write access.

Best regards
Robin

**Comment by ouclpl** [comment]
[IIMN-error.txt](https://github.com/CCMS-UCSD/GNPS_Workflows/files/7543328/IIMN-error.txt)
here is the error file.

**Comment by robinschmid** [comment]
Thanks for sharing your logs. There seem to be multiple problems.

1. In the GNPS FBMN export module, you have to select a full path. Currently only a filename is selected. Just click on the button next to the parameter and select a full path.

2. Somehow you create 0 groups. Maybe your settings in the metaCorrelate grouping module are too strict? Try turning off the feature height correlation, check the "minimum samples paramter" and make sure you set it to 1 sample if you only process one sample. You can see it here:

> [12:04:31|FINEST|MainMenu]: Starting module metaCorrelate with parameters Peak lists: Aligned peak list, RT tolerance: 0.1 min, Sample set: false, Min height: 100000.0, Noise level: 10000.0, Min samples filter: true, Correlation grouping: true, Feature height correlation: true, Suffix (or auto): false
[12:04:31|FINEST|TaskQueue]: Adding task "Identification of groups in Aligned peak list scan events (lists)" to the task controller queue
[12:04:31|INFO|WorkerThread]: Starting processing of task Identification of groups in Aligned peak list scan events (lists)
[12:04:31|INFO|CorrelateGroupingTask]: Starting metaCorrelation search in Aligned peak list peaklists
[12:04:31|INFO|CorrelateGroupingTask]: Corr: Creating row2row correlation map
[12:04:31|INFO|CorrelateGroupingTask]: Corr: Correlations done with 0 R2R correlations and 0 F2F correlations

**Comment by ouclpl** [comment]
I have done the last step for IIMN, but I can not get the network, only three nodes there. Can you tell me some reason.
![image](https://user-images.githubusercontent.com/93566745/142712210-22a11730-2730-40cd-be1f-b0b94ad91b7b.png)
And here is the raw file:
[114-positive.zip](https://github.com/CCMS-UCSD/GNPS_Workflows/files/7573818/114-positive.zip)
