### ISSUE TITLE
Test MS2LDA.org task integration

### ISSUE THREAD

**Issue by mwang87** [CCMS-UCSD/GNPS_Workflows#80]

**Comment by mwang87** [comment]
These are the test cases:

https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=aaff02c11f514d8db203b31b6b5058c1
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=fe0eab89ab55416c82cdf3e6bba96014
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=1626073f6f224862bc852139a5c61be7
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=1b96965e4629442dbedd39ec5e25bd4f
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=eac9a6df8cda40d588fd51451f44bc02

**Comment by laserc** [comment]
#135

**Comment by mwang87** [comment]
merged, will continue to merge into master and test out on proteomics.
