### ISSUE TITLE
molecular-library-search-v2 bug at the get_dbannotations step

### ISSUE THREAD

**Issue by adelabriere** [CCMS-UCSD/GNPS_Workflows#800]
I ran into a bug running the MOLECULAR-LIBRARYSEARCH-V2 workflow, I have an exception, possibly originating from an empty file somewhere during the processing. My input MGF is valid and can be opened programmatically using R MSnbase. The job is tagged as FAILED.

Link to the job [here](https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=8ffca8238556453abc4f72551cdde076)

The graph and exceptions are the following
![The graph](https://user-images.githubusercontent.com/17563377/144400991-c8293e10-539c-43ae-bed3-49b478e77671.png)
![The exception](https://user-images.githubusercontent.com/17563377/144401055-e0ae8e7c-8b4b-48f7-9dbc-d2987fdf78af.png)

Do you have any idea from where the problem can originates from and how to solve it ?

**Comment by mwang87** [comment]
THis means there are new hits.

**Comment by adelabriere** [comment]
Well at the moment it is just crashing the job. Is there a solution so that I can get the list of matches for this set of MS2 spectra ?

**Comment by mwang87** [comment]
Well there are no matches for this search so there is nothing to get.

**Comment by adelabriere** [comment]
Haaa thanks, since you said there "new" hits I was confused. Thanks it is clear now.

**Comment by mwang87** [comment]
Oh man just looked at the actual data a bit, negative polarity is rough on public libraries. Just in case it's relevant, how did you format the mgf file?

**Comment by adelabriere** [comment]
It was a SLAW output, the spectra are consensus MS-MS spectra. It worked fine on the same dataset in positive mode with exactly the same formatting, so I don't think the format is a problem. The data seems really emptier in negative mode so it does not surprise me that there is just 0 matches.

**Comment by mwang87** [comment]
Ok great. Yeah I'm always nervous when it comes to mgf since it's such a poorly defined format. One thing you could try in case you're interested is turning on analog search. We also have a few other libraries that are propogated that aren't selected by default.
