### ISSUE TITLE
FBMN: Error when trying to get File Summaries

### ISSUE THREAD

**Issue by LiesaSalzer** [CCMS-UCSD/GNPS_Workflows#806]
Hi all, 
I was trying to run FBMN on GNPS using the provided XCMS test files (https://github.com/CCMS-UCSD/GNPSDocumentation/tree/master/docs/tutorials/AG_tutorial_files)
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=cda2b01e477e4bd8870546bd8f0ff871

However, when I was trying to download the File Summaries I get following error message:

**There was an error retrieving the result data for block "main" of workflow type "FEATURE-BASED-MOLECULAR-NETWORKING".**

I was also changing input parameters and files, but still getting the same error. 

Any suggestions how to solve that error? 
Thanks!

**Comment by mwang87** [comment]
Oh yes, you'll need to simply add in the original mzML/mzXML files to have the file summaries show up.
