### ISSUE TITLE
Table (FeatureQuant) from GNPS FBMN with OpenMS misses info

### ISSUE THREAD

**Issue by eeko-kon** [CCMS-UCSD/GNPS_Workflows#824]
**Describe the bug**
For each feature, all groups have zero intensities. It looks as if no features were detected in any of the files, even though there is a feature list of course.

**To Reproduce**
 https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=30964ed8f6504e1cb980910a6777f620

**Expected behavior**
There has to be intensities assigned for visualization

**Additional context**
Attached csv exported table from cytoscape:
[Untitled.csv.zip](https://github.com/CCMS-UCSD/GNPS_Workflows/files/8200974/Untitled.csv.zip)

**Comment by mwang87** [comment]
You need to run the latest version on proteomics2. GNPS hasn't be updated with those fixes yet.

**Comment by eeko-kon** [comment]
Ok, I thought with "Clone to latest version" it would be fine. My bad! I re-run with the "version release_31+mzmine3-fbmn", but the problem persists.

https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=009eb9612ed0438198fcb1a6833e7dd2

**Comment by eeko-kon** [comment]
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=ad681d10c7974ee6b4018caea5deb3cb

Still the same issue in cytoscape. I think the reformatted table has a problem.

**Comment by eeko-kon** [comment]
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=2db52a1b6e2a4bf5ad04cddc7fee02aa

Still no intensities under any of the maps.

**Comment by eeko-kon** [comment]
Found the problem - filename related. Thanks a lot!
