### ISSUE TITLE
Problem visualizing mass spectra of corresponding selection on TIC plot with .CDF files

### ISSUE THREAD

**Issue by mabelgon88** [CCMS-UCSD/GNPS_Workflows#827]
**Describe the bug**
Hi Ming! I was trying to test the Dashboard with different datasets from GC-MS instruments that I have and I found that is working fine with Mzml datasets, but not with .CDF files.

**To Reproduce**
Steps/Task to reproduce the behavior:
1. Go to employing this tool: https://gnps-explorer.ucsd.edu/?dataset_accession=1fbca16f44b04c679a95faff4868e473&metadata_source=DEFAULT&metadata_option= 
2. Copy and paste the data accession: 1fbca16f44b04c679a95faff4868e473
3. Select some random files and click Visualize ## files  
4. Scroll down to TIC plot and "walk to the chromatogram"
5. You will see that the Mass spectra (MS spectrum plot) to the right changes changes until the correspondent MS1: 999 (around 5.5 minutes, but then if you select higher retention times the MS1: 1000 freeze in that number and also the mass spectra plot is the same. I tried this with several datasets and it is happening the same thing with all .CDF files. 

**Expected behavior**
I expect that the bug be solved for analyzing .CDF files or instructions of how can I solve this issue

**Screenshots**
I add screenshots to three different retention times. Two screenshots look like the same, but they are actually different poisitions in the TIC plot
![Screen Shot 2022-03-08 at 7 08 09 PM](https://user-images.githubusercontent.com/54383060/157365297-2ccb7c90-ed8b-400c-a579-e80910f0c675.png)
![Screen Shot 2022-03-08 at 7 08 21 PM](https://user-images.githubusercontent.com/54383060/157365301-bd8b10d0-7d2f-4db5-848e-a10e16c7b55f.png)
 

![Screen Shot 2022-03-08 at 7 07 50 PM](https://user-images.githubusercontent.com/54383060/157365287-8284862d-1573-40fe-9dd4-fc7e384a0af1.png)

**Additional context**
This bug is with GC-MS data in .CDF format

**Comment by mwang87** [comment]
Oh man, I think its how I'm writing the mzML files converted from CDF! Let me take a look really quickly, I think we can figure it out. 

Thanks @mabelgon88

**Comment by mwang87** [comment]
Fixed: https://gnps-lcms.ucsd.edu/#%7B%22usi%22%3A%20%22mzspec%3AGNPS%3ATASK-1fbca16f44b04c679a95faff4868e473-mabel_gonzalez/MYLF/Old/CONVERTED/190307017_021%20D.CDF%22%2C%20%22usi2%22%3A%20%22%22%7D
