### ISSUE TITLE
IIMN with OpenMS 

### ISSUE THREAD

**Issue by eeko-kon** [CCMS-UCSD/GNPS_Workflows#834]
**Describe the bug**

The network is collapsing, but the edges in a non-collapsed view are all the same. I should be able to see "cosine score" and "MS1 annotation" under "Style" - "Edges" - "EdgeType", only the option of "cosine score" is passed/offered. Meaning that the MS1 annotation under EdgeType information (SuppPairs.csv) is not passed for some reason. 

**To Reproduce**

Steps/Task to reproduce the behavior:
1. Go to 'https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=c442343427c24c20bcf24e8199440f25'
2. Files used https://drive.google.com/drive/folders/1vPgj6iaIavfejLIoat1_a8PzqYlSykZK?usp=sharing

**Comment by mwang87** [comment]
Can you run this on P2?

**Comment by eeko-kon** [comment]
Oh sorry Ming, I sent you the wrong job! 

https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=c442343427c24c20bcf24e8199440f25

**Comment by eeko-kon** [comment]
@mwang87  I was supposed to come to the office hours but never made it this week. Did you have time to look into that ? Thanks a lot!

**Comment by mwang87** [comment]
@robinschmid do you think the existing code for collapsing should have handled this for IIMN?

**Comment by eeko-kon** [comment]
Still nothing @mwang87 
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=95841335101b42adbacdbe330e98baa3

**Comment by eeko-kon** [comment]
Problem fixed!
