### ISSUE TITLE
FBMN - Support Mztab-m as input for quant

### ISSUE THREAD

**Issue by mwang87** [CCMS-UCSD/GNPS_Workflows#85]
Waiting for Steffen to send example files to test on.

**Comment by lfnothias** [comment]
Hey @sneumann 
Thanks a lot for the suggestion.
I would suggest to reuse one of the example here. https://github.com/DorresteinLaboratory/XCMS3_FeatureBasedMN

We could try exporting one mz-tab from the list of all peaks and one the list of peaks with MS2.

Also it would be perfect to include an CAMERA step, so we could see how the adduct information is reported in the mz-TAB and/or other more advanced results for CAMERA (that would contain information like score for adducts).

**Comment by sneumann** [comment]
Hi, mzTab-M is specified here
https://github.com/HUPO-PSI/mzTab
and example files are here
https://github.com/HUPO-PSI/mzTab/tree/master/examples/2_0-Metabolomics_Release
The MTBLS263.mztab also includes the reference to MS/MS spectra in the mzML files:
https://github.com/HUPO-PSI/mzTab/blob/master/examples/2_0-Metabolomics_Release/MTBLS263.mztab#L120
We do have a prototype xcms export (unfortunately based on old xcms1 interfaces, 
not yet xcms3) in an xcms branch https://github.com/sneumann/xcms/blob/writemzTab/R/writemztab.R#L226
Yours, Steffen

**Comment by mwang87** [comment]
Thanks Steffen, I think this is a good start. I think one of the missing portions is the MS2 spectra in one place. Do you imagine that mzTab-m would support simply referringin the future a consolidated MGF (or just some peak list file)? Or will it always refer to the full LC/MS mzML file. 

Either is fine, we just have to define it so we can pull out the spectra from an LCMS file. 

Ming

**Comment by sneumann** [comment]
Hi, currently the MS2 spectra are expected to be living in an mzML file.
https://hupo-psi.github.io/mzTab/2_0-metabolomics-release/mzTab_format_specification_2_0-M_release.html#spectra_ref 
Yours, Steffen

**Comment by mwang87** [comment]
Thanks. 

I think we'll do this for now, from the mzTab-m file we'll use that for the quantification information, and the user will have to provide the actual mzML files as well and we'll extract the MS2 spectra and collate them into something we can compute on within the workflow. 

I think this will be very doable, we'll take your example as a starting example. 

Ming

**Comment by mwang87** [comment]
Since we have a one to one correspondence between ms-run and assays, we will use assays for the quants and the MSF's as the features we show in FBMN. Then we will go into the actual files and extract the MS2s. Initial parsing of mzTab-M information completed..

**Comment by lfnothias** [comment]
It would be nice to have this available before the manuscript submission (next week).

**Comment by mwang87** [comment]
I got you! gotta change a few things around, will have working beta version with Steffen provided data working. Re-prioritizing. Also, can you clarify next week is monday or friday?

**Comment by lfnothias** [comment]
Next Friday. Lets already include the description of mz-tab support.

**Comment by mwang87** [comment]
Being worked on in this PR: https://github.com/CCMS-UCSD/GNPS_Workflows/pull/107

**Comment by nilshoffmann** [comment]
@mwang @sneumann You are right about the indices. Thanks for spotting that. I do not know what the actual mzMLs look like, and MTD ms_run[1]-id_format is not defined in the referenced file, so the validator also has no chance to check the format. It should be scan instead of index. I will fix the examples tomorrow. I am tracking this here: https://github.com/lifs-tools/jmzTab-m/issues/26

**Comment by nilshoffmann** [comment]
@mwang87 I have just pushed the updated samples in https://github.com/HUPO-PSI/mzTab/issues/178
It will take a few more days to update the reference implementation jmzTab-M, adding support for validation of the ms run reference entries based on the defined ms_run[1-n]-id_format cv parameters.

**Comment by mwang87** [comment]
@nilshoffmann Thanks Nils, I think there is still a slight error in not the format but the content of the mzTabs, I continued the issue in the other thread. Thanks for all the help!

**Comment by mwang87** [comment]
Deployed in development server:

https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=85ad5b65a3214474af63e00e645141d6

Can input mztab-m and the spectra, extract the appropriate MS/MS spectra and create a molecular network.

**Comment by lfnothias** [comment]
This is so cool :). 
I am opening an issue for the documentation update.
