### ISSUE TITLE
Classical molecular networking failed 

### ISSUE THREAD

**Issue by lydia1201** [CCMS-UCSD/GNPS_Workflows#854]
![3B92E8B0-BA8D-42A8-90D7-9702BE891607](https://user-images.githubusercontent.com/71855567/202517681-40985e16-ec79-43a0-be6d-08085d6394aa.jpeg)

Hi 
I am running classical networking but I got this err a few times, can anyone help to solve the issue? 
here is the job link
http://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=76d7994e141e4029a6fd296b80a6c4a3

Thank you very much 

Lydia

**Comment by mwang87** [comment]
Would recommend default library selection and not selecting all the other libraires. 

Best,

Ming

**Comment by lydia1201** [comment]
Hi Mang,

I selected the default library, and run again, but still failed, got another err. 

![34399038-6290-4609-8958-1AFB88D20386](https://user-images.githubusercontent.com/71855567/202541841-3ef53f7f-b827-450b-95c2-bf172af4b9e0.png)

here is the job link
http://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=1921cc585c0744318dfa466b38b0ad54

Thank you 

Lydia

**Comment by mwang87** [comment]
Would recommend you use the latest version. you're running a hugely out of
date version of Molecular Networking. Click "Clone to Latest"

Best,

Ming

**Comment by lydia1201** [comment]
Worked by using the latest version and default library input. Thank you very much 

Lydia
