### ISSUE TITLE
Conversion of blanks and standards (LC-MS)

### ISSUE THREAD

**Issue by ThuridurNott** [CCMS-UCSD/GNPS_Workflows#855]
Hi
I am using the easy data conversion method given in the GNPS documentation where I put my LC-MS data files into the input folder and receive them in MzXML format in the output folder. We are several in the same group who use this method. However, despite all of us using the same LC-MS methods and getting similar outputs I am the only one who cannot convert the data files from my blank samples and standard samples from the LC-MS output to the MzXML file format using the converter. The converter works fine for my actual samples so I don't understand the problem. When I put the files in the input folder and press to convert blanks and standards don't appear in the output. We use Bruker programs for the LC (Compass HyStar and otof control) if that could have any effect.

**Comment by mwang87** [comment]
Strange. Happy to look together and discuss at my office hours:

https://ccms-ucsd.github.io/GNPSDocumentation/contact/#gnps-office-hours

**Comment by mwang87** [comment]
Strange, happy to look together in my office hours:

https://ccms-ucsd.github.io/GNPSDocumentation/contact/#gnps-office-hours

**Comment by ThuridurNott** [comment]
I think maybe I have figured it out. The problem is that my file names have a space (" ") in them whereas my colleagues' files do not, they use _. I tried changing the space in one of the files I could not convert to a _ instead and the conversion worked. My bad!

**Comment by mwang87** [comment]
Awesome! Let me know if you have any other issuess
