### ISSUE TITLE
The format of experiment file of Waters MSE data on MS-DIAL

### ISSUE THREAD

**Issue by mhlsalvia** [CCMS-UCSD/GNPS_Workflows#859]
Dear developer,
My MES data were from Waters X2GS-QTof, and the low collision energy was 6 eV and the high collision energy ranged from 30 to 50 eV. When I dealt with Waters MSE data by MS-DIAL, it was needed to load an experiment file. I am not sure if the format of my experiment file was correct, so please help me to review whether the format of my experiment file was correct. My experiment file is as follow. 
Thanks for your help,
regards

ID	MS Type	Start m/z	End m/z	Name	CollisionEnergy	DecTarget
0	   ALL	       50	   1200	 MS2	        40	                    1
1	   ALL	       50	   1200	 MS2	        50	                    1
2	 SCAN	       50	   1200	 MS1	         6	                    1

**Comment by mwang87** [comment]
Here is the documentation to getting the output of MS-DIAL to work with GNPS:
https://ccms-ucsd.github.io/GNPSDocumentation/featurebasedmolecularnetworking-with-ms-dial/
