### ISSUE TITLE
error during GNPS molecular networking 

### ISSUE THREAD

**Issue by Vignesh291** [CCMS-UCSD/GNPS_Workflows#860]
Hello

I am new to using GNPS molecular networking. I am trying to process my mass spec data using the workflow: METABOLOMICS-SNETS-V2 (version release_30). I get the following errors:

"ERROR: ExecMsCluster.cpp : 192: Error executing MsCluster
ERROR: ExecMsCluster.cpp : 193: Check data is centroided and not profile
ERROR: main_specnets.cpp : 1040: Problem encountered during MsCluster stage
Tool execution terminates abnormally with exit code [1]"

http://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=155863c5762747f58f6772c26de3ce3f

My data is in centroid mode. I need inputs to solve this issue.

Thanks

**Comment by mwang87** [comment]
I dont think these are valid mzML files. I'd recommend using this conversion process: 

https://ccms-ucsd.github.io/GNPSDocumentation/fileconversion/
