### ISSUE TITLE
[FBMN] Jobs getting stuck?

### ISSUE THREAD

**Issue by siwook-hwang** [CCMS-UCSD/GNPS_Workflows#871]
I had a lot of problem getting FBMN to work so I downloaded the example data provided (MZMine version). When I upload those data, FBMN still seems to get stuck.
Run_dereplicator seems to be the bottleneck. Previous job of the same parameter got stuck at a similar point... Perhaps I am being too impatient?

Screenshot of the progress:
<img width="723" alt="image" src="https://github.com/CCMS-UCSD/GNPS_Workflows/assets/158392582/ecdbc23a-4b8f-4a84-a1fe-52ba68543a45">

Job link: https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=8fee5db732214bd094eb8ca9f5d1e7a9

Also my personal data is experiencing a similar thing: https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=c7ae63e9f384404f9bf7b117d0349cfc

Thank you in advance!

**Comment by mwang87** [comment]
I'd suggest trying GNPS2 quickstart for FBMN:

https://quickstart2.gnps2.org/FBMN_quickstart
