### ISSUE TITLE
Direct Cytoscape Preview/Download Error

### ISSUE THREAD

**Issue by kp1394** [CCMS-UCSD/GNPS_Workflows#876]
The link for the "Direct Cytoscape Preview/Download" is not working. After opening the link and attempting to load the page, a "502 Bad Gateway" server error appears.

This occurs anytime the Direct Cytoscape Preview/Download link is opened, regardless of when the job was run. 

I am expecting to see a preview of the network generated by the GNPS run with a link to download into Cytoscape. 

I am attaching a screenshot of the end result. 
<img width="1680" alt="Screen Shot 2024-05-23 at 12 04 50 PM" src="https://github.com/CCMS-UCSD/GNPS_Workflows/assets/115043939/dbbb1d9c-f000-4d32-af4a-4a4c17f6398b">

This has been brought up multiple times in the forum, most recently on May 17, but does not seem to have been resolved yet.

**Comment by mwang87** [comment]
Servers are being migrated on the GNPS2 side, please be patient.
