### ISSUE TITLE
GNPS BileAcidLibrary Release

### ISSUE THREAD

**Issue by mwang87** [CCMS-UCSD/GNPS_Workflows#88]
- [x] Create Batch
- [x] Run Library Creation
- [x] Validate Results
- [x] Write Description
- [x] Make Public
- [x] Add to Libraries Page

**Comment by mpanitch** [comment]
Hi Ming,

I assume these tasks you assigned are regarding the smaller library created by Emily, Alan and I?

This was the library I created with a blank mgf file here http://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=c816bf203d2d4b7a96666c61155a1023

The following is the descriptions of the library:

i. short name is BILELIB19
ii. MS2 spectra from commercial and synthesized bile acid standards
iii.  Reference MS2 spectra for 21 commercial bile acids and 4 synthesized amino acid conjugated bile acids run in positive and negative mode, including spectra of observed adducts. 

I have a few questions regarding your tasks for the bile acid library let me know when you have time to chat.

**Comment by mwang87** [comment]
Waiting on next deployment
