### ISSUE TITLE
What should I do if I have more than 6 groups for GNPS analyzing?

### ISSUE THREAD

**Issue by diaorao** [CCMS-UCSD/GNPS_Workflows#880]
Hi,
I'm now following the guide in GNPS document and I didn't find a specific way to create a GNPS job includes more than 6 groups, and I have 8. What the latest progress I have is I uploaded all my MS data to MASSIVE and made it public, and I filled the REDU form. Is that form the most important part for me to add more groups? I'm not so sure how to make it. So please if anyone see this issue would you please help me, thank you so much!
Luna

**Comment by mwang87** [comment]
This should help:

https://wang-bioinformatics-lab.github.io/GNPS2_Documentation/metadata/#barebones-metadata
