### ISSUE TITLE
bug or large dataset?

### ISSUE THREAD

**Issue by marwa38** [CCMS-UCSD/GNPS_Workflows#881]
Hey 

I am not sure if that could be considered as a bug. I am trying to create CMN classical molecuar newtwork on my 644 samples. I tried the first thing by changing the node label to be by library match and I get this pop up window and nothing change
![image](https://github.com/user-attachments/assets/1cdfbcce-0c51-4f3b-b03c-7f470ab20012)

here is my job in case interested to have a look: https://gnps2.org/status?task=6c575621d34f459b8e5f1eeb8683aed1

Thanks for your advice in advance
Marwa

**Comment by mwang87** [comment]
The dataset is quite large, so please view the individual components separately.

**Comment by marwa38** [comment]
That doesn't work too.
