### ISSUE TITLE
[GC] Public GC libraries release at GNPS

### ISSUE THREAD

**Issue by mwang87** [CCMS-UCSD/GNPS_Workflows#89]

**Comment by mwang87** [comment]
@aaksenov1 Please list all the libraries that we intend to make public here.

**Comment by mwang87** [comment]
I need 

- [ ] Library Name
- [ ] Library Description
- [ ] Link to Library
- [ ] Location to store on server

**Comment by aaksenov1** [comment]
1.
Library Name: Fiehn 
Library Description: Mass spectral and retention index libraries for metabolomics based on quadrupole and time-of-flight gas chromatography/mass spectrometry. Compiled 2,212 electron impact mass spectra and retention indices for quadrupole and time-of-flight GC/MS for over 1,000 primary metabolites below 550 Da, covering lipids, amino acids, fatty acids, amines, alcohols, sugars, amino-sugars, sugar alcohols, sugar acids, organic phosphates, hydroxyl acids, aromatics, purines and sterols as methoximated and trimethylsilylated mass spectra under electron impact ionization.
Link to Library: https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=a99963ddcb314887afaa61e2bf894823

2. 
Library Name: HMDB 
Library Description: The Human Metabolome Database or HMDB (www.hmdb.ca) is a web-enabled metabolomic database containing comprehensive information about human metabolites along with their biological roles, physiological concentrations, disease associations, chemical reactions, metabolic pathways, and reference spectra.
Link to Library: http://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=27eb6967918041199110239b436f8be3

3. 
Library Name: MoNA 
Library Description: GC-MS portion of the MassBank of North America (MoNA) database. MoNA is a metadata-centric, auto-curating repository designed for efficient storage and querying of mass spectral records. It intends to serve as a the framework for a centralized, collaborative database of metabolite mass spectra, metadata and associated compounds. MoNA currently contains over 200,000 mass spectral records from experimental and in-silico libraries as well as from user contributions.
Link to Library: http://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=58c04d109dae48a9a2ff1cf08e4a0b6f

**Comment by mwang87** [comment]
We will put these libraries at CCMS_SpectralLibraries/GNPS_GC_Libraries

We will call the above libraries

1. GC-FIEHN
2. GC-HMDB
3. GC-MONA

**Comment by mwang87** [comment]
Outstanding tasks 

- [ ] Rename these libraires
- [ ] Copy MGF to appropraite location
- [ ] Make them default selection library search

**Comment by mwang87** [comment]
Do we have references for each of the entries so we can link to the original resource?

**Comment by mwang87** [comment]
Deployed and ready to use.

**Comment by aaksenov1** [comment]
Search works, matches look good. Example job:
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=d255788d2b8f472881cfc95cd8017c8a
