### ISSUE TITLE
Add MS-DIAL Test Job to Tests

### ISSUE THREAD

**Issue by mwang87** [CCMS-UCSD/GNPS_Workflows#92]
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=44eecfdc5ef44639ad6b8083d2cb0817

**Comment by lfnothias** [comment]
It should be fixed with the next proteomics2 deployment

**Comment by mwang87** [comment]
Rerunning on release_10 code:

https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=3891e7728e78426abb92f65979dbae36

**Comment by mwang87** [comment]
added and validated is working.
